// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-aba-routing-validator-v1","name":"ABA Routing Number Validator","slug":"aba-routing-validator","description":"Validate a US bank ABA/routing transit number using its mod-10 checksum.","category":"crypto","tags":["aba","routing","bank","checksum","mod-10"],"keywords":["aba routing number","routing transit number","rtn","bank routing","checksum","federal reserve"],"icon":"Banknote","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/aba-routing-validator","webPath":"/tools/aba-routing-validator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
