// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-adler32-checksum-v1","name":"Adler-32 Checksum","slug":"adler32-checksum","description":"Compute the Adler-32 checksum of text or a file, as used by zlib.","category":"crypto","tags":["adler32","checksum","hash","zlib","integrity"],"keywords":["adler-32","rfc 1950","zlib checksum","file checksum","integrity"],"icon":"FileDigit","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/adler32-checksum","webPath":"/tools/adler32-checksum/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
