// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-aes-cbc-text-v1","name":"AES-CBC Text Encrypt/Decrypt","slug":"aes-cbc-text","description":"Encrypt or decrypt text with AES-CBC using a passphrase-derived key and explicit IV.","category":"crypto","tags":["aes","cbc","encrypt","decrypt","pbkdf2"],"keywords":["aes-cbc","pbkdf2","symmetric encryption","iv","pkcs7","passphrase"],"icon":"Lock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/aes-cbc-text","webPath":"/tools/aes-cbc-text/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
