// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-aes-encrypt-decrypt-v1","name":"AES Encrypt / Decrypt","slug":"aes-encrypt-decrypt","description":"Encrypt and decrypt text with AES-GCM using a passphrase, producing self-contained Base64 output with embedded salt and IV.","category":"crypto","tags":["aes","encrypt","decrypt"],"keywords":["aes","encrypt","decrypt","aes-gcm","cipher","passphrase"],"icon":"Lock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/aes-encrypt-decrypt","webPath":"/tools/aes-encrypt-decrypt/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
