// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-aes-gcm-file-v1","name":"AES-GCM File Encrypt/Decrypt","slug":"aes-gcm-file","description":"Encrypt or decrypt a chosen file in-browser with AES-GCM using a passphrase.","category":"crypto","tags":["aes","gcm","file","encrypt","decrypt"],"keywords":["aes-gcm","file encryption","pbkdf2","authenticated encryption","passphrase","in-browser"],"icon":"FileLock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/aes-gcm-file","webPath":"/tools/aes-gcm-file/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
