// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-bsb-validator-v1","name":"Australian BSB Lookup","slug":"bsb-validator","description":"Validate and parse an Australian Bank State Branch (BSB) number into bank, state, and branch.","category":"crypto","tags":["bsb","bank","australia","lookup","parse"],"keywords":["bsb","bank state branch","australian bank","routing","sort code","branch"],"icon":"University","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/bsb-validator","webPath":"/tools/bsb-validator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
