// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-certificate-chain-builder-v1","name":"Certificate Chain Builder","slug":"certificate-chain-builder","description":"Inspect pasted PEM certificate chains and flag ordering, duplicate subjects, and missing intermediates.","category":"crypto","tags":["certificate","chain","tls","pem"],"keywords":["certificate","chain","tls","pem"],"icon":"FileStack","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/certificate-chain-builder","webPath":"/tools/certificate-chain-builder/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
