// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-certificate-decoder-x509-v1","name":"X.509 Certificate Decoder","slug":"certificate-decoder-x509","description":"Decode PEM certificate structure and extract subject, issuer, validity, SAN hints, and fingerprints when visible.","category":"crypto","tags":["certificate","x509","tls","pem"],"keywords":["certificate","x509","tls","pem"],"icon":"FileBadge","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/certificate-decoder-x509","webPath":"/tools/certificate-decoder-x509/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
