// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-crypto-mod10-mod11-check-digit-v1","name":"Mod-10 / Mod-11 Check Digit Calculator","slug":"crypto-mod10-mod11-check-digit","description":"Computes and verifies Mod-10 (Luhn) and Mod-11 check digits for arbitrary numeric strings.","category":"crypto","tags":["check-digit","luhn","mod-10","mod-11","checksum"],"keywords":["check digit","luhn","mod 10","mod 11","checksum","verify","isbn","weighted"],"icon":"Calculator","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/crypto-mod10-mod11-check-digit","webPath":"/tools/crypto-mod10-mod11-check-digit/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
