// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-crypto-argon2-params-advisor-v1","name":"Argon2 Parameter Advisor","slug":"crypto-argon2-params-advisor","description":"Recommend Argon2id memory, iteration, and parallelism parameters for a target environment.","category":"crypto","tags":["argon2","argon2id","password","kdf","owasp"],"keywords":["argon2","argon2id","rfc 9106","owasp","password hashing","memory cost","time cost","phc"],"icon":"ShieldCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/crypto-argon2-params-advisor","webPath":"/tools/crypto-argon2-params-advisor/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
