// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-csr-generator-validator-v1","name":"CSR Generator & Validator","slug":"csr-generator-validator","description":"Generate an OpenSSL CSR command and inspect pasted CSR PEM blocks.","category":"crypto","tags":["csr","certificate","openssl","tls"],"keywords":["csr","certificate","openssl","tls"],"icon":"FileKey","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/csr-generator-validator","webPath":"/tools/csr-generator-validator/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
