// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-ecdsa-sign-verify-v1","name":"ECDSA Sign & Verify","slug":"ecdsa-sign-verify","description":"Sign and verify messages with ECDSA over P-256/P-384/P-521 curves.","category":"crypto","tags":["ecdsa","signature","sign","verify","pem"],"keywords":["p-256","p-384","p-521","pkcs8","spki","webcrypto","r||s","signing"],"icon":"FileKey","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/ecdsa-sign-verify","webPath":"/tools/ecdsa-sign-verify/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
