// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-ecdsa-keypair-generator-v1","name":"ECDSA Key Pair Generator","slug":"ecdsa-keypair-generator","description":"Generate an elliptic-curve (P-256/P-384/P-521) key pair as PEM for ECDSA signing.","category":"crypto","tags":["ecdsa","elliptic curve","pem"],"keywords":["ecdsa","elliptic curve","key pair","pem","p-256","signing"],"icon":"Fingerprint","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/ecdsa-keypair-generator","webPath":"/tools/ecdsa-keypair-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
