// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-fletcher-checksum-v1","name":"Fletcher-16/32/64 Checksum","slug":"fletcher-checksum","description":"Compute Fletcher checksums (16, 32, and 64-bit) of input bytes.","category":"crypto","tags":["fletcher","checksum","hash","integrity"],"keywords":["fletcher-16","fletcher-32","fletcher-64","modular sum","error detection"],"icon":"FileDigit","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/fletcher-checksum","webPath":"/tools/fletcher-checksum/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
