// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-hash-text-v1","name":"Hash Text","slug":"hash-text","description":"Compute MD5, SHA-1, SHA-256/384/512, SHA-3, BLAKE3 and CRC32 digests of text — live, in your browser.","category":"crypto","tags":["md5","sha256","sha512","blake3","crc32","digest"],"keywords":["hash","checksum","digest","sha","md5","blake3","fingerprint"],"icon":"Hash","relatedTools":["hmac-generator","file-hash","base64-text"],"packageImportPath":"@open-utility-tools/core/tools/crypto/hash-text","webPath":"/tools/hash-text/","loadWasm":true} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
