// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-isbn-validator-v1","name":"ISBN-10 / ISBN-13 Validator","slug":"isbn-validator","description":"Validate ISBN-10 and ISBN-13 check digits and convert between the two formats.","category":"crypto","tags":["isbn","validator","checksum","book","check-digit"],"keywords":["isbn10","isbn13","ean","check digit","book number","convert isbn"],"icon":"Book","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/isbn-validator","webPath":"/tools/isbn-validator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
