// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-jwks-inspector-v1","name":"JWKS Inspector","slug":"jwks-inspector","description":"Inspect JSON Web Key Sets, key IDs, algorithms, use, key type, and rotation readiness.","category":"crypto","tags":["jwks","jwk","jwt","keys"],"keywords":["jwks","jwk","jwt","keys"],"icon":"KeyRound","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/jwks-inspector","webPath":"/tools/jwks-inspector/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
