// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-jwt-verify-rsa-es-v1","name":"JWT Verifier (RS/ES)","slug":"jwt-verify-rsa-es","description":"Verify a JWT signature against an RSA or ECDSA public key and check standard claims.","category":"crypto","tags":["jwt","verify","rsa","ecdsa","signature"],"keywords":["rs256","es256","ps256","spki","jwk","public key","json web token"],"icon":"ShieldCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/jwt-verify-rsa-es","webPath":"/tools/jwt-verify-rsa-es/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
