// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-jwt-verify-hmac-v1","name":"JWT Signature Verifier (HS256)","slug":"jwt-verify-hmac","description":"Verify an HMAC-signed JWT (HS256/384/512) against a secret and report whether the signature and expiry are valid.","category":"crypto","tags":["jwt","hmac","verify"],"keywords":["jwt","verify","hs256","hmac","signature","validate"],"icon":"ShieldCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/jwt-verify-hmac","webPath":"/tools/jwt-verify-hmac/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
