// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-luhn-validator-v1","name":"Luhn Checksum Validator","slug":"luhn-validator","description":"Validate any Luhn-based number (credit cards, IMEI, etc.) and compute its check digit.","category":"crypto","tags":["luhn","checksum","credit-card","validator","mod10"],"keywords":["luhn algorithm","mod 10","imei","credit card check","check digit","iin"],"icon":"CreditCard","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/luhn-validator","webPath":"/tools/luhn-validator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
