// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-md5-hash-v1","name":"MD5 Hash Generator","slug":"md5-hash","description":"Generate the MD5 hash of any text, with lowercase or uppercase hex output (the algorithm Web Crypto omits).","category":"crypto","tags":["md5","hash","digest"],"keywords":["md5","hash","checksum","digest","fingerprint","message digest"],"icon":"Hash","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/md5-hash","webPath":"/tools/md5-hash/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
