// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-passphrase-entropy-meter-v1","name":"Passphrase Entropy Meter","slug":"passphrase-entropy-meter","description":"Estimate the bits of entropy in a passphrase based on its character set and length.","category":"crypto","tags":["entropy","password","security","strength","passphrase"],"keywords":["password strength","bits of entropy","crack time","guess","charset"],"icon":"Gauge","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/passphrase-entropy-meter","webPath":"/tools/passphrase-entropy-meter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
