// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-password-generator-v1","name":"Password Generator","slug":"password-generator","description":"Generate strong random passwords or diceware passphrases, locally.","category":"crypto","tags":["password","passphrase","random","secure","diceware"],"keywords":["password","passphrase","generator","random","secure","diceware","strength"],"icon":"KeyRound","relatedTools":["uuid-generator","hmac-generator","hash-text"],"packageImportPath":"@open-utility-tools/core/tools/crypto/password-generator","webPath":"/tools/password-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
