// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-random-bytes-generator-v1","name":"Random Bytes Generator","slug":"random-bytes-generator","description":"Generate cryptographically secure random bytes as hex, Base64, Base64URL, or a C-style byte array of a chosen length.","category":"crypto","tags":["random","bytes","crypto"],"keywords":["random bytes","secure random","hex","nonce","iv","entropy"],"icon":"Sparkles","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/random-bytes-generator","webPath":"/tools/random-bytes-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
