// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-rsa-sign-verify-v1","name":"RSA Sign & Verify","slug":"rsa-sign-verify","description":"Sign messages with an RSA private key and verify signatures with a public key (RSASSA-PKCS1 / PSS).","category":"crypto","tags":["rsa","sign","verify","signature","pss"],"keywords":["rsassa","pkcs1","pkcs8","spki","pem","digital signature"],"icon":"FileBadge","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/rsa-sign-verify","webPath":"/tools/rsa-sign-verify/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
