// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-scrypt-style-kdf-params-v1","name":"KDF Parameter Planner","slug":"scrypt-style-kdf-params","description":"Compute memory, time, and output sizes for PBKDF2/scrypt/Argon2 parameter sets without running them.","category":"crypto","tags":["kdf","scrypt","argon2","pbkdf2","planner"],"keywords":["key derivation","memory cost","owasp","n r p","parameters","tuning"],"icon":"Calculator","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/scrypt-style-kdf-params","webPath":"/tools/scrypt-style-kdf-params/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
