// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-secret-scanner-redactor-v1","name":"Secret Scanner & Redactor","slug":"secret-scanner-redactor","description":"Scan pasted code, logs, configs, diffs or .env files for leaked API keys, tokens, passwords and private keys, then copy a redacted version that is safe to share.","category":"crypto","tags":["secrets","redact","security","api keys","leak"],"keywords":["secret scanner","redact secrets","api key detector","leaked credentials","env file","gitleaks","trufflehog","mask password","sanitize logs","aws key","github token","private key","jwt","before sharing with ai"],"icon":"ShieldCheck","relatedTools":["jwt-decoder","password-strength-checker","hash-text"],"packageImportPath":"@open-utility-tools/core/tools/crypto/secret-scanner-redactor","webPath":"/tools/secret-scanner-redactor/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
