// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-sha-multi-hash-text-v1","name":"SHA Multi-Hash (Text)","slug":"sha-multi-hash-text","description":"Compute SHA-1, SHA-256, SHA-384, and SHA-512 digests of pasted text simultaneously.","category":"crypto","tags":["sha","hash","digest","checksum","sha256"],"keywords":["sha1","sha384","sha512","base64","hex","fingerprint"],"icon":"Hash","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/sha-multi-hash-text","webPath":"/tools/sha-multi-hash-text/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
