// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-webhook-signature-verifier-v1","name":"Webhook Signature Verifier","slug":"webhook-signature-verifier","description":"Verify HMAC webhook signatures used by GitHub, Slack, Stripe-style integrations.","category":"crypto","tags":["webhook","hmac","signature","security"],"keywords":["webhook","hmac","signature","security"],"icon":"Webhook","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/webhook-signature-verifier","webPath":"/tools/webhook-signature-verifier/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
