// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"crypto-xor-cipher-v1","name":"XOR Cipher","slug":"xor-cipher","description":"Encrypt or decrypt text with a repeating-key XOR, output as hex or Base64 and back.","category":"crypto","tags":["cipher","xor","encrypt"],"keywords":["xor","cipher","encrypt","decrypt","repeating key","obfuscate"],"icon":"Blend","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/crypto/xor-cipher","webPath":"/tools/xor-cipher/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
