// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-arbitrary-base-converter-v1","name":"Arbitrary Base Converter (2-36)","slug":"arbitrary-base-converter","description":"Convert an integer between any two radixes from base 2 to base 36 with full digit-set support.","category":"math","tags":["base","radix","converter","bigint","number"],"keywords":["arbitrary base","radix converter","base 36","base conversion","bigint","number system"],"icon":"ArrowLeftRight","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/arbitrary-base-converter","webPath":"/tools/arbitrary-base-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
