// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-arithmetic-geometric-sequence-v1","name":"Arithmetic & Geometric Sequence Calculator","slug":"arithmetic-geometric-sequence","description":"Find the nth term and sum of arithmetic or geometric sequences.","category":"math","tags":["sequence","series","arithmetic","geometric","sum"],"keywords":["arithmetic sequence","geometric sequence","nth term","series sum","common ratio","common difference","progression"],"icon":"ListOrdered","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/arithmetic-geometric-sequence","webPath":"/tools/arithmetic-geometric-sequence/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
