// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-aspect-ratio-calculator-v1","name":"Aspect Ratio Calculator","slug":"aspect-ratio-calculator","description":"Find a missing width or height for a target aspect ratio and reduce any resolution to its simplest ratio.","category":"math","tags":["math","image","video"],"keywords":["aspect ratio","resolution","16:9","width height","screen"],"icon":"Crop","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/aspect-ratio-calculator","webPath":"/tools/aspect-ratio-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
