// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-base-n-arithmetic-v1","name":"Base-N Arithmetic Calculator","slug":"base-n-arithmetic","description":"Add, subtract, multiply, and divide numbers in any base 2–36.","category":"math","tags":["base","arithmetic","radix","bigint","calculator"],"keywords":["base arithmetic","hex math","binary math","radix calculator","base 36","add hex","multiply binary"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/base-n-arithmetic","webPath":"/tools/base-n-arithmetic/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
