// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-binary-to-gray-code-v1","name":"Binary ↔ Gray Code Converter","slug":"binary-to-gray-code","description":"Convert between standard binary and reflected Gray code at any bit width.","category":"math","tags":["gray code","binary","encoding","bits","converter"],"keywords":["gray code","binary to gray","gray to binary","reflected binary","rotary encoder","karnaugh"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/binary-to-gray-code","webPath":"/tools/binary-to-gray-code/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
