// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-bit-rotate-shift-v1","name":"Bit Rotate & Shift Visualizer","slug":"bit-rotate-shift","description":"Apply logical/arithmetic shifts and circular rotations to a fixed-width integer and watch each bit move.","category":"math","tags":["bitwise","shift","rotate","binary","visualizer"],"keywords":["bit shift","logical shift","arithmetic shift","rotate left","rotate right","bitwise","rol ror shl shr"],"icon":"RotateCw","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/bit-rotate-shift","webPath":"/tools/bit-rotate-shift/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
