// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-bitwise-v1","name":"Bitwise Calculator","slug":"bitwise-calculator","description":"Perform AND, OR, XOR, NOT and shifts on two integers, shown in all bases.","category":"math","tags":["bitwise","and","or","xor","shift","binary"],"keywords":["bitwise","and or xor","bit shift","binary operations","mask"],"icon":"Binary","relatedTools":["number-base-converter","binary-text","prime-checker"],"packageImportPath":"@open-utility-tools/core/tools/math/bitwise-calculator","webPath":"/tools/bitwise-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
