// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-break-even-calculator-v1","name":"Break-Even Point Calculator","slug":"break-even-calculator","description":"Find the units and revenue needed to cover fixed and variable costs.","category":"math","tags":["break-even","finance","business","profit","costs"],"keywords":["break even","break-even point","contribution margin","fixed costs","variable costs","profit","cvp analysis"],"icon":"Crosshair","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/break-even-calculator","webPath":"/tools/break-even-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
