// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-cooking-converter-v1","name":"Cooking Measurement Converter","slug":"cooking-converter","description":"Convert kitchen measurements between cups, tablespoons, teaspoons, milliliters, ounces, and grams.","category":"math","tags":["converter","cooking","everyday"],"keywords":["cooking","cups tablespoons","recipe","milliliters","kitchen"],"icon":"Droplet","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/cooking-converter","webPath":"/tools/cooking-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
