// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-data-rate-converter-v1","name":"Data Transfer Rate Converter","slug":"data-rate-converter","description":"Convert data transfer rates between bps, Kbps, Mbps, Gbps, and bytes-per-second equivalents.","category":"math","tags":["converter","data","networking"],"keywords":["data rate","bandwidth","mbps","bitrate","convert"],"icon":"Network","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/data-rate-converter","webPath":"/tools/data-rate-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
