// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-discount-calculator-v1","name":"Discount & Sale Price Calculator","slug":"discount-calculator","description":"Find sale price, savings, and effective discount including stacked discounts.","category":"math","tags":["discount","sale","price","savings","percent"],"keywords":["markdown","coupon","stacked discount","final price","off","reduction"],"icon":"Tag","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/discount-calculator","webPath":"/tools/discount-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
