// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-divisibility-rules-checker-v1","name":"Divisibility Rules Checker","slug":"divisibility-rules-checker","description":"Test divisibility of a number by 2-13 and show which mental-math rule applies.","category":"math","tags":["divisibility","rules","number-theory","remainder","mental-math"],"keywords":["divisible","modulo","digit sum","factor","tricks","multiple"],"icon":"CheckCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/divisibility-rules-checker","webPath":"/tools/divisibility-rules-checker/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
