// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-divisor-lister-v1","name":"Divisor Lister & Counter","slug":"divisor-lister","description":"List every divisor of a number with totals, divisor count, and divisor pairs.","category":"math","tags":["divisors","factors","number-theory","sigma","aliquot"],"keywords":["factor list","divisor count","divisor sum","proper divisors","perfect number"],"icon":"List","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/divisor-lister","webPath":"/tools/divisor-lister/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
