// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-duration-converter-v1","name":"Time Duration Converter","slug":"duration-converter","description":"Convert durations between milliseconds, seconds, minutes, hours, days, and weeks.","category":"math","tags":["math","time","convert"],"keywords":["duration","time","seconds minutes hours","milliseconds","convert"],"icon":"Timer","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/duration-converter","webPath":"/tools/duration-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
