// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-exponent-power-calculator-v1","name":"Exponent & Power Calculator","slug":"exponent-power-calculator","description":"Raise numbers to powers, find roots, and evaluate scientific exponent expressions.","category":"math","tags":["exponent","power","root","logarithm","radical"],"keywords":["nth root","square root","pow","base","solve exponent","index"],"icon":"Superscript","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/exponent-power-calculator","webPath":"/tools/exponent-power-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
