// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-factorial-calculator-v1","name":"Factorial Calculator","slug":"factorial-calculator","description":"Compute exact n!, double factorial, and subfactorial for large integers.","category":"math","tags":["factorial","combinatorics","bigint","derangement"],"keywords":["n!","double factorial","subfactorial","derangement","exact","big number"],"icon":"Sigma","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/factorial-calculator","webPath":"/tools/factorial-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
