// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-fibonacci-calculator-v1","name":"Fibonacci & Lucas Number Generator","slug":"fibonacci-calculator","description":"Compute the nth Fibonacci/Lucas number and list the sequence exactly.","category":"math","tags":["fibonacci","lucas","sequence","golden-ratio","bigint"],"keywords":["fib","nth fibonacci","lucas numbers","golden ratio","phi","fast doubling"],"icon":"Spline","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/fibonacci-calculator","webPath":"/tools/fibonacci-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
