// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-fixed-point-converter-v1","name":"Fixed-Point (Qm.n) Converter","slug":"fixed-point-converter","description":"Convert real numbers to and from signed/unsigned Qm.n fixed-point integer representations.","category":"math","tags":["fixed-point","q-format","dsp","binary","embedded"],"keywords":["Qm.n","fixed point","quantization","twos complement","fractional bits","Q15"],"icon":"Ruler","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/fixed-point-converter","webPath":"/tools/fixed-point-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
