// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-fraction-simplifier-v1","name":"Fraction Simplifier","slug":"fraction-simplifier","description":"Reduce any fraction to lowest terms and show the mixed-number and decimal forms.","category":"math","tags":["fraction","simplify","reduce","gcd","mixed-number"],"keywords":["lowest terms","simplify fraction","repeating decimal","repetend","gcd","reduce"],"icon":"Minimize2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/fraction-simplifier","webPath":"/tools/fraction-simplifier/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
