// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-fraction-decimal-converter-v1","name":"Fraction & Decimal Converter","slug":"fraction-decimal-converter","description":"Convert fractions to decimals and decimals to simplified fractions, detecting repeating decimals.","category":"math","tags":["math","convert","numbers"],"keywords":["fraction","decimal","simplify","ratio","repeating decimal"],"icon":"Diff","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/fraction-decimal-converter","webPath":"/tools/fraction-decimal-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
