// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-fuel-economy-converter-v1","name":"Fuel Economy Converter","slug":"fuel-economy-converter","description":"Convert fuel efficiency between MPG (US/UK), km/L, and liters per 100 km.","category":"math","tags":["math","conversion","automotive"],"keywords":["fuel economy","mpg","l/100km","km/l","mileage"],"icon":"Gauge","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/fuel-economy-converter","webPath":"/tools/fuel-economy-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
