// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-gcd-lcm-v1","name":"GCD & LCM Calculator","slug":"gcd-lcm","description":"Find the greatest common divisor and least common multiple of numbers.","category":"math","tags":["gcd","lcm","divisor","multiple","factor"],"keywords":["gcd","lcm","greatest common divisor","least common multiple","hcf"],"icon":"Sigma","relatedTools":["prime-checker","percentage-calculator","number-base-converter"],"packageImportPath":"@open-utility-tools/core/tools/math/gcd-lcm","webPath":"/tools/gcd-lcm/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
