// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-integer-factorization-v1","name":"Integer Factorization Explorer","slug":"integer-factorization","description":"Fully factor an integer into primes and explore all derived multiplicative properties.","category":"math","tags":["factorization","primes","number-theory","totient","divisors"],"keywords":["prime factors","euler totient","phi","divisors","sigma","omega","radical","pollard rho"],"icon":"Boxes","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/integer-factorization","webPath":"/tools/integer-factorization/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
