// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-logarithm-calculator-v1","name":"Logarithm & Antilog Calculator","slug":"logarithm-calculator","description":"Evaluate logs in any base plus natural/common logs and their antilogs.","category":"math","tags":["logarithm","antilog","math","change-of-base","exponent"],"keywords":["log","ln","log10","log2","natural log","common log","antilogarithm","base"],"icon":"SquareFunction","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/logarithm-calculator","webPath":"/tools/logarithm-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
