// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-markup-margin-calculator-v1","name":"Markup & Margin Calculator","slug":"markup-margin-calculator","description":"Convert between cost, price, markup, and profit margin.","category":"math","tags":["markup","margin","pricing","profit","business"],"keywords":["markup vs margin","gross margin","cost","selling price","profit","retail pricing"],"icon":"Receipt","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/markup-margin-calculator","webPath":"/tools/markup-margin-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
