// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-math-linear-system-solver-v1","name":"Linear System Solver (Ax = b)","slug":"math-linear-system-solver","description":"Solves a system of linear equations using Gaussian elimination and reports the solution.","category":"math","tags":["linear-algebra","gaussian-elimination","matrix","equations","solver"],"keywords":["linear system","gaussian elimination","simultaneous equations","matrix solve","Ax=b","pivoting"],"icon":"SquareFunction","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/math-linear-system-solver","webPath":"/tools/math-linear-system-solver/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
