// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-math-matrix-determinant-inverse-v1","name":"Matrix Determinant & Inverse","slug":"math-matrix-determinant-inverse","description":"Computes the determinant, inverse, and rank of a small square matrix.","category":"math","tags":["matrix","determinant","inverse","linear algebra","rank"],"keywords":["matrix","determinant","inverse","rank","linear algebra","gaussian elimination","gauss jordan"],"icon":"Grid2x2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/math-matrix-determinant-inverse","webPath":"/tools/math-matrix-determinant-inverse/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
