// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-math-dms-decimal-degrees-v1","name":"DMS ↔ Decimal Degrees Converter","slug":"math-dms-decimal-degrees","description":"Convert geographic coordinates between degrees-minutes-seconds and decimal degrees.","category":"math","tags":["coordinates","dms","decimal-degrees","gps","geography"],"keywords":["dms","decimal degrees","latitude","longitude","gps coordinates","degrees minutes seconds"],"icon":"Compass","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/math-dms-decimal-degrees","webPath":"/tools/math-dms-decimal-degrees/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
