// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-math-tax-bracket-calculator-v1","name":"Progressive Tax Bracket Calculator","slug":"math-tax-bracket-calculator","description":"Compute total tax across user-defined progressive income brackets.","category":"math","tags":["tax","brackets","income","finance","marginal rate"],"keywords":["tax","bracket","progressive","marginal rate","effective rate","income tax"],"icon":"Receipt","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/math-tax-bracket-calculator","webPath":"/tools/math-tax-bracket-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
