// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-math-aspect-ratio-resizer-v1","name":"Dimension Aspect-Ratio Solver","slug":"math-aspect-ratio-resizer","description":"Solve a missing width or height that preserves a given aspect ratio.","category":"math","tags":["aspect-ratio","resize","dimensions","scaling","pixels"],"keywords":["aspect ratio","resize","proportional","width","height","scale factor","gcd"],"icon":"Scaling","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/math-aspect-ratio-resizer","webPath":"/tools/math-aspect-ratio-resizer/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
