// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-math-gpa-calculator-v1","name":"GPA Calculator","slug":"math-gpa-calculator","description":"Compute weighted grade point average from courses, credits, and grades.","category":"math","tags":["gpa","grades","education","credits","average"],"keywords":["gpa","grade point average","weighted gpa","credit hours","letter grade","school"],"icon":"Award","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/math-gpa-calculator","webPath":"/tools/math-gpa-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
