// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-math-numeral-system-clock-v1","name":"Number System Visualizer","slug":"math-numeral-system-clock","description":"Show one integer simultaneously in binary, octal, decimal, hex, and custom base.","category":"math","tags":["binary","hexadecimal","octal","base","number system"],"keywords":["binary","hex","hexadecimal","octal","decimal","base converter","twos complement","radix"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/math-numeral-system-clock","webPath":"/tools/math-numeral-system-clock/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
