// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-matrix-calculator-v1","name":"Matrix Calculator","slug":"matrix-calculator","description":"Add, subtract, multiply, transpose, and find the determinant and inverse of small matrices.","category":"math","tags":["math","linear algebra"],"keywords":["matrix","determinant","inverse","transpose","linear algebra"],"icon":"Grid3x3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/matrix-calculator","webPath":"/tools/matrix-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
