// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-mean-median-mode-v1","name":"Mean, Median, Mode & Range","slug":"mean-median-mode","description":"Compute central-tendency measures from a list of numbers.","category":"math","tags":["mean","median","mode","statistics","average"],"keywords":["mean","median","mode","range","average","central tendency","geometric mean","harmonic mean"],"icon":"BarChart3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/mean-median-mode","webPath":"/tools/mean-median-mode/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
