// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-midpoint-calculator-v1","name":"Midpoint & Section Point Calculator","slug":"midpoint-calculator","description":"Find the midpoint or any ratio division point of a segment.","category":"math","tags":["midpoint","geometry","coordinate","section formula","segment"],"keywords":["midpoint","section formula","division point","coordinate geometry","segment length","ratio"],"icon":"Dot","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/midpoint-calculator","webPath":"/tools/midpoint-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
