// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-modulo-calculator-v1","name":"Modular Arithmetic Calculator","slug":"modulo-calculator","description":"Compute true modulo, modular addition, multiplication, and exponentiation with non-negative results.","category":"math","tags":["math","number theory","cryptography"],"keywords":["modulo","modular arithmetic","remainder","mod","exponentiation"],"icon":"Calculator","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/modulo-calculator","webPath":"/tools/modulo-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
