// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-modular-inverse-v1","name":"Modular Multiplicative Inverse","slug":"modular-inverse","description":"Find x such that a*x ≡ 1 (mod m) using the extended Euclidean algorithm.","category":"math","tags":["modular","inverse","number-theory","euclidean","cryptography"],"keywords":["mod inverse","modular arithmetic","extended euclid","bezout","gcd","rsa"],"icon":"Equal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/modular-inverse","webPath":"/tools/modular-inverse/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
