// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-mortgage-extra-payment-v1","name":"Mortgage Extra Payment Calculator","slug":"mortgage-extra-payment","description":"See how extra monthly payments cut your loan term and interest.","category":"math","tags":["mortgage","loan","amortization","finance","prepayment"],"keywords":["extra payment","pay off mortgage early","interest saved","amortization schedule","home loan"],"icon":"Home","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/mortgage-extra-payment","webPath":"/tools/mortgage-extra-payment/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
