// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-number-to-base64-v1","name":"Number to Base64 Encoder","slug":"number-to-base64","description":"Encode an integer as compact Base64 bytes and decode Base64 back to a number.","category":"math","tags":["base64","integer","encoding","bytes","token"],"keywords":["number to base64","big integer encode","url-safe base64","byte order","compact id"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/number-to-base64","webPath":"/tools/number-to-base64/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
