// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-number-base-v1","name":"Number Base Converter","slug":"number-base-converter","description":"Convert numbers between binary, octal, decimal, hex and arbitrary bases.","category":"math","tags":["base","binary","hex","octal","decimal","radix"],"keywords":["number base","binary","hexadecimal","octal","radix","convert","bin dec hex"],"icon":"Binary","relatedTools":["hex-text","bitwise-calculator","ascii-table"],"packageImportPath":"@open-utility-tools/core/tools/math/number-base-converter","webPath":"/tools/number-base-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
