// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-pace-calculator-v1","name":"Pace & Speed Calculator","slug":"pace-calculator","description":"Convert between running pace, speed, distance, and time for runs, walks, and cycling.","category":"math","tags":["math","fitness","running"],"keywords":["pace calculator","running","speed","min per km","marathon"],"icon":"Timer","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/pace-calculator","webPath":"/tools/pace-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
