// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-percent-increase-decrease-v1","name":"Percent Increase & Decrease","slug":"percent-increase-decrease","description":"Apply a percentage increase or decrease to a number and reverse it.","category":"math","tags":["percent","increase","decrease","reverse","finance"],"keywords":["percentage increase","percentage decrease","add percent","subtract percent","reverse percent","undo discount"],"icon":"TrendingUp","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/percent-increase-decrease","webPath":"/tools/percent-increase-decrease/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
