// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-percentage-calculator-v1","name":"Percentage Calculator","slug":"percentage-calculator","description":"Work out percentages, percentage change, and what-percent-of calculations.","category":"math","tags":["percentage","percent","calculator","change"],"keywords":["percentage","percent","increase","decrease","change","of"],"icon":"Percent","relatedTools":["roman-numerals","number-base-converter","unit-converter"],"packageImportPath":"@open-utility-tools/core/tools/math/percentage-calculator","webPath":"/tools/percentage-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
