// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-polar-cartesian-converter-v1","name":"Polar ↔ Cartesian Converter","slug":"polar-cartesian-converter","description":"Convert 2D points between polar (r, θ) and Cartesian (x, y) coordinates.","category":"math","tags":["polar","cartesian","coordinates","geometry","trigonometry"],"keywords":["polar to cartesian","cartesian to polar","radius angle","atan2","degrees radians","quadrant","r theta"],"icon":"Compass","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/polar-cartesian-converter","webPath":"/tools/polar-cartesian-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
