// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-prime-checker-v1","name":"Prime Checker & Factorizer","slug":"prime-checker","description":"Check whether a number is prime and view its prime factorization.","category":"math","tags":["prime","factor","factorization","number"],"keywords":["prime","is prime","prime factors","factorization","composite"],"icon":"Sigma","relatedTools":["gcd-lcm","number-base-converter","statistics"],"packageImportPath":"@open-utility-tools/core/tools/math/prime-checker","webPath":"/tools/prime-checker/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
