// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-prism-cylinder-volume-v1","name":"Prism & Cylinder Volume Calculator","slug":"prism-cylinder-volume","description":"Compute volume and surface area of cylinders, cubes, and box prisms.","category":"math","tags":["volume","surface-area","geometry","cylinder","prism"],"keywords":["cube volume","rectangular box","cylinder volume","surface area","lateral area","geometry calculator","cuboid"],"icon":"Cylinder","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/prism-cylinder-volume","webPath":"/tools/prism-cylinder-volume/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
