// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-quadratic-equation-solver-v1","name":"Quadratic Equation Solver","slug":"quadratic-equation-solver","description":"Solve quadratic equations for real or complex roots from coefficients a, b, and c.","category":"math","tags":["calculator","algebra","equations"],"keywords":["quadratic","equation","roots","discriminant","solver"],"icon":"Variable","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/quadratic-equation-solver","webPath":"/tools/quadratic-equation-solver/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
