// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-random-distribution-generator-v1","name":"Random Distribution Generator","slug":"random-distribution-generator","description":"Generate random samples from uniform, normal, exponential, or Poisson distributions.","category":"math","tags":["random","statistics","distribution","sampling","generator"],"keywords":["random sample","normal distribution","gaussian","box-muller","exponential","poisson","uniform","histogram","rng"],"icon":"ChartBar","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/random-distribution-generator","webPath":"/tools/random-distribution-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
