// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-rectangle-square-calculator-v1","name":"Rectangle & Square Calculator","slug":"rectangle-square-calculator","description":"Compute area, perimeter, and diagonal of rectangles and squares.","category":"math","tags":["rectangle","square","geometry","area","perimeter"],"keywords":["rectangle","square","area","perimeter","diagonal","aspect ratio","geometry","length","width"],"icon":"Square","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/rectangle-square-calculator","webPath":"/tools/rectangle-square-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
