// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-roi-calculator-v1","name":"ROI Calculator","slug":"roi-calculator","description":"Compute return on investment, net profit, and annualized ROI.","category":"math","tags":["roi","investment","finance","profit","return"],"keywords":["roi","return on investment","net profit","annualized return","gain","loss","profitability","finance"],"icon":"TrendingUp","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/roi-calculator","webPath":"/tools/roi-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
