// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-rounding-calculator-v1","name":"Rounding & Significant Figures","slug":"rounding-calculator","description":"Round numbers by decimals, significant figures, or a chosen rule.","category":"math","tags":["rounding","significant figures","precision","decimals","math"],"keywords":["rounding","significant figures","sig figs","bankers rounding","half even","half up","ceil","floor","truncate","nearest multiple"],"icon":"Calculator","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/rounding-calculator","webPath":"/tools/rounding-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
