// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-scientific-notation-converter-v1","name":"Scientific Notation Converter","slug":"scientific-notation-converter","description":"Convert numbers between plain decimal, scientific E-notation, and engineering notation.","category":"math","tags":["math","convert","numbers"],"keywords":["scientific notation","exponential","engineering notation","decimal","convert"],"icon":"Sigma","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/scientific-notation-converter","webPath":"/tools/scientific-notation-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
