// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-significant-figures-rounder-v1","name":"Significant Figures Rounder","slug":"significant-figures-rounder","description":"Round a number to a chosen number of significant figures and count its sig figs.","category":"math","tags":["significant-figures","rounding","precision","sigfigs","science"],"keywords":["sig figs","sig fig","round","precision","scientific notation","banker rounding"],"icon":"Target","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/significant-figures-rounder","webPath":"/tools/significant-figures-rounder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
