// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-simple-interest-calculator-v1","name":"Simple Interest Calculator","slug":"simple-interest-calculator","description":"Compute simple interest, total, or solve for any missing variable.","category":"math","tags":["interest","finance","loan","simple-interest","calculator"],"keywords":["simple interest","principal","rate","time","I=Prt","finance","loan"],"icon":"Banknote","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/simple-interest-calculator","webPath":"/tools/simple-interest-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
