// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-sphere-cone-pyramid-volume-v1","name":"Sphere, Cone & Pyramid Volume","slug":"sphere-cone-pyramid-volume","description":"Compute volume and surface area of spheres, cones, and pyramids.","category":"math","tags":["volume","geometry","surface-area","sphere","cone","pyramid"],"keywords":["volume","surface area","sphere","cone","pyramid","slant height","geometry"],"icon":"Triangle","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/sphere-cone-pyramid-volume","webPath":"/tools/sphere-cone-pyramid-volume/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
