// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-triangle-solver-v1","name":"Triangle Solver","slug":"triangle-solver","description":"Solve any triangle from 3 known sides/angles using the laws of sines and cosines.","category":"math","tags":["triangle","trigonometry","geometry","law-of-sines","law-of-cosines"],"keywords":["triangle solver","SSS","SAS","ASA","AAS","SSA","law of sines","law of cosines","trigonometry"],"icon":"Triangle","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/triangle-solver","webPath":"/tools/triangle-solver/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
