// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-twos-complement-converter-v1","name":"Two's Complement Converter","slug":"twos-complement-converter","description":"Encode and decode signed integers in two's complement across 8/16/32/64-bit widths.","category":"math","tags":["binary","twos-complement","signed","bits","encoding"],"keywords":["twos complement","two's complement","signed integer","binary","hex","bit width","sign bit"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/twos-complement-converter","webPath":"/tools/twos-complement-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
