// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-unit-price-calculator-v1","name":"Unit Price Comparison","slug":"unit-price-calculator","description":"Compare products by price per unit to find the best value.","category":"math","tags":["shopping","price","compare","value","unit"],"keywords":["unit price","price per unit","cost comparison","best value","price per gram","price per ml","grocery"],"icon":"Scale","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/unit-price-calculator","webPath":"/tools/unit-price-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
