// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-vector-calculator-2d-3d-v1","name":"Vector Calculator (2D/3D)","slug":"vector-calculator-2d-3d","description":"Add, subtract, dot, cross, normalize, and measure angle between vectors.","category":"math","tags":["vector","geometry","linear-algebra","physics","math"],"keywords":["vector","dot product","cross product","magnitude","normalize","unit vector","angle between vectors","projection","2d","3d"],"icon":"Navigation","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/vector-calculator-2d-3d","webPath":"/tools/vector-calculator-2d-3d/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
