// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"math-weighted-average-calculator-v1","name":"Weighted Average & Grade Calculator","slug":"weighted-average-calculator","description":"Compute a weighted mean from value-weight pairs, e.g. grades.","category":"math","tags":["average","mean","grades","statistics","weights"],"keywords":["weighted average","weighted mean","gpa","grade calculator","final grade","credits","mean"],"icon":"Scale","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/math/weighted-average-calculator","webPath":"/tools/weighted-average-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
