#!/usr/bin/env bun
/**
 * Generates package-level catalog entries for every browser tool.
 *
 * The functional core APIs are extracted category-by-category, but the npm
 * package should still expose a stable typed entry for every tool in the app.
 * This script mirrors the app registry scan and emits:
 *   src/tools/registry.ts
 *   src/tools/<category>/<slug>.ts
 */
import { Glob } from 'bun';
import { existsSync } from 'node:fs';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';

const PACKAGE_NAME = '@open-utility-tools/core';

const pkgDir = join(import.meta.dir, '..');
const repoRoot = join(pkgDir, '..', '..');
const toolsDir = join(repoRoot, 'tools');
const outDir = join(pkgDir, 'src', 'tools');
const registryOut = join(outDir, 'registry.ts');

const VALID_CATEGORIES = [
  'image',
  'pdf',
  'data',
  'convert',
  'text',
  'crypto',
  'encoding',
  'generators',
  'web',
  'time',
  'math',
  'color',
] as const;

type ToolCategory = (typeof VALID_CATEGORIES)[number];

interface RawToolConfig {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: string;
  tags?: string[];
  keywords?: string[];
  icon: string;
  relatedTools?: string[];
  loadWasm?: boolean;
  hidden?: boolean;
}

interface CatalogEntry extends RawToolConfig {
  category: ToolCategory;
  packageImportPath: string;
  webPath: string;
  coreImportPath?: string;
}

const directCoreApiOverrides: Record<string, string> = {
  'image/image-converter': `${PACKAGE_NAME}/image/convert`,
};

async function main() {
  const files = await scanToolConfigs();
  const tools = await loadTools(files);

  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  await writeFile(join(outDir, 'types.ts'), typesSource());
  await writeFile(join(outDir, 'index.ts'), indexSource());
  await writeFile(registryOut, registrySource(tools));

  for (const tool of tools) {
    const modulePath = join(outDir, tool.category, tool.slug + '.ts');
    await mkdir(dirname(modulePath), { recursive: true });
    await writeFile(modulePath, toolModuleSource(tool));
  }

  console.log(
    `gen-tools-catalog: wrote ${tools.length} tool entries under ${relative(pkgDir, outDir)}`,
  );
}

async function scanToolConfigs(): Promise<string[]> {
  const glob = new Glob('**/tool.config.ts');
  const files: string[] = [];
  for await (const file of glob.scan({ cwd: toolsDir })) {
    files.push(file);
  }
  files.sort();
  return files;
}

async function loadTools(files: string[]): Promise<CatalogEntry[]> {
  const categories = new Set<string>(VALID_CATEGORIES);
  const ids = new Set<string>();
  const slugs = new Set<string>();
  const entries: CatalogEntry[] = [];

  for (const rel of files) {
    const mod = await import(join(toolsDir, rel));
    const cfg = (mod.default ?? mod.config) as RawToolConfig | undefined;
    if (!cfg) throw new Error(`tool config has no default export: ${rel}`);

    const expectedPathKey = `${cfg.category}/${cfg.slug}`;
    if (!categories.has(cfg.category)) {
      throw new Error(`tool ${rel}: invalid category "${cfg.category}"`);
    }
    if (ids.has(cfg.id)) throw new Error(`duplicate id: ${cfg.id}`);
    if (slugs.has(cfg.slug)) throw new Error(`duplicate slug: ${cfg.slug}`);
    ids.add(cfg.id);
    slugs.add(cfg.slug);

    const category = cfg.category as ToolCategory;
    entries.push({
      ...cfg,
      category,
      tags: cfg.tags ?? [],
      keywords: cfg.keywords ?? [],
      relatedTools: cfg.relatedTools ?? [],
      packageImportPath: `${PACKAGE_NAME}/tools/${category}/${cfg.slug}`,
      webPath: `/tools/${cfg.slug}/`,
      coreImportPath:
        directCoreApiOverrides[expectedPathKey] ?? discoverDirectCoreApi(expectedPathKey),
    });
  }

  return entries.sort((a, b) => `${a.category}/${a.slug}`.localeCompare(`${b.category}/${b.slug}`));
}

function discoverDirectCoreApi(pathKey: string): string | undefined {
  // Current direct compute APIs live at src/<category>/<slug>.ts and are
  // exported as @open-utility-tools/core/<category>/<slug>.
  const [category, slug] = pathKey.split('/');
  if (!category || !slug) return undefined;
  const directPath = join(pkgDir, 'src', category, slug + '.ts');
  return existsSync(directPath) ? `${PACKAGE_NAME}/${category}/${slug}` : undefined;
}

function typesSource(): string {
  return `// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.

export const TOOL_CATEGORIES = ${JSON.stringify(VALID_CATEGORIES)} as const;

export type ToolCategory = (typeof TOOL_CATEGORIES)[number];

export interface ToolPackageEntry {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: ToolCategory;
  tags: readonly string[];
  keywords: readonly string[];
  icon: string;
  relatedTools: readonly string[];
  loadWasm?: boolean;
  hidden?: boolean;
  packageImportPath: string;
  webPath: string;
  coreImportPath?: string;
}
`;
}

function indexSource(): string {
  return `// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
export * from './types';
export * from './registry';
`;
}

function registrySource(tools: CatalogEntry[]): string {
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.');
  lines.push("import type { ToolPackageEntry } from './types';");
  lines.push('');
  lines.push('export const TOOL_CATALOG = [');
  for (const tool of tools) {
    lines.push(`  ${serializeTool(tool)},`);
  }
  lines.push('] as const satisfies readonly ToolPackageEntry[];');
  lines.push('');
  lines.push(
    'export const TOOL_CATALOG_BY_ID: ReadonlyMap<string, ToolPackageEntry> = new Map(TOOL_CATALOG.map((tool) => [tool.id, tool] as const));',
  );
  lines.push(
    'export const TOOL_CATALOG_BY_SLUG: ReadonlyMap<string, ToolPackageEntry> = new Map(TOOL_CATALOG.map((tool) => [tool.slug, tool] as const));',
  );
  lines.push(
    "export const TOOL_CATALOG_BY_PATH: ReadonlyMap<string, ToolPackageEntry> = new Map(TOOL_CATALOG.map((tool) => [`${tool.category}/${tool.slug}`, tool] as const));",
  );
  lines.push('');
  lines.push('export function getToolById(id: string): ToolPackageEntry | undefined {');
  lines.push('  return TOOL_CATALOG_BY_ID.get(id);');
  lines.push('}');
  lines.push('');
  lines.push('export function getToolBySlug(slug: string): ToolPackageEntry | undefined {');
  lines.push('  return TOOL_CATALOG_BY_SLUG.get(slug);');
  lines.push('}');
  lines.push('');
  lines.push('export function getToolByPath(category: string, slug: string): ToolPackageEntry | undefined {');
  lines.push('  return TOOL_CATALOG_BY_PATH.get(`${category}/${slug}`);');
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function toolModuleSource(tool: CatalogEntry): string {
  return `// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = ${serializeTool(tool)} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
`;
}

function serializeTool(tool: CatalogEntry): string {
  const obj: Record<string, unknown> = {
    id: tool.id,
    name: tool.name,
    slug: tool.slug,
    description: tool.description,
    category: tool.category,
    tags: tool.tags ?? [],
    keywords: tool.keywords ?? [],
    icon: tool.icon,
    relatedTools: tool.relatedTools ?? [],
    packageImportPath: tool.packageImportPath,
    webPath: tool.webPath,
  };
  if (tool.loadWasm) obj.loadWasm = true;
  if (tool.hidden) obj.hidden = true;
  if (tool.coreImportPath) obj.coreImportPath = tool.coreImportPath;
  return JSON.stringify(obj);
}

main().catch((error) => {
  console.error('gen-tools-catalog failed:', error);
  process.exit(1);
});
