// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-acceleration-converter-v1","name":"Acceleration Converter","slug":"acceleration-converter","description":"Convert acceleration between m/s2, g-force, ft/s2, and gal.","category":"convert","tags":["acceleration","physics","units","g-force","converter"],"keywords":["m/s2","gal","galileo","gravity","ft/s2","milligal","mph","kph"],"icon":"TrendingUp","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/acceleration-converter","webPath":"/tools/acceleration-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
