// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-area-converter-v1","name":"Area Converter","slug":"area-converter","description":"Convert areas between square meters, acres, hectares, square feet, and more.","category":"convert","tags":["area","unit","measurement","hectare","acre"],"keywords":["square meter","square feet","acre","hectare","square mile","are","land area"],"icon":"Square","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/area-converter","webPath":"/tools/area-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
