// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-astronomical-distance-converter-v1","name":"Astronomical Distance Converter","slug":"astronomical-distance-converter","description":"Convert cosmic distances between AU, light-years, parsecs, and kilometers.","category":"convert","tags":["astronomy","distance","space","unit","parsec"],"keywords":["light year","astronomical unit","au","parsec","kiloparsec","megaparsec","space distance"],"icon":"Rocket","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/astronomical-distance-converter","webPath":"/tools/astronomical-distance-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
