// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-convert-cron-to-human-and-quartz-v1","name":"Cron Dialect Translator","slug":"convert-cron-to-human-and-quartz","description":"Converts between standard 5-field cron and 6/7-field Quartz/Spring cron expressions.","category":"convert","tags":["cron","quartz","spring","schedule","convert"],"keywords":["cron","quartz","spring","unix cron","seconds field","day of week","translate"],"icon":"CalendarClock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/convert-cron-to-human-and-quartz","webPath":"/tools/convert-cron-to-human-and-quartz/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
