// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-convert-color-list-to-tailwind-config-v1","name":"Color List to Tailwind Config","slug":"convert-color-list-to-tailwind-config","description":"Turns a list of name=hex color pairs into a Tailwind theme.extend.colors config object.","category":"convert","tags":["tailwind","color","config","theme","css"],"keywords":["tailwind","colors","theme.extend","palette","hex","config","design tokens"],"icon":"Palette","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/convert-color-list-to-tailwind-config","webPath":"/tools/convert-color-list-to-tailwind-config/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
