// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-convert-cron-to-human-multi-v1","name":"Crontab File Explainer","slug":"convert-cron-to-human-multi","description":"Explain every line of a crontab file in plain English including special strings.","category":"convert","tags":["cron","crontab","schedule","explain","human"],"keywords":["crontab","cron explain","human readable","@daily","@reboot","schedule","plain english"],"icon":"CalendarClock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/convert-cron-to-human-multi","webPath":"/tools/convert-cron-to-human-multi/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
