// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-convert-csv-to-sql-insert-batch-v1","name":"CSV to Batched SQL INSERT","slug":"convert-csv-to-sql-insert-batch","description":"Generate multi-row batched SQL INSERT statements from CSV with a configurable batch size.","category":"convert","tags":["csv","sql","insert","database","batch","migration"],"keywords":["csv to sql","bulk insert","seed data","mysql","postgres","sqlite","ndjson"],"icon":"Database","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/convert-csv-to-sql-insert-batch","webPath":"/tools/convert-csv-to-sql-insert-batch/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
