// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-convert-har-to-curl-v1","name":"HAR Entry to cURL","slug":"convert-har-to-curl","description":"Extracts requests from a HAR file or single HAR entry and emits equivalent cURL commands.","category":"convert","tags":["har","curl","http","devtools","network"],"keywords":["har to curl","network log","request","replay","devtools export","fiddler"],"icon":"Terminal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/convert-har-to-curl","webPath":"/tools/convert-har-to-curl/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
