// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-convert-svg-to-jsx-v1","name":"SVG to JSX/React Component","slug":"convert-svg-to-jsx","description":"Converts a raw SVG markup into a React JSX component with camelCased attributes.","category":"convert","tags":["svg","jsx","react","component","tsx"],"keywords":["svg to jsx","svg to react","svgr","camelcase attributes","icon component"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/convert-svg-to-jsx","webPath":"/tools/convert-svg-to-jsx/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
