// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-convert-jsonl-to-sql-insert-v1","name":"JSON Lines to SQL INSERT","slug":"convert-jsonl-to-sql-insert","description":"Generates SQL INSERT statements from NDJSON records using each object's keys as columns.","category":"convert","tags":["ndjson","jsonl","sql","insert","database"],"keywords":["jsonl to sql","ndjson to sql","json lines","bulk insert","seed","import"],"icon":"Database","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/convert-jsonl-to-sql-insert","webPath":"/tools/convert-jsonl-to-sql-insert/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
