// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-css-shorthand-expander-v1","name":"CSS Shorthand Expander","slug":"css-shorthand-expander","description":"Expand CSS shorthand properties (margin, padding, border, font, background, etc.) into their longhand declarations, or collapse longhands back.","category":"convert","tags":["css","shorthand","longhand","stylesheet","expand"],"keywords":["css shorthand","expand margin","longhand","border shorthand","font shorthand","collapse"],"icon":"Code2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/css-shorthand-expander","webPath":"/tools/css-shorthand-expander/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
