// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-csv-to-tsv-v1","name":"CSV to TSV","slug":"csv-to-tsv","description":"Convert between comma-separated and tab-separated values with proper quote handling, in either direction, ready to paste into a spreadsheet.","category":"convert","tags":["csv","tsv","convert"],"keywords":["csv","tsv","tab","convert","spreadsheet","delimiter"],"icon":"ArrowLeftRight","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/csv-to-tsv","webPath":"/tools/csv-to-tsv/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
