// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-csv-to-markdown-v1","name":"CSV to Markdown Table","slug":"csv-to-markdown","description":"Convert CSV into a GitHub-flavored Markdown table.","category":"convert","tags":["csv","markdown","table","convert","gfm"],"keywords":["csv to markdown","markdown table","gfm table","convert csv"],"icon":"Table","relatedTools":["csv-to-json","json-to-csv","markdown-to-html"],"packageImportPath":"@open-utility-tools/core/tools/convert/csv-to-markdown","webPath":"/tools/csv-to-markdown/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
