// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-csv-to-yaml-v1","name":"CSV to YAML","slug":"csv-to-yaml","description":"Convert CSV rows into a YAML list of objects.","category":"convert","tags":["csv","yaml","convert","data","transform"],"keywords":["csv2yaml","spreadsheet","rfc4180","records","mapping"],"icon":"FileSpreadsheet","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/csv-to-yaml","webPath":"/tools/csv-to-yaml/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
