// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-curl-to-httpie-v1","name":"cURL to HTTPie","slug":"curl-to-httpie","description":"Convert a curl command into an equivalent HTTPie command.","category":"convert","tags":["curl","httpie","http","convert","api"],"keywords":["curl2httpie","request","rest","command","cli"],"icon":"Terminal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/curl-to-httpie","webPath":"/tools/curl-to-httpie/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
