// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-currency-unit-naming-v1","name":"Currency Subunit & Naming Reference","slug":"currency-unit-naming","description":"Look up world currencies, their subunits, symbols, and ISO 4217 codes.","category":"convert","tags":["currency","iso 4217","reference","subunit","symbols"],"keywords":["currency code","cent","penny","paisa","kopeck","minor unit","decimal digits","currency symbol"],"icon":"Coins","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/currency-unit-naming","webPath":"/tools/currency-unit-naming/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
