// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-data-storage-units-converter-v1","name":"Data Storage Units Converter","slug":"data-storage-units-converter","description":"Convert digital storage between bits, bytes, and decimal/binary multiples like MB vs MiB.","category":"convert","tags":["storage","bytes","bits","SI","IEC"],"keywords":["MB vs MiB","gigabyte gibibyte","nibble","bit byte","decimal binary storage","data units"],"icon":"HardDrive","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/data-storage-units-converter","webPath":"/tools/data-storage-units-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
