// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-dpi-ppi-size-converter-v1","name":"DPI / PPI Pixel-Size Converter","slug":"dpi-ppi-size-converter","description":"Convert between physical print size, pixel dimensions, and DPI — or compute a screen’s PPI from its resolution and diagonal.","category":"convert","tags":["dpi","ppi","print","pixels","resolution"],"keywords":["dots per inch","pixels per inch","print size","screen density","dot pitch"],"icon":"Scan","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/dpi-ppi-size-converter","webPath":"/tools/dpi-ppi-size-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
