// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-energy-converter-v1","name":"Energy Converter","slug":"energy-converter","description":"Convert energy between joules, calories, kWh, BTU, and electronvolts.","category":"convert","tags":["energy","joule","calorie","kwh","btu","physics"],"keywords":["energy","joule","kilojoule","calorie","kilocalorie","watt hour","kilowatt hour","kwh","btu","electronvolt","ev","erg","foot pound"],"icon":"Zap","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/energy-converter","webPath":"/tools/energy-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
