// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-env-to-shell-exports-v1","name":".env to Shell Exports","slug":"env-to-shell-exports","description":"Turn a .env file into copy-paste shell export statements for bash/zsh, fish, or PowerShell.","category":"convert","tags":["env","shell","bash","export","convert"],"keywords":["dotenv","zsh","fish","powershell","environment","variables"],"icon":"Terminal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/env-to-shell-exports","webPath":"/tools/env-to-shell-exports/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
