// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-force-converter-v1","name":"Force Converter","slug":"force-converter","description":"Convert force between newtons, kilogram-force, pound-force, and dyne.","category":"convert","tags":["force","newton","pound-force","dyne","physics","engineering"],"keywords":["force","newton","kilonewton","dyne","kilogram force","gram force","pound force","lbf","ounce force","poundal","kip"],"icon":"Dumbbell","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/force-converter","webPath":"/tools/force-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
