// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-frequency-converter-v1","name":"Frequency Converter","slug":"frequency-converter","description":"Convert frequency between Hz, kHz, MHz, GHz, RPM, and angular rad/s.","category":"convert","tags":["frequency","hertz","rpm","angular","bpm","physics"],"keywords":["frequency","hertz","hz","kilohertz","megahertz","gigahertz","rpm","rps","radian per second","angular frequency","bpm","degree per second"],"icon":"Activity","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/frequency-converter","webPath":"/tools/frequency-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
