// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-hex-to-rgb-code-v1","name":"Hex to RGB Code Snippet","slug":"hex-to-rgb-code","description":"Turn a hex color into ready-to-paste code in many languages.","category":"convert","tags":["color","hex","rgb","code","convert"],"keywords":["css","swift","flutter","android","uicolor","snippet","tailwind"],"icon":"Palette","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/hex-to-rgb-code","webPath":"/tools/hex-to-rgb-code/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
