// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-json-to-php-array-v1","name":"JSON to PHP Array","slug":"json-to-php-array","description":"Convert JSON into a PHP array literal.","category":"convert","tags":["json","php","array","convert","code"],"keywords":["json to php","php array","array literal","short syntax","export"],"icon":"Braces","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/json-to-php-array","webPath":"/tools/json-to-php-array/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
