// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-json-to-yaml-v1","name":"JSON to YAML","slug":"json-to-yaml","description":"Convert JSON into readable YAML.","category":"convert","tags":["json","yaml","convert","config"],"keywords":["json to yaml","yaml","convert","config"],"icon":"ArrowLeftRight","relatedTools":["yaml-to-json","json-formatter","json-to-csv"],"packageImportPath":"@open-utility-tools/core/tools/convert/json-to-yaml","webPath":"/tools/json-to-yaml/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
