// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-json-to-xml-attributes-v1","name":"JSON to XML (Attribute Mode)","slug":"json-to-xml-attributes","description":"Convert JSON to XML choosing attributes vs child elements.","category":"convert","tags":["json","xml","attributes","convert","serialize"],"keywords":["json to xml","xml attributes","@text convention","scalars as attributes","markup"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/json-to-xml-attributes","webPath":"/tools/json-to-xml-attributes/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
