// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-json-to-ruby-hash-v1","name":"JSON to Ruby Hash","slug":"json-to-ruby-hash","description":"Convert JSON into a Ruby hash literal.","category":"convert","tags":["json","ruby","hash","convert","code"],"keywords":["json to ruby","ruby hash","symbol keys","hashrocket","rails"],"icon":"Gem","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/json-to-ruby-hash","webPath":"/tools/json-to-ruby-hash/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
