// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-json-array-to-list-v1","name":"JSON Array to List","slug":"json-array-to-list","description":"Convert a JSON array into a delimited or line-separated list.","category":"convert","tags":["json","array","list","convert","delimiter"],"keywords":["json array to list","flatten array","join","extract key","csv list"],"icon":"ListOrdered","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/json-array-to-list","webPath":"/tools/json-array-to-list/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
