// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-json-to-go-v1","name":"JSON to Go Struct","slug":"json-to-go","description":"Infer Go structs (with json tags) from a JSON sample.","category":"convert","tags":["json","go","golang","struct","codegen"],"keywords":["json to go","go struct","golang struct","json tags","codegen"],"icon":"FileCode","relatedTools":["json-to-typescript","json-formatter","json-to-xml"],"packageImportPath":"@open-utility-tools/core/tools/convert/json-to-go","webPath":"/tools/json-to-go/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
