// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-length-converter-v1","name":"Length and Distance Converter","slug":"length-converter","description":"Convert between metric and imperial lengths such as mm, cm, m, km, inch, foot, yard, mile, and nautical mile with live multi-unit output.","category":"convert","tags":["length","distance","metric","imperial","convert"],"keywords":["length","distance","metric","imperial","convert","units"],"icon":"Ruler","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/length-converter","webPath":"/tools/length-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
