// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-list-to-json-array-v1","name":"List to JSON Array","slug":"list-to-json-array","description":"Convert a line/comma list into a JSON array.","category":"convert","tags":["json","array","list","convert"],"keywords":["list","json","array","lines","comma","split","dedupe","convert"],"icon":"Brackets","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/list-to-json-array","webPath":"/tools/list-to-json-array/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
