// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-markdown-to-jsx-v1","name":"Markdown to JSX","slug":"markdown-to-jsx","description":"Convert Markdown into a JSX/React component snippet.","category":"convert","tags":["markdown","jsx","react","convert"],"keywords":["markdown","jsx","react","component","className","convert","md"],"icon":"Code2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/markdown-to-jsx","webPath":"/tools/markdown-to-jsx/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
