// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-markdown-list-to-json-v1","name":"Markdown List ↔ JSON Tree","slug":"markdown-list-to-json","description":"Convert an indented Markdown bullet/numbered list into a nested JSON array (and back).","category":"convert","tags":["markdown","json","tree","list","convert"],"keywords":["markdown","list","json","tree","nested","outline","bullet","convert"],"icon":"ListTree","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/markdown-list-to-json","webPath":"/tools/markdown-list-to-json/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
