// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-markdown-table-to-html-v1","name":"Markdown Table to HTML","slug":"markdown-table-to-html","description":"Convert a GitHub-flavored Markdown pipe table into a clean semantic HTML table with alignment.","category":"convert","tags":["markdown","html","table","convert"],"keywords":["markdown","table","html","gfm","pipe","thead","alignment","convert"],"icon":"TableProperties","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/markdown-table-to-html","webPath":"/tools/markdown-table-to-html/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
