// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-mass-weight-converter-v1","name":"Mass & Weight Converter","slug":"mass-weight-converter","description":"Convert between metric and imperial mass units like kilograms, pounds, ounces, and stones.","category":"convert","tags":["mass","weight","units","metric","imperial"],"keywords":["kilogram","pound","lb","ounce","oz","stone","gram","tonne","carat","grain"],"icon":"Scale","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/mass-weight-converter","webPath":"/tools/mass-weight-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
