// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-number-base-words-v1","name":"Number to Spoken Base Words","slug":"number-base-words","description":"Spell out a number in any base (2-36) as place-value words, e.g. binary 1011 as one-zero-one-one or grouped nibbles.","category":"convert","tags":["number","base","words","convert","radix"],"keywords":["base","radix","binary","hex","octal","digits","spoken","words","convert"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/number-base-words","webPath":"/tools/number-base-words/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
