// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-number-to-roman-words-variants-v1","name":"Number Spelling Variants","slug":"number-to-roman-words-variants","description":"Spell a number as English words, ordinals, currency words, and a tally count.","category":"convert","tags":["number","words","ordinal","currency","tally","spell"],"keywords":["number to words","ordinal","currency words","tally marks","british and","spell number","cardinal"],"icon":"Hash","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/number-to-roman-words-variants","webPath":"/tools/number-to-roman-words-variants/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
