// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-number-to-words-v1","name":"Number to Words","slug":"number-to-words","description":"Spell out numbers as English words including negatives, decimals, and large magnitudes, with an optional currency cents mode.","category":"convert","tags":["number","words","spell","currency","convert"],"keywords":["number","words","spell","currency","convert","english"],"icon":"Type","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/number-to-words","webPath":"/tools/number-to-words/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
