// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-properties-to-yaml-v1","name":"Java Properties to YAML","slug":"properties-to-yaml","description":"Convert a Java .properties file into nested YAML by expanding dotted keys into a tree.","category":"convert","tags":["properties","yaml","java","spring","convert","config"],"keywords":["properties to yaml","java properties","spring config","application.properties","application.yml","dotted keys"],"icon":"FileCog","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/properties-to-yaml","webPath":"/tools/properties-to-yaml/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
