// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-properties-to-json-v1","name":"Java .properties to JSON","slug":"properties-to-json","description":"Convert Java/Spring .properties files into nested JSON.","category":"convert","tags":["properties","json","java","spring","convert","config"],"keywords":["properties to json","java properties","spring config","application.properties","dotted keys","nested json"],"icon":"FileText","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/properties-to-json","webPath":"/tools/properties-to-json/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
