// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-pug-to-html-v1","name":"Pug to HTML","slug":"pug-to-html","description":"Convert basic Pug (Jade) templates into HTML.","category":"convert","tags":["pug","jade","html","template","convert"],"keywords":["pug to html","jade to html","template","markup","compile pug"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/pug-to-html","webPath":"/tools/pug-to-html/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
