// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-querystring-to-curl-v1","name":"Query String to cURL","slug":"querystring-to-curl","description":"Build a curl command from a base URL and query string.","category":"convert","tags":["curl","query string","url","http","convert"],"keywords":["querystring to curl","curl builder","data-urlencode","http request","url params"],"icon":"Link","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/querystring-to-curl","webPath":"/tools/querystring-to-curl/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
