// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-query-string-to-json-v1","name":"Query String to JSON","slug":"query-string-to-json","description":"Parse a URL query string into structured JSON, decoding values, grouping repeated keys into arrays, and rebuilding bracketed nesting.","category":"convert","tags":["query","json","url","convert"],"keywords":["query string","json","url","params","parse","convert"],"icon":"Braces","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/query-string-to-json","webPath":"/tools/query-string-to-json/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
