// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-radiation-dose-converter-v1","name":"Radiation Dose Converter","slug":"radiation-dose-converter","description":"Convert radiation dose between sieverts, rems, grays, and rads.","category":"convert","tags":["radiation","dose","units","physics","converter"],"keywords":["sievert","sv","rem","gray","gy","rad","absorbed","equivalent","dosimetry"],"icon":"Radar","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/radiation-dose-converter","webPath":"/tools/radiation-dose-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
