// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-shoe-size-converter-v1","name":"Shoe Size Converter","slug":"shoe-size-converter","description":"Convert shoe sizes across US, UK, EU, and centimeter foot-length systems.","category":"convert","tags":["shoe","size","conversion","footwear","reference"],"keywords":["shoe size","us uk eu","foot length cm","mondopoint","brannock","mens womens"],"icon":"Ruler","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/shoe-size-converter","webPath":"/tools/shoe-size-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
