// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-speed-converter-v1","name":"Speed Converter","slug":"speed-converter","description":"Convert speeds between km/h, mph, m/s, knots, and Mach.","category":"convert","tags":["speed","velocity","units","travel","converter"],"keywords":["kmh","mph","m/s","knot","mach","fps","kilometers per hour","miles per hour"],"icon":"Gauge","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/speed-converter","webPath":"/tools/speed-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
