// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-svg-path-rounder-v1","name":"SVG Path Coordinate Rounder","slug":"svg-path-rounder","description":"Round and tidy the numeric coordinates in an SVG path 'd' string to reduce precision and file size.","category":"convert","tags":["svg","path","optimize","minify","round"],"keywords":["svg path","d attribute","precision","coordinates","file size","bezier","arc"],"icon":"Spline","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/svg-path-rounder","webPath":"/tools/svg-path-rounder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
