// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-toml-to-yaml-v1","name":"TOML to YAML","slug":"toml-to-yaml","description":"Convert TOML configuration into equivalent YAML.","category":"convert","tags":["toml","yaml","config","convert","serialize"],"keywords":["toml to yaml","configuration","tables","inline table","array of tables"],"icon":"FileCog","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/toml-to-yaml","webPath":"/tools/toml-to-yaml/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
