// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-tsv-to-json-v1","name":"TSV to JSON","slug":"tsv-to-json","description":"Paste tab-separated data copied from a spreadsheet and convert it to JSON, with header-row detection and numeric or boolean coercion options.","category":"convert","tags":["tsv","json","spreadsheet","convert"],"keywords":["tsv","json","spreadsheet","tab","convert","excel"],"icon":"FileSpreadsheet","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/tsv-to-json","webPath":"/tools/tsv-to-json/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
