// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-typography-units-converter-v1","name":"Typographic Units Converter","slug":"typography-units-converter","description":"Convert typography units between points, picas, pixels, em, and millimeters.","category":"convert","tags":["typography","units","converter","print","css"],"keywords":["point","pica","pixel","em","rem","cicero","didot","postscript point","font size"],"icon":"Type","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/typography-units-converter","webPath":"/tools/typography-units-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
