// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-viscosity-converter-v1","name":"Viscosity Converter","slug":"viscosity-converter","description":"Convert dynamic and kinematic viscosity between poise, pascal-seconds, and stokes.","category":"convert","tags":["viscosity","units","converter","fluid","physics"],"keywords":["poise","centipoise","pascal second","stokes","centistokes","dynamic viscosity","kinematic viscosity"],"icon":"Droplet","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/viscosity-converter","webPath":"/tools/viscosity-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
