// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-volume-converter-v1","name":"Volume Converter","slug":"volume-converter","description":"Convert liquid and dry volumes between liters, gallons, cups, pints, and more.","category":"convert","tags":["volume","units","converter","cooking","measurement"],"keywords":["liter","gallon","cup","pint","quart","fluid ounce","milliliter","imperial","us customary"],"icon":"FlaskConical","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/volume-converter","webPath":"/tools/volume-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
