// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-xml-attributes-to-elements-v1","name":"XML Attributes ↔ Child Elements","slug":"xml-attributes-to-elements","description":"Rewrite an XML document by promoting attributes into child elements, or demoting simple child elements into attributes.","category":"convert","tags":["xml","attributes","elements","transform","refactor"],"keywords":["xml attributes to elements","promote","demote","dom","restructure","pretty print"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/xml-attributes-to-elements","webPath":"/tools/xml-attributes-to-elements/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
