// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-xml-to-json-v1","name":"XML to JSON","slug":"xml-to-json","description":"Parse XML into a clean JSON tree with options for attribute prefixes, text-node naming, and array coercion for repeated elements.","category":"convert","tags":["xml","json","convert"],"keywords":["xml","json","convert","parse","attributes","dom"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/convert/xml-to-json","webPath":"/tools/xml-to-json/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
