// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"convert-yaml-to-json-v1","name":"YAML to JSON","slug":"yaml-to-json","description":"Convert common YAML configuration into JSON.","category":"convert","tags":["yaml","json","convert","config"],"keywords":["yaml to json","parse yaml","convert","config"],"icon":"ArrowLeftRight","relatedTools":["json-to-yaml","json-formatter","csv-to-json"],"packageImportPath":"@open-utility-tools/core/tools/convert/yaml-to-json","webPath":"/tools/yaml-to-json/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
