// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-add-business-days-v1","name":"Add Business Days","slug":"add-business-days","description":"Add or subtract a number of business days to a date, skipping weekends and custom holidays.","category":"time","tags":["business","days","workdays","date","holidays"],"keywords":["add business days","working days","skip weekends","holidays","date offset","deadline calculator","workday"],"icon":"CalendarDays","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/add-business-days","webPath":"/tools/add-business-days/","coreImportPath":"@open-utility-tools/core/time/add-business-days"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
