// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-age-on-other-planets-v1","name":"Age on Other Planets","slug":"age-on-other-planets","description":"Convert an age or elapsed time on Earth to equivalent years on other planets.","category":"time","tags":["age","planets","space","orbital","fun"],"keywords":["planetary age","age on mars","orbital period","space age","how old on jupiter","planet years","solar system"],"icon":"Orbit","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/age-on-other-planets","webPath":"/tools/age-on-other-planets/","coreImportPath":"@open-utility-tools/core/time/age-on-other-planets"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
