// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-birthday-milestone-finder-v1","name":"Birthday Milestone Finder","slug":"birthday-milestone-finder","description":"Find dates of life milestones: 10,000 days old, 1 billion seconds, next round-number birthday.","category":"time","tags":["birthday","milestone","age","anniversary","date"],"keywords":["milestone dates","10000 days old","billion seconds","life milestones","round birthday","days alive","age milestones"],"icon":"Gift","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/birthday-milestone-finder","webPath":"/tools/birthday-milestone-finder/","coreImportPath":"@open-utility-tools/core/time/birthday-milestone-finder"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
