// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-chinese-zodiac-sign-v1","name":"Chinese Zodiac Animal","slug":"chinese-zodiac-sign","description":"Find the Chinese zodiac animal, element, and yin/yang for any year (approximate by year).","category":"time","tags":["zodiac","chinese","animal","element","astrology"],"keywords":["chinese zodiac","zodiac animal","year of the","five elements","sexagenary cycle","yin yang","birth year sign"],"icon":"Sparkles","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/chinese-zodiac-sign","webPath":"/tools/chinese-zodiac-sign/","coreImportPath":"@open-utility-tools/core/time/chinese-zodiac-sign"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
