// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-cron-field-expander-v1","name":"Cron Field Expander","slug":"cron-field-expander","description":"Expand each field of a cron expression into the explicit set of matching values.","category":"time","tags":["cron","schedule","crontab","fields","expand"],"keywords":["cron expression","crontab","expand cron","cron values","cron fields","fire times"],"icon":"ListChecks","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/cron-field-expander","webPath":"/tools/cron-field-expander/","coreImportPath":"@open-utility-tools/core/time/cron-field-expander"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
