// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-day-of-year-v1","name":"Day of Year Calculator","slug":"day-of-year","description":"Find the ordinal day-of-year for any date, days remaining in the year, and convert an ordinal day back to a date.","category":"time","tags":["day of year","ordinal date","calendar"],"keywords":["day of year","ordinal date","julian day","remaining","calendar"],"icon":"Calendar","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/day-of-year","webPath":"/tools/day-of-year/","coreImportPath":"@open-utility-tools/core/time/day-of-year"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
