// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-day-percentage-elapsed-v1","name":"Day Percentage Elapsed","slug":"day-percentage-elapsed","description":"Show how much of a day, week, month, year, hour, or minute has elapsed for a given moment.","category":"time","tags":["date","progress","percentage","elapsed","year"],"keywords":["percent of year","day elapsed","year progress","time elapsed","week progress","percentage of day"],"icon":"Percent","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/day-percentage-elapsed","webPath":"/tools/day-percentage-elapsed/","coreImportPath":"@open-utility-tools/core/time/day-percentage-elapsed"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
