// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-days-between-units-v1","name":"Days Between in Many Units","slug":"days-between-units","description":"Measure the span between two datetimes simultaneously in years, months, weeks, days, hours, minutes, and seconds.","category":"time","tags":["date","difference","duration","units","between"],"keywords":["days between","time between dates","date difference units","weeks between","hours between","business days"],"icon":"ArrowLeftRight","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/days-between-units","webPath":"/tools/days-between-units/","coreImportPath":"@open-utility-tools/core/time/days-between-units"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
