// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-decimal-time-converter-v1","name":"Decimal (French) Time Converter","slug":"decimal-time-converter","description":"Convert standard clock time to French Revolutionary decimal time (10 hours/day) and back.","category":"time","tags":["decimal time","french","revolutionary","clock","convert"],"keywords":["decimal time","french revolutionary time","metric time","10 hour clock","decimal clock","fraction of day"],"icon":"Clock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/decimal-time-converter","webPath":"/tools/decimal-time-converter/","coreImportPath":"@open-utility-tools/core/time/decimal-time-converter"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
