// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-duration-humanizer-v1","name":"Duration Humanizer","slug":"duration-humanizer","description":"Turn a raw number of seconds or milliseconds into a human phrase like '2 days, 3 hours, 5 minutes'.","category":"time","tags":["duration","humanize","seconds","format","time"],"keywords":["humanize duration","seconds to human","milliseconds to time","format duration","pretty time","time ago"],"icon":"Hourglass","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/duration-humanizer","webPath":"/tools/duration-humanizer/","coreImportPath":"@open-utility-tools/core/time/duration-humanizer"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
