// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-duration-parser-v1","name":"Duration String Parser","slug":"duration-parser","description":"Parse human duration text like '1h30m', '2 days 4 hours', or '90s' into total seconds and milliseconds.","category":"time","tags":["duration","parser","time","seconds","milliseconds"],"keywords":["parse duration","human duration","1h30m","time string","to seconds","to ms"],"icon":"Timer","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/duration-parser","webPath":"/tools/duration-parser/","coreImportPath":"@open-utility-tools/core/time/duration-parser"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
