// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-iso-8601-parser-v1","name":"ISO 8601 Parser","slug":"iso-8601-parser","description":"Break down an ISO 8601 date-time string into its components (year, month, day, hour, offset, week) and validate it.","category":"time","tags":["iso 8601","parse","datetime","validate"],"keywords":["iso 8601","parse","datetime","offset","validate"],"icon":"CalendarClock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/iso-8601-parser","webPath":"/tools/iso-8601-parser/","coreImportPath":"@open-utility-tools/core/time/iso-8601-parser"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
