// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-iso-week-date-converter-v1","name":"ISO Week Date Converter","slug":"iso-week-date-converter","description":"Convert between a calendar date and its ISO-8601 week-date form (YYYY-Www-D).","category":"time","tags":["iso 8601","week date","calendar","week number","conversion"],"keywords":["iso week date","yyyy-www-d","week year","53 week year","week number converter"],"icon":"CalendarDays","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/iso-week-date-converter","webPath":"/tools/iso-week-date-converter/","coreImportPath":"@open-utility-tools/core/time/iso-week-date-converter"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
