// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-nth-weekday-of-month-v1","name":"Nth Weekday of Month","slug":"nth-weekday-of-month","description":"Find dates like 'the 3rd Thursday of November' or 'the last Monday of May'.","category":"time","tags":["weekday","recurring","calendar","holidays","schedule"],"keywords":["nth weekday","last monday","third thursday","recurring meeting","thanksgiving","holiday rule"],"icon":"Calendar","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/nth-weekday-of-month","webPath":"/tools/nth-weekday-of-month/","coreImportPath":"@open-utility-tools/core/time/nth-weekday-of-month"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
