// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-ordinal-date-converter-v1","name":"Ordinal Date Converter","slug":"ordinal-date-converter","description":"Convert between calendar dates and ordinal dates (year + day-of-year, YYYY-DDD).","category":"time","tags":["ordinal date","day of year","iso 8601","calendar","convert"],"keywords":["ordinal date","yyyy-ddd","day of year","julian day","iso ordinal","date to ordinal"],"icon":"ListOrdered","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/ordinal-date-converter","webPath":"/tools/ordinal-date-converter/","coreImportPath":"@open-utility-tools/core/time/ordinal-date-converter"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
