// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-quarter-of-date-v1","name":"Quarter & Fiscal Period Finder","slug":"quarter-of-date","description":"Determine the calendar or fiscal quarter, half, and period dates for any date.","category":"time","tags":["quarter","fiscal year","calendar","finance","period"],"keywords":["quarter","fiscal year","q1 q2 q3 q4","half year","fiscal quarter","period dates"],"icon":"ChartPie","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/quarter-of-date","webPath":"/tools/quarter-of-date/","coreImportPath":"@open-utility-tools/core/time/quarter-of-date"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
