// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-relative-time-formatter-v1","name":"Relative Time Formatter","slug":"relative-time-formatter","description":"Turn a timestamp or date into human-friendly relative phrasing like '3 hours ago' or 'in 2 days' across locales.","category":"time","tags":["relative time","ago","intl"],"keywords":["relative time","ago","time since","intl","human readable"],"icon":"Clock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/relative-time-formatter","webPath":"/tools/relative-time-formatter/","coreImportPath":"@open-utility-tools/core/time/relative-time-formatter"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
