// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-stardate-converter-v1","name":"Star Trek Stardate Converter","slug":"stardate-converter","description":"Convert Gregorian dates to TNG-era stardates and back using the common fan formula.","category":"time","tags":["stardate","star trek","novelty","convert","sci-fi"],"keywords":["stardate","star trek","tng","gregorian to stardate","sci-fi date","next generation"],"icon":"Rocket","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/stardate-converter","webPath":"/tools/stardate-converter/","coreImportPath":"@open-utility-tools/core/time/stardate-converter"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
