// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-time-meeting-cost-calculator-v1","name":"Meeting Cost Calculator","slug":"time-meeting-cost-calculator","description":"Estimates the dollar cost of a meeting from attendee count, hourly rates, and duration.","category":"time","tags":["meeting","cost","salary","productivity","calculator"],"keywords":["meeting cost","meeting price","salary per hour","cost of meeting","attendee cost","time is money"],"icon":"HandCoins","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/time-meeting-cost-calculator","webPath":"/tools/time-meeting-cost-calculator/","coreImportPath":"@open-utility-tools/core/time/time-meeting-cost-calculator"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
