// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-time-12-24-converter-v1","name":"12 / 24 Hour Time Converter","slug":"time-12-24-converter","description":"Convert clock times between 12-hour AM/PM and 24-hour formats, single or in bulk.","category":"time","tags":["12 hour","24 hour","am pm","clock","convert"],"keywords":["12 hour to 24 hour","am pm","military time","clock format","time converter","bulk time"],"icon":"Clock3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/time-12-24-converter","webPath":"/tools/time-12-24-converter/","coreImportPath":"@open-utility-tools/core/time/time-12-24-converter"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
