// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-time-timecode-frames-converter-v1","name":"SMPTE Timecode / Frames Converter","slug":"time-timecode-frames-converter","description":"Converts between SMPTE timecode (HH:MM:SS:FF) and total frame counts at a chosen frame rate.","category":"time","tags":["smpte","timecode","frames","video","drop-frame"],"keywords":["timecode to frames","frames to timecode","drop frame","fps converter","ndf df","29.97"],"icon":"Clock3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/time-timecode-frames-converter","webPath":"/tools/time-timecode-frames-converter/","coreImportPath":"@open-utility-tools/core/time/time-timecode-frames-converter"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
