// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-time-of-day-bucketer-v1","name":"Time-of-Day Classifier","slug":"time-of-day-bucketer","description":"Classify a time into parts of day (morning, afternoon, evening, night) and solar/clock segments.","category":"time","tags":["time of day","morning","evening","greeting","classify"],"keywords":["part of day","morning afternoon evening night","good morning","time bucket","time segment","clock period"],"icon":"Sun","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/time-of-day-bucketer","webPath":"/tools/time-of-day-bucketer/","coreImportPath":"@open-utility-tools/core/time/time-of-day-bucketer"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
