// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-time-unit-converter-v1","name":"Time Unit Converter","slug":"time-unit-converter","description":"Convert a value between nanoseconds, microseconds, milliseconds, seconds, minutes, hours, and days.","category":"time","tags":["time","convert","units"],"keywords":["time units","milliseconds","nanoseconds","convert","seconds"],"icon":"ArrowLeftRight","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/time-unit-converter","webPath":"/tools/time-unit-converter/","coreImportPath":"@open-utility-tools/core/time/time-unit-converter"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
