// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-time-server-format-reference-v1","name":"Datetime Format Examples Reference","slug":"time-server-format-reference","description":"Cheatsheet of the same instant rendered in RFC 3339, RFC 2822, ISO 8601, HTTP-date, SQL, and more.","category":"time","tags":["datetime","formats","rfc 3339","iso 8601","reference"],"keywords":["RFC 3339","RFC 2822","ISO 8601","HTTP-date","SQL datetime","unix",".NET ticks","cookie expires"],"icon":"FileText","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/time-server-format-reference","webPath":"/tools/time-server-format-reference/","coreImportPath":"@open-utility-tools/core/time/time-server-format-reference"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
