// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-time-time-duration-arithmetic-v1","name":"Time Duration Arithmetic","slug":"time-time-duration-arithmetic","description":"Adds and subtracts a list of HH:MM:SS durations and shows the running and total result.","category":"time","tags":["duration","add","subtract","time","calculator"],"keywords":["add times","sum durations","subtract time","hms math","time adder","total duration"],"icon":"Hourglass","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/time-time-duration-arithmetic","webPath":"/tools/time-time-duration-arithmetic/","coreImportPath":"@open-utility-tools/core/time/time-time-duration-arithmetic"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
