// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-timezone-v1","name":"Timezone Converter","slug":"timezone-converter","description":"Convert a date/time across timezones using the browser’s IANA database.","category":"time","tags":["timezone","time","convert","utc","iana"],"keywords":["timezone converter","utc","time zones","world clock","convert time"],"icon":"Clock","relatedTools":["timestamp-converter","date-difference","cron-parser"],"packageImportPath":"@open-utility-tools/core/tools/time/timezone-converter","webPath":"/tools/timezone-converter/","coreImportPath":"@open-utility-tools/core/time/timezone-converter"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
