// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-unix-nanoseconds-converter-v1","name":"Unix Nanoseconds Converter","slug":"unix-nanoseconds-converter","description":"Convert nanosecond-precision Unix timestamps to date-time and back without floating-point loss.","category":"time","tags":["unix","nanoseconds","timestamp","bigint","epoch"],"keywords":["nanosecond timestamp","unix nanos","epoch ns","high precision time","ns to date","date to nanoseconds"],"icon":"Timer","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/unix-nanoseconds-converter","webPath":"/tools/unix-nanoseconds-converter/","coreImportPath":"@open-utility-tools/core/time/unix-nanoseconds-converter"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
