// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-unix-time-now-v1","name":"Unix Timestamp Now","slug":"unix-time-now","description":"Live ticking display of the current Unix timestamp in seconds, milliseconds, and microseconds, with a one-click copy and pause toggle.","category":"time","tags":["unix","epoch","timestamp","now"],"keywords":["unix","epoch","current timestamp","now","milliseconds"],"icon":"Clock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/unix-time-now","webPath":"/tools/unix-time-now/","coreImportPath":"@open-utility-tools/core/time/unix-time-now"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
