// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-week-of-month-finder-v1","name":"Week of Month Finder","slug":"week-of-month-finder","description":"Determine which week of the month a date falls in, using several common counting conventions.","category":"time","tags":["week of month","calendar","date","convention","finder"],"keywords":["week of month","which week","nth week","calendar week row","first full week","monthly week number"],"icon":"CalendarDays","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/week-of-month-finder","webPath":"/tools/week-of-month-finder/","coreImportPath":"@open-utility-tools/core/time/week-of-month-finder"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
