// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-week-to-date-v1","name":"Week Number to Date","slug":"week-to-date","description":"Convert an ISO week number and year into the start and end dates of that week, and vice versa.","category":"time","tags":["iso week","week number","calendar"],"keywords":["iso week","week number","week date","convert","calendar"],"icon":"Calendar","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/week-to-date","webPath":"/tools/week-to-date/","coreImportPath":"@open-utility-tools/core/time/week-to-date"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
