// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-week-number-v1","name":"ISO Week Number","slug":"week-number","description":"Find the ISO 8601 week number for any date (and day-of-year).","category":"time","tags":["week number","iso 8601","date","calendar"],"keywords":["week number","iso week","day of year","calendar week","what week"],"icon":"Calendar","relatedTools":["date-difference","age-calculator","timestamp-converter"],"packageImportPath":"@open-utility-tools/core/tools/time/week-number","webPath":"/tools/week-number/","coreImportPath":"@open-utility-tools/core/time/week-number"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
