// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"time-working-hours-calculator-v1","name":"Working Hours Calculator","slug":"working-hours-calculator","description":"Compute net working hours between two datetimes, excluding nights, weekends, and lunch.","category":"time","tags":["working hours","business hours","timesheet","payroll","duration"],"keywords":["work hours","billable hours","business hours","lunch break","weekday hours","timesheet"],"icon":"Briefcase","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/time/working-hours-calculator","webPath":"/tools/working-hours-calculator/","coreImportPath":"@open-utility-tools/core/time/working-hours-calculator"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
