// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-pixel-ruler-v1","name":"Pixel Ruler & Color Probe","slug":"image-pixel-ruler","description":"Measure pixel distances and read pixel colors by clicking on a loaded image.","category":"image","tags":["ruler","measure","pixel","color","distance","inspect"],"keywords":["pixel ruler","measure distance","color picker","eyedropper","pixel color","image measurement","angle"],"icon":"Ruler","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-pixel-ruler","webPath":"/tools/image-pixel-ruler/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
