// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-watermark-text-v1","name":"Text Watermark","slug":"image-watermark-text","description":"Overlay a repeating or single text watermark with opacity, angle, and tiling.","category":"image","tags":["watermark","text","overlay","tiled","protect"],"keywords":["text watermark","tiled watermark","image overlay","copyright stamp","diagonal watermark","protect images"],"icon":"Stamp","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-watermark-text","webPath":"/tools/image-watermark-text/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
