// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-filter-adjust-v1","name":"Brightness / Contrast / Saturation Adjuster","slug":"image-filter-adjust","description":"Tweak brightness, contrast, saturation, and hue of an image with live sliders.","category":"image","tags":["brightness","contrast","saturation","hue","filter"],"keywords":["brightness","contrast","saturation","hue rotate","image adjust","photo filter","color correction"],"icon":"SlidersHorizontal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-filter-adjust","webPath":"/tools/image-filter-adjust/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
