// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-gradient-svg-generator-v1","name":"Gradient SVG / PNG Generator","slug":"image-gradient-svg-generator","description":"Create linear/radial multi-stop gradients and export as SVG, PNG, or CSS.","category":"image","tags":["gradient","svg","png","css","linear"],"keywords":["gradient generator","linear gradient svg","radial gradient","multi stop gradient","gradient png export","css gradient","design asset"],"icon":"Blend","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-gradient-svg-generator","webPath":"/tools/image-gradient-svg-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
