// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-converter-v1","name":"Image Converter","slug":"image-converter","description":"Convert images between PNG, JPEG, WebP, GIF, BMP, TIFF and ICO — resize, set quality, batch & zip. All in your browser.","category":"image","tags":["convert","png","jpeg","webp","gif","bmp","tiff","ico","resize"],"keywords":["image converter","png to jpg","webp","resize image","ico","favicon","batch"],"icon":"ImageDown","relatedTools":["image-to-base64","hash-text","base64-text"],"packageImportPath":"@open-utility-tools/core/tools/image/image-converter","webPath":"/tools/image-converter/","loadWasm":true,"coreImportPath":"@open-utility-tools/core/image/convert"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
