// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-pixelate-v1","name":"Pixelate / Mosaic","slug":"image-pixelate","description":"Pixelate an image (or simulate censoring) with an adjustable block size.","category":"image","tags":["pixelate","mosaic","censor","blur","block","privacy"],"keywords":["pixelate image","mosaic","censor","blur face","block size","redact","nearest neighbor"],"icon":"Grid3x3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-pixelate","webPath":"/tools/image-pixelate/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
