// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-checkerboard-svg-v1","name":"Checkerboard & Pattern Generator","slug":"image-checkerboard-svg","description":"Generate checkerboard, stripes, dots, or grid SVG/PNG patterns with custom colors.","category":"image","tags":["checkerboard","pattern","svg","png","tile"],"keywords":["checkerboard generator","stripes pattern","polka dots","grid lines svg","tileable background","css background pattern","transparent placeholder"],"icon":"Grid2x2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-checkerboard-svg","webPath":"/tools/image-checkerboard-svg/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
