// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-contact-sheet-builder-v1","name":"Image Contact Sheet Builder","slug":"image-contact-sheet-builder","description":"Arranges multiple uploaded images into a single grid contact sheet PNG.","category":"image","tags":["contact sheet","grid","montage","collage","thumbnails"],"keywords":["contact sheet","photo grid","image montage","thumbnail sheet","collage maker"],"icon":"Images","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-contact-sheet-builder","webPath":"/tools/image-contact-sheet-builder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
