// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-favicon-generator-v1","name":"Favicon Set Generator","slug":"image-favicon-generator","description":"Generate favicon PNGs at standard sizes (16-512px) from one image plus the HTML link tags.","category":"image","tags":["favicon","icon","png","apple-touch","manifest"],"keywords":["favicon","favicon generator","apple touch icon","site icon","webmanifest","link rel icon","app icon"],"icon":"FileImage","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-favicon-generator","webPath":"/tools/image-favicon-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
