// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-rgb-channel-split-v1","name":"RGB Channel Splitter","slug":"image-rgb-channel-split","description":"Split an image into separate red, green, blue, and alpha channel images.","category":"image","tags":["channels","rgb","split","alpha","grayscale","compositing"],"keywords":["rgb channel split","color channels","red green blue","alpha mask","channel separation","isolate channel"],"icon":"Layers","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-rgb-channel-split","webPath":"/tools/image-rgb-channel-split/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
