// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-exif-viewer-v1","name":"EXIF Metadata Viewer","slug":"image-exif-viewer","description":"View EXIF/JFIF metadata embedded in a JPEG (camera, exposure, GPS) without uploading.","category":"image","tags":["exif","metadata","jpeg","camera","gps"],"keywords":["exif viewer","image metadata","jpeg exif","camera info","gps coordinates","exposure"],"icon":"FileSearch","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-exif-viewer","webPath":"/tools/image-exif-viewer/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
