// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-color-overlay-v1","name":"Color Overlay / Tint","slug":"image-color-overlay","description":"Apply a color tint or duotone over an image using canvas blend modes.","category":"image","tags":["color","overlay","tint","blend","filter"],"keywords":["color tint","blend mode","multiply","screen","overlay","photo tint"],"icon":"Blend","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-color-overlay","webPath":"/tools/image-color-overlay/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
