// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-resize-pixels-v1","name":"Image Resizer (Pixels & Percent)","slug":"image-resize-pixels","description":"Resize an image to exact pixel dimensions or by percentage, with optional aspect-lock.","category":"image","tags":["resize","scale","dimensions","pixels","percent","aspect"],"keywords":["resize image","scale image","image dimensions","aspect ratio lock","resize percent","png jpeg export"],"icon":"Scaling","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-resize-pixels","webPath":"/tools/image-resize-pixels/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
