// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-resize-to-filesize-v1","name":"Resize to Target File Size","slug":"image-resize-to-filesize","description":"Iteratively re-encode an image to land under a target KB limit (e.g. for upload limits).","category":"image","tags":["compress","filesize","target","upload","jpeg","webp"],"keywords":["resize to file size","compress to kb","target file size","upload limit","jpeg quality","webp compress","shrink image"],"icon":"Gauge","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-resize-to-filesize","webPath":"/tools/image-resize-to-filesize/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
