// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-crop-aspect-v1","name":"Crop to Aspect Ratio","slug":"image-crop-aspect","description":"Crop an image to a chosen aspect ratio (1:1, 4:3, 16:9, custom) with center/anchor control.","category":"image","tags":["crop","aspect ratio","resize","thumbnail","square"],"keywords":["crop image","aspect ratio","square crop","16:9","thumbnail crop","anchor"],"icon":"Crop","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-crop-aspect","webPath":"/tools/image-crop-aspect/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
