// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-invert-colors-v1","name":"Invert Colors (Negative)","slug":"image-invert-colors","description":"Create a photographic negative by inverting every pixel's RGB values.","category":"image","tags":["invert","negative","colors","filter","pixels"],"keywords":["invert colors","negative image","photo negative","invert luminance","film negative","color invert"],"icon":"Contrast","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-invert-colors","webPath":"/tools/image-invert-colors/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
