// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-sprite-splitter-v1","name":"Sprite Sheet Splitter","slug":"image-sprite-splitter","description":"Slice a sprite sheet into a grid of individual images by rows/cols or cell size.","category":"image","tags":["sprite","spritesheet","slice","split","grid"],"keywords":["sprite sheet","slice sprites","split image","tileset","extract frames","cell grid"],"icon":"Grid2x2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-sprite-splitter","webPath":"/tools/image-sprite-splitter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
