// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-noise-texture-svg-v1","name":"Noise & Grain SVG Generator","slug":"image-noise-texture-svg","description":"Generate a tileable fractal-noise/grain texture as an inline SVG or PNG.","category":"image","tags":["noise","grain","svg","texture","turbulence"],"keywords":["noise texture","film grain","feTurbulence","fractal noise svg","grain overlay","css background noise","tileable texture"],"icon":"Sparkles","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-noise-texture-svg","webPath":"/tools/image-noise-texture-svg/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
