// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-compress-quality-v1","name":"JPEG/WebP Compressor","slug":"image-compress-quality","description":"Reduce image file size with a quality slider and live before/after byte comparison.","category":"image","tags":["compress","jpeg","webp","optimize","quality"],"keywords":["image compression","reduce file size","jpeg quality","webp encode","optimize photo"],"icon":"ImageDown","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-compress-quality","webPath":"/tools/image-compress-quality/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
