// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-mirror-collage-v1","name":"Mirror & Reflection Collage","slug":"image-mirror-collage","description":"Create symmetric mirror collages (2-up, 4-up kaleidoscope) from one image.","category":"image","tags":["mirror","reflection","collage","kaleidoscope","symmetry"],"keywords":["mirror","reflection","kaleidoscope","symmetry","collage","flip image"],"icon":"FlipHorizontal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-mirror-collage","webPath":"/tools/image-mirror-collage/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
