// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-canvas-grid-overlay-v1","name":"Image Grid & Guide Overlay","slug":"image-canvas-grid-overlay","description":"Overlays a rule-of-thirds, pixel grid, or custom guides onto an uploaded image.","category":"image","tags":["grid","overlay","guides","composition","thirds"],"keywords":["rule of thirds","golden ratio","grid overlay","pixel grid","composition guides","crop guides"],"icon":"Grid3x3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-canvas-grid-overlay","webPath":"/tools/image-canvas-grid-overlay/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
