// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"image-image-round-corners-v1","name":"Round Corners & Circle Crop","slug":"image-round-corners","description":"Round an image's corners by radius or crop it to a perfect circle/ellipse.","category":"image","tags":["round","corners","circle","crop","avatar","mask"],"keywords":["round corners","rounded image","circle crop","avatar maker","ellipse crop","border radius","transparent png"],"icon":"Crop","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/image/image-round-corners","webPath":"/tools/image-round-corners/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
