// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-ascii85-v1","name":"Ascii85 / Base85 Encode","slug":"ascii85","description":"Encode and decode text using Ascii85 (Adobe variant).","category":"encoding","tags":["ascii85","base85","encode","decode","adobe"],"keywords":["ascii85","base85","btoa","encode","decode"],"icon":"Binary","relatedTools":["base64-text","base58","hex-text"],"packageImportPath":"@open-utility-tools/core/tools/encoding/ascii85","webPath":"/tools/ascii85/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
