// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-base58-v1","name":"Base58 Encode / Decode","slug":"base58","description":"Encode bytes/text to Base58 (Bitcoin alphabet) and decode it back.","category":"encoding","tags":["base58","bitcoin","encode","decode"],"keywords":["base58","bitcoin","btc","encode","decode","base58check"],"icon":"Binary","relatedTools":["base64-text","base32-text","hex-text"],"packageImportPath":"@open-utility-tools/core/tools/encoding/base58","webPath":"/tools/base58/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
