// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-base64-text-v1","name":"Base64 Encode / Decode","slug":"base64-text","description":"Encode text to Base64 (standard or URL-safe) and decode it back — live.","category":"encoding","tags":["base64","b64","url-safe","encode","decode"],"keywords":["base64","b64","atob","btoa","url safe","encode","decode"],"icon":"Binary","relatedTools":["hex-text","url-encode","base32-text","hash-text"],"packageImportPath":"@open-utility-tools/core/tools/encoding/base64-text","webPath":"/tools/base64-text/","loadWasm":true} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
