// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-binary-text-v1","name":"Text to Binary","slug":"binary-text","description":"Convert text to its binary (and back), with a configurable separator.","category":"encoding","tags":["binary","text","bits","convert","encode"],"keywords":["text to binary","binary to text","bits","ascii binary","utf-8 binary"],"icon":"Binary","relatedTools":["hex-text","base64-text","number-base-converter"],"packageImportPath":"@open-utility-tools/core/tools/encoding/binary-text","webPath":"/tools/binary-text/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
