// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-beaufort-cipher-v1","name":"Beaufort Cipher","slug":"encoding-beaufort-cipher","description":"Encrypt and decrypt with the reciprocal Beaufort polyalphabetic cipher.","category":"encoding","tags":["beaufort","cipher","polyalphabetic","classical","encryption"],"keywords":["beaufort","vigenere variant","reciprocal cipher","german beaufort","keyword cipher"],"icon":"Key","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-beaufort-cipher","webPath":"/tools/encoding-beaufort-cipher/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
