// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-uri-template-expander-v1","name":"URI Template Expander (RFC 6570)","slug":"encoding-uri-template-expander","description":"Expand RFC 6570 URI templates with variables, applying correct percent-encoding per operator.","category":"encoding","tags":["uri","template","rfc6570","url","expand"],"keywords":["uri template","rfc 6570","rfc6570","url template","expansion","percent encoding","query","path"],"icon":"Link","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-uri-template-expander","webPath":"/tools/encoding-uri-template-expander/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
