// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-unicode-normalization-v1","name":"Unicode Normalization (NFC/NFD/NFKC/NFKD)","slug":"encoding-unicode-normalization","description":"Apply and compare the four Unicode normalization forms to text.","category":"encoding","tags":["unicode","normalization","nfc","nfd","text"],"keywords":["normalize","nfc","nfd","nfkc","nfkd","composition","decomposition","diacritics","ligature"],"icon":"Languages","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-unicode-normalization","webPath":"/tools/encoding-unicode-normalization/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
