// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-xor-cipher-v1","name":"XOR Cipher","slug":"encoding-xor-cipher","description":"Encrypt or decrypt text with a repeating-key XOR cipher, outputting or reading hex or Base64.","category":"encoding","tags":["xor","cipher","key","encrypt","decrypt","encode"],"keywords":["xor","cipher","key","encrypt","decrypt","encode"],"icon":"Lock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-xor-cipher","webPath":"/tools/encoding-xor-cipher/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
