// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-json-pointer-escape-v1","name":"JSON Pointer Escaper (RFC 6901)","slug":"encoding-json-pointer-escape","description":"Encode and decode JSON Pointer reference tokens with the ~0/~1 escape rules.","category":"encoding","tags":["json-pointer","rfc6901","escape","json","reference-token"],"keywords":["json pointer","rfc 6901","reference token","tilde escape","uri fragment","json path","encode","decode"],"icon":"Braces","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-json-pointer-escape","webPath":"/tools/encoding-json-pointer-escape/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
