// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-sql-string-escape-v1","name":"SQL String Escaper","slug":"encoding-sql-string-escape","description":"Escape text into a safe SQL string literal for common database dialects.","category":"encoding","tags":["sql","escape","literal","database","developer"],"keywords":["sql","escape","string","literal","quote","mysql","postgres","sqlite","sql server","injection"],"icon":"Database","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-sql-string-escape","webPath":"/tools/encoding-sql-string-escape/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
