// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-polybius-square-v1","name":"Polybius Square Cipher","slug":"encoding-polybius-square","description":"Encode/decode text using a 5x5 Polybius square coordinate cipher.","category":"encoding","tags":["cipher","polybius","classical","adfgx","transposition"],"keywords":["polybius","square","cipher","coordinates","adfgx","fractionation","keyword"],"icon":"Grid2x2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-polybius-square","webPath":"/tools/encoding-polybius-square/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
