// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-morse-prosigns-reference-v1","name":"Morse Code Prosigns & Abbreviations","slug":"encoding-morse-prosigns-reference","description":"Reference of Morse prosigns, Q-codes, and common abbreviations beyond plain letters.","category":"encoding","tags":["morse","prosigns","q-codes","ham radio","reference"],"keywords":["morse code","prosigns","q codes","cw abbreviations","ham radio","cheatsheet"],"icon":"Radio","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-morse-prosigns-reference","webPath":"/tools/encoding-morse-prosigns-reference/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
