// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-base32hex-encode-v1","name":"Base32hex (Extended Hex) Encode / Decode","slug":"encoding-base32hex-encode","description":"Encode/decode using the RFC 4648 Base32hex extended-hex alphabet (0-9A-V).","category":"encoding","tags":["base32hex","rfc4648","dnssec","encode","decode"],"keywords":["base32hex","extended hex","rfc 4648","nsec3","dnssec","sort order","encode"],"icon":"Hash","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-base32hex-encode","webPath":"/tools/encoding-base32hex-encode/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
