// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-rail-fence-cipher-v1","name":"Rail Fence Cipher","slug":"encoding-rail-fence-cipher","description":"Encrypt and decrypt text with the zigzag rail fence transposition cipher.","category":"encoding","tags":["cipher","transposition","zigzag","classical","rail-fence"],"keywords":["rail","fence","zigzag","transposition","cipher","rails","classical"],"icon":"Waves","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-rail-fence-cipher","webPath":"/tools/encoding-rail-fence-cipher/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
