// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-atbash-cipher-v1","name":"Atbash Cipher","slug":"encoding-atbash-cipher","description":"Encode or decode text with the Atbash cipher, mirroring each letter to its opposite in the alphabet.","category":"encoding","tags":["atbash","cipher","mirror","substitution","encode","decode"],"keywords":["atbash","cipher","mirror","encode","decode","substitution"],"icon":"FlipHorizontal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-atbash-cipher","webPath":"/tools/encoding-atbash-cipher/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
