// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-percent-encoding-table-v1","name":"Percent-Encoding Reference Table","slug":"encoding-percent-encoding-table","description":"Searchable table of percent-encoded (%XX) values for ASCII and common reserved characters.","category":"encoding","tags":["percent-encoding","url-encoding","ascii","rfc3986","reference"],"keywords":["percent encoding","url encode","ascii table","rfc 3986","reserved characters","%xx"],"icon":"Percent","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-percent-encoding-table","webPath":"/tools/encoding-percent-encoding-table/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
