// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-columnar-transposition-v1","name":"Columnar Transposition Cipher","slug":"encoding-columnar-transposition","description":"Encrypt/decrypt with a keyword-based columnar transposition cipher.","category":"encoding","tags":["transposition","cipher","columnar","classical","keyword"],"keywords":["columnar transposition","transposition cipher","keyword cipher","classical crypto","grid cipher"],"icon":"Columns3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-columnar-transposition","webPath":"/tools/encoding-columnar-transposition/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
