// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-base85-rfc1924-v1","name":"Base85 (RFC 1924 / ZeroMQ) Variants","slug":"encoding-base85-rfc1924","description":"Encodes and decodes data across Base85 alphabets: ASCII85, RFC 1924, and Z85 side by side.","category":"encoding","tags":["base85","ascii85","z85","rfc1924","encode"],"keywords":["base85","ascii85","z85","rfc 1924","zeromq","adobe","encode","decode"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-base85-rfc1924","webPath":"/tools/encoding-base85-rfc1924/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
