// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-base64-to-hex-v1","name":"Base64 to Hex Converter","slug":"encoding-base64-to-hex","description":"Convert between Base64-encoded data and its hexadecimal byte representation in both directions.","category":"encoding","tags":["base64","hex","convert"],"keywords":["base64","hex","hexadecimal","convert","bytes"],"icon":"ArrowLeftRight","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-base64-to-hex","webPath":"/tools/encoding-base64-to-hex/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
