// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-regex-literal-escape-v1","name":"Regex Special-Character Escaper","slug":"encoding-regex-literal-escape","description":"Escape text so it matches literally inside a regular expression, for several flavors.","category":"encoding","tags":["regex","escape","pattern","literal","developer"],"keywords":["regex","escape","metacharacter","literal","quotemeta","re.escape","pcre","character class"],"icon":"Regex","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-regex-literal-escape","webPath":"/tools/encoding-regex-literal-escape/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
