// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-playfair-cipher-v1","name":"Playfair Cipher","slug":"encoding-playfair-cipher","description":"Encrypt and decrypt with the classic 5x5 Playfair digraph substitution cipher.","category":"encoding","tags":["playfair","cipher","digraph","classical","key-square"],"keywords":["playfair cipher","digraph","bigram","key square","keyword","i/j merge","encrypt","decrypt"],"icon":"Grid3x3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-playfair-cipher","webPath":"/tools/encoding-playfair-cipher/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
