// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-url-component-variants-v1","name":"URL Encode Variants (encodeURI vs encodeURIComponent)","slug":"encoding-url-component-variants","description":"Compare and apply the three JavaScript URL-encoding functions side by side on the same input.","category":"encoding","tags":["url","encode","percent","escape","compare"],"keywords":["encodeuri","encodeuricomponent","escape","unescape","percent encoding","url encode","decodeuri"],"icon":"Link2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-url-component-variants","webPath":"/tools/encoding-url-component-variants/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
