// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-punycode-v1","name":"Punycode Encode / Decode","slug":"encoding-punycode","description":"Convert internationalized domain names to ASCII Punycode (xn--) and back to their Unicode form.","category":"encoding","tags":["punycode","idn","domain"],"keywords":["punycode","idn","domain","xn--","unicode","encode"],"icon":"Globe","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-punycode","webPath":"/tools/encoding-punycode/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
