// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-caesar-cipher-v1","name":"Caesar Cipher Shift","slug":"encoding-caesar-cipher","description":"Encode or decode text with a configurable Caesar shift, rotating letters by any amount while preserving case and symbols.","category":"encoding","tags":["caesar","cipher","shift"],"keywords":["caesar","cipher","shift","rotate","encode","decode"],"icon":"RotateCw","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-caesar-cipher","webPath":"/tools/encoding-caesar-cipher/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
