// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-decimal-binary-octal-hex-v1","name":"Char Multi-Radix Encoder (Dec/Bin/Oct/Hex)","slug":"encoding-decimal-binary-octal-hex","description":"Show every character's value simultaneously in decimal, binary, octal, and hex.","category":"encoding","tags":["radix","binary","octal","hex","decimal"],"keywords":["radix","base conversion","char codes","binary octal hex decimal","ascii values","multi base"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-decimal-binary-octal-hex","webPath":"/tools/encoding-decimal-binary-octal-hex/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
