// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-base45-v1","name":"Base45 Encode / Decode","slug":"encoding-base45","description":"Encode text to RFC 9285 Base45 or decode Base45 back to text, as used in QR-code data payloads.","category":"encoding","tags":["base45","rfc 9285","qr code","encode","decode"],"keywords":["base45","rfc 9285","qr code","encode","decode"],"icon":"QrCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-base45","webPath":"/tools/encoding-base45/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
