// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-base91-encode-v1","name":"basE91 Encode / Decode","slug":"encoding-base91-encode","description":"Encode binary text to basE91, a denser ASCII encoding than Base64.","category":"encoding","tags":["base91","encode","decode","ascii","binary"],"keywords":["base91","base 91","basE91","henke","binary to text","compact encoding"],"icon":"Boxes","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-base91-encode","webPath":"/tools/encoding-base91-encode/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
