// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-encoding-tap-code-v1","name":"Tap Code (Knock Cipher)","slug":"encoding-tap-code","description":"Encode/decode text to the tap code used as a 5x5 grid of knocks.","category":"encoding","tags":["cipher","tap-code","knock","polybius","classical"],"keywords":["tap","code","knock","cipher","prisoner","polybius","grid","taps"],"icon":"Grid2x2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/encoding-tap-code","webPath":"/tools/encoding-tap-code/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
