// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-hex-text-v1","name":"Hex Encode / Decode","slug":"hex-text","description":"Convert text to hexadecimal and back, with optional uppercase.","category":"encoding","tags":["hex","hexadecimal","base16","encode","decode"],"keywords":["hex","hexadecimal","base16","bytes","encode","decode"],"icon":"Binary","relatedTools":["base64-text","base32-text","hash-text"],"packageImportPath":"@open-utility-tools/core/tools/encoding/hex-text","webPath":"/tools/hex-text/","loadWasm":true} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
