// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-html-entities-v1","name":"HTML Entity Encode / Decode","slug":"html-entities","description":"Escape text to HTML entities and unescape entities back to text.","category":"encoding","tags":["html","entities","escape","unescape"],"keywords":["html entities","escape","unescape","ampersand","nbsp"],"icon":"Code","relatedTools":["url-encode","base64-text","json-formatter"],"packageImportPath":"@open-utility-tools/core/tools/encoding/html-entities","webPath":"/tools/html-entities/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
