// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-magic-decoder-v1","name":"Magic Decoder (Auto-Detect Encoding)","slug":"magic-decoder","description":"Paste an unknown blob and automatically find the chain of decodings (Base64, hex, gzip, URL, ROT13, UTF-16 and more) that turns it into readable text or a recognisable file.","category":"encoding","tags":["magic","decode","auto-detect","base64","cyberchef"],"keywords":["cyberchef magic","auto decode","detect encoding","decode chain","multi layer","base64 gzip","powershell encodedcommand","rot13","deobfuscate","ctf","unknown encoding","identify encoding"],"icon":"Wand2","relatedTools":["base64-text","hex-text","url-encode","encoding-gzip-base64"],"packageImportPath":"@open-utility-tools/core/tools/encoding/magic-decoder","webPath":"/tools/magic-decoder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
