// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-protobuf-binary-decoder-v1","name":"Protobuf Binary Decoder","slug":"protobuf-binary-decoder","description":"Decode protobuf wire bytes into field numbers, wire types, and raw scalar values.","category":"encoding","tags":["protobuf","binary","decode","wire"],"keywords":["protobuf","binary","decode","wire"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/encoding/protobuf-binary-decoder","webPath":"/tools/protobuf-binary-decoder/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
