// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"encoding-url-encode-v1","name":"URL Encode / Decode","slug":"url-encode","description":"Percent-encode and decode text or whole-component URL strings.","category":"encoding","tags":["url","percent","uri","encode","decode"],"keywords":["url","uri","percent encoding","escape","encodeURIComponent"],"icon":"Link","relatedTools":["base64-text","html-entities","jwt-decoder"],"packageImportPath":"@open-utility-tools/core/tools/encoding/url-encode","webPath":"/tools/url-encode/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
