'use client';

import { useCallback } from 'react';

import { TextToolLayout } from '@/components/tools/text-tool';

function goName(key: string): string {
  const n = key.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''));
  const capped = n.charAt(0).toUpperCase() + n.slice(1);
  return /^[A-Za-z]/.test(capped) ? capped : 'Field' + capped;
}

function goType(v: unknown, key: string, structs: string[], seen: Set<string>): string {
  if (v === null) return 'interface{}';
  if (Array.isArray(v)) {
    if (v.length === 0) return '[]interface{}';
    return '[]' + goType(v[0], key, structs, seen);
  }
  if (typeof v === 'object') {
    const name = goName(key);
    buildStruct(v as Record<string, unknown>, name, structs, seen);
    return name;
  }
  if (typeof v === 'number') return Number.isInteger(v) ? 'int' : 'float64';
  if (typeof v === 'boolean') return 'bool';
  return 'string';
}

function buildStruct(obj: Record<string, unknown>, name: string, structs: string[], seen: Set<string>) {
  if (seen.has(name)) return;
  seen.add(name);
  const lines = [`type ${name} struct {`];
  for (const [key, val] of Object.entries(obj)) {
    lines.push(`\t${goName(key)} ${goType(val, key, structs, seen)} \`json:"${key}"\``);
  }
  lines.push('}');
  structs.push(lines.join('\n'));
}

export default function JsonToGoTool() {
  const transform = useCallback((input: string) => {
    if (!input.trim()) return '';
    let data: unknown;
    try {
      data = JSON.parse(input);
    } catch (e) {
      throw new Error(e instanceof Error ? e.message : 'Invalid JSON');
    }
    const structs: string[] = [];
    const seen = new Set<string>();
    if (Array.isArray(data)) data = data[0] ?? {};
    if (typeof data !== 'object' || data === null) throw new Error('Expected a JSON object.');
    buildStruct(data as Record<string, unknown>, 'AutoGenerated', structs, seen);
    return structs.reverse().join('\n\n');
  }, []);

  return (
    <TextToolLayout
      transform={transform}
      inputLabel="JSON"
      outputLabel="Go"
      sample={'{\n  "id": 1,\n  "name": "Ada",\n  "active": true,\n  "tags": ["a","b"]\n}'}
      downloadName="types.go"
      downloadMime="text/plain"
    />
  );
}
