// AUTO-GENERATED by scripts/gen-registry.ts — do not edit.
// Run `bun run registry:gen` to regenerate.
import type { ToolConfig, ToolMetaStatic } from "./types";

export const TOOL_META: ToolMetaStatic[] = [
  {"id":"encoding-base64-text-v1","name":"Base64 Encode / Decode","slug":"base64-text","description":"Encode text to Base64 (standard or URL-safe) and decode it back — live.","category":"encoding","tags":["base64","b64","url-safe","encode","decode"],"keywords":["base64","b64","atob","btoa","url safe","encode","decode"],"icon":"Binary","relatedTools":["hex-text","url-encode","base32-text","hash-text"],"loadWasm":true},
  {"id":"text-case-converter-v1","name":"Case Converter","slug":"case-converter","description":"Convert text between camelCase, snake_case, kebab-case, Title Case and more.","category":"text","tags":["case","camel","snake","kebab","title"],"keywords":["camelcase","snake_case","kebab","pascal","title case","uppercase","lowercase"],"icon":"CaseSensitive","relatedTools":["slugify","json-formatter","hash-text"]},
  {"id":"crypto-hash-text-v1","name":"Hash Text","slug":"hash-text","description":"Compute MD5, SHA-1, SHA-256/384/512, SHA-3, BLAKE3 and CRC32 digests of text — live, in your browser.","category":"crypto","tags":["md5","sha256","sha512","blake3","crc32","digest"],"keywords":["hash","checksum","digest","sha","md5","blake3","fingerprint"],"icon":"Hash","relatedTools":["hmac-generator","hash-file","base64-text"],"loadWasm":true},
  {"id":"encoding-html-entities-v1","name":"HTML Entity Encode / Decode","slug":"html-entities","description":"Escape text to HTML entities and unescape entities back to text.","category":"encoding","tags":["html","entities","escape","unescape"],"keywords":["html entities","escape","unescape","ampersand","nbsp"],"icon":"Code","relatedTools":["url-encode","base64-text","json-formatter"]},
  {"id":"data-json-formatter-v1","name":"JSON Formatter","slug":"json-formatter","description":"Pretty-print, minify, and validate JSON with configurable indentation.","category":"data","tags":["json","format","beautify","minify","validate"],"keywords":["json","pretty","prettify","beautify","minify","validate","lint"],"icon":"Braces","relatedTools":["json-minify","json-to-csv","yaml-to-json"]},
  {"id":"web-jwt-decoder-v1","name":"JWT Decoder","slug":"jwt-decoder","description":"Decode and inspect JSON Web Token header & payload (no verification).","category":"web","tags":["jwt","token","json web token","decode","auth"],"keywords":["jwt","jws","bearer","claims","token","auth","oauth"],"icon":"KeyRound","relatedTools":["base64-text","json-formatter","hash-text"]},
  {"id":"text-slugify-v1","name":"Slugify","slug":"slugify","description":"Turn any text into a clean, URL-safe slug.","category":"text","tags":["slug","url","permalink","kebab"],"keywords":["slug","url safe","permalink","seo","kebab"],"icon":"Link2","relatedTools":["case-converter","url-encode","json-formatter"]},
  {"id":"encoding-url-encode-v1","name":"URL Encode / Decode","slug":"url-encode","description":"Percent-encode and decode text or whole-component URL strings.","category":"encoding","tags":["url","percent","uri","encode","decode"],"keywords":["url","uri","percent encoding","escape","encodeURIComponent"],"icon":"Link","relatedTools":["base64-text","html-entities","jwt-decoder"]},
  {"id":"generators-uuid-v1","name":"UUID Generator","slug":"uuid-generator","description":"Generate RFC 4122 v4 (random) and v7 (time-ordered) UUIDs in bulk.","category":"generators","tags":["uuid","guid","v4","v7","id"],"keywords":["uuid","guid","unique id","v4","v7","random id"],"icon":"Fingerprint","relatedTools":["hash-text","base64-text","jwt-decoder"]},
];

/** Lazy component loaders, keyed by slug. Each is its own chunk. */
export const TOOL_COMPONENTS: Record<string, ToolConfig["component"]> = {
  "base64-text": () => import("@/tools/encoding/base64-text/ui"),
  "case-converter": () => import("@/tools/text/case-converter/ui"),
  "hash-text": () => import("@/tools/crypto/hash-text/ui"),
  "html-entities": () => import("@/tools/encoding/html-entities/ui"),
  "json-formatter": () => import("@/tools/data/json-formatter/ui"),
  "jwt-decoder": () => import("@/tools/web/jwt-decoder/ui"),
  "slugify": () => import("@/tools/text/slugify/ui"),
  "url-encode": () => import("@/tools/encoding/url-encode/ui"),
  "uuid-generator": () => import("@/tools/generators/uuid-generator/ui"),
};
