// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-asyncapi-validator-preview-v1","name":"AsyncAPI Validator Preview","slug":"asyncapi-validator-preview","description":"Validate common AsyncAPI structure and summarize channels, operations, messages, and servers.","category":"web","tags":["asyncapi","events","api","yaml"],"keywords":["asyncapi","events","api","yaml"],"icon":"Radio","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/asyncapi-validator-preview","webPath":"/tools/asyncapi-validator-preview/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
