// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-avro-schema-validator-v1","name":"Avro Schema Validator","slug":"avro-schema-validator","description":"Validate common Avro schema structure and summarize records, fields, enums, and unions.","category":"web","tags":["avro","schema","json","events"],"keywords":["avro","schema","json","events"],"icon":"FileJson","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/avro-schema-validator","webPath":"/tools/avro-schema-validator/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
