// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-bimi-record-checker-v1","name":"BIMI Record Checker","slug":"bimi-record-checker","description":"Inspect BIMI TXT records for version, logo URL, authority URL, and deployment checklist.","category":"web","tags":["bimi","dns","email","brand"],"keywords":["bimi","dns","email","brand"],"icon":"FileBadge","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/bimi-record-checker","webPath":"/tools/bimi-record-checker/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
