// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-chmod-v1","name":"Chmod Calculator","slug":"chmod-calculator","description":"Toggle Unix permission bits and get the octal + symbolic chmod value.","category":"web","tags":["chmod","permissions","unix","octal","file"],"keywords":["chmod","file permissions","octal","rwx","unix permissions","755"],"icon":"Lock","relatedTools":["number-base-converter","gitignore-generator","mime-types"],"packageImportPath":"@open-utility-tools/core/tools/web/chmod-calculator","webPath":"/tools/chmod-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
