// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-cookie-parser-v1","name":"Cookie Parser","slug":"cookie-parser","description":"Parse a Cookie or Set-Cookie header into a readable table of attributes.","category":"web","tags":["cookie","header","parse","set-cookie"],"keywords":["cookie parser","set-cookie","http cookie","attributes","samesite"],"icon":"FileSearch","relatedTools":["url-parser","jwt-decoder","http-status-codes"],"packageImportPath":"@open-utility-tools/core/tools/web/cookie-parser","webPath":"/tools/cookie-parser/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
