// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-dmarc-report-xml-parser-v1","name":"DMARC Report XML Parser","slug":"dmarc-report-xml-parser","description":"Parse aggregate DMARC XML reports into source IPs, counts, dispositions, and auth results.","category":"web","tags":["dmarc","xml","email","reports"],"keywords":["dmarc","xml","email","reports"],"icon":"FileSearch","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/dmarc-report-xml-parser","webPath":"/tools/dmarc-report-xml-parser/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
