// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-dmarc-record-builder-v1","name":"DMARC Record Builder","slug":"dmarc-record-builder","description":"Build DMARC TXT policies with reporting URIs, alignment, percentage, and subdomain policy.","category":"web","tags":["dmarc","dns","email","txt"],"keywords":["dmarc","dns","email","txt"],"icon":"Mail","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/dmarc-record-builder","webPath":"/tools/dmarc-record-builder/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
