// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-dns-record-dig-ui-v1","name":"DNS Record dig UI","slug":"dns-record-dig-ui","description":"Build copyable dig commands and summarize pasted DNS records.","category":"web","tags":["dns","dig","records","network"],"keywords":["dns","dig","records","network"],"icon":"Globe","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/dns-record-dig-ui","webPath":"/tools/dns-record-dig-ui/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
