// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-dnssec-chain-visualizer-v1","name":"DNSSEC Chain Visualizer","slug":"dnssec-chain-visualizer","description":"Inspect pasted DS, DNSKEY, RRSIG, and NSEC records and outline the trust chain.","category":"web","tags":["dnssec","dns","security","records"],"keywords":["dnssec","dns","security","records"],"icon":"ShieldCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/dnssec-chain-visualizer","webPath":"/tools/dnssec-chain-visualizer/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
