// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-grpcurl-command-builder-v1","name":"grpcurl Command Builder","slug":"grpcurl-command-builder","description":"Build grpcurl commands with host, service method, headers, TLS, and JSON body.","category":"web","tags":["grpc","grpcurl","command","api"],"keywords":["grpc","grpcurl","command","api"],"icon":"Terminal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/grpcurl-command-builder","webPath":"/tools/grpcurl-command-builder/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
