// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-hsts-preload-checker-v1","name":"HSTS Preload Checker","slug":"hsts-preload-checker","description":"Check Strict-Transport-Security headers against common preload requirements.","category":"web","tags":["hsts","headers","security","tls"],"keywords":["hsts","headers","security","tls"],"icon":"ShieldCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/hsts-preload-checker","webPath":"/tools/hsts-preload-checker/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
