// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-html-to-text-v1","name":"HTML to Text","slug":"html-to-text","description":"Strip HTML tags and decode entities to get clean plain text.","category":"web","tags":["html","strip tags","plain text","extract"],"keywords":["html to text","strip tags","remove html","plain text","extract text"],"icon":"FileCode","relatedTools":["html-entities","markdown-to-html","whitespace-cleaner"],"packageImportPath":"@open-utility-tools/core/tools/web/html-to-text","webPath":"/tools/html-to-text/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
