// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-http-status-codes-v1","name":"HTTP Status Codes","slug":"http-status-codes","description":"Searchable reference of HTTP status codes and their meanings.","category":"web","tags":["http","status","codes","reference","404","500"],"keywords":["http status","status codes","404","500","200","reference","response codes"],"icon":"Globe","relatedTools":["mime-types","url-parser","jwt-decoder"],"packageImportPath":"@open-utility-tools/core/tools/web/http-status-codes","webPath":"/tools/http-status-codes/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
