// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-http-multipart-form-data-builder-v1","name":"Multipart Form-Data Builder","slug":"http-multipart-form-data-builder","description":"Build multipart/form-data bodies and cURL snippets from field definitions.","category":"web","tags":["http","multipart","form-data","api"],"keywords":["http","multipart","form-data","api"],"icon":"Rows3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/http-multipart-form-data-builder","webPath":"/tools/http-multipart-form-data-builder/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
