// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-http-request-replay-sanitizer-v1","name":"HTTP Request Replay Sanitizer","slug":"http-request-replay-sanitizer","description":"Redact secrets from captured HTTP requests and emit a safer replay snippet.","category":"web","tags":["http","request","redact","debug"],"keywords":["http","request","redact","debug"],"icon":"Eraser","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/http-request-replay-sanitizer","webPath":"/tools/http-request-replay-sanitizer/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
