// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-javascript-beautifier-minifier-v1","name":"JavaScript Beautifier & Minifier","slug":"javascript-beautifier-minifier","description":"Beautify messy JavaScript with consistent indentation or minify it by stripping comments and whitespace, with ASI-safe output and no renaming, entirely in your browser.","category":"web","tags":["javascript","js","beautify","minify","format"],"keywords":["javascript beautifier","javascript minifier","js formatter","js prettifier","minify js","uglify alternative","format javascript online","whitespace minifier","remove comments javascript"],"icon":"FileCode","relatedTools":["css-minify","web-html-minify","json-formatter"],"packageImportPath":"@open-utility-tools/core/tools/web/javascript-beautifier-minifier","webPath":"/tools/javascript-beautifier-minifier/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
