// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-keyboard-event-inspector-v1","name":"Keyboard Event Inspector (Keycode Info)","slug":"keyboard-event-inspector","description":"Press any key to see event.key, event.code, keyCode, location and modifiers, then copy a ready-made shortcut condition, hotkey string and event log.","category":"web","tags":["keyboard","keycode","event.key","event.code","hotkey","shortcut"],"keywords":["keycode","key code","event.code","event.key","keydown","keyup","keypress","which","charcode","keyboard shortcut","hotkey generator","keyboard tester","ime composition","beforeinput","keyboard layout map"],"icon":"Keyboard","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/keyboard-event-inspector","webPath":"/tools/keyboard-event-inspector/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
