// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-markdown-preview-v1","name":"Markdown to HTML","slug":"markdown-to-html","description":"Render Markdown to HTML with a live preview and copyable output.","category":"web","tags":["markdown","md","html","preview","render"],"keywords":["markdown","md to html","preview","render markdown","gfm"],"icon":"FileCode","relatedTools":["html-to-text","html-entities","json-formatter"],"packageImportPath":"@open-utility-tools/core/tools/web/markdown-to-html","webPath":"/tools/markdown-to-html/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
