// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-mqtt-topic-matcher-v1","name":"MQTT Topic Matcher","slug":"mqtt-topic-matcher","description":"Test MQTT topic filters with + and # wildcards against sample topics.","category":"web","tags":["mqtt","topic","wildcard","events"],"keywords":["mqtt","topic","wildcard","events"],"icon":"Radio","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/mqtt-topic-matcher","webPath":"/tools/mqtt-topic-matcher/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
