// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-mta-sts-policy-checker-v1","name":"MTA-STS Policy Checker","slug":"mta-sts-policy-checker","description":"Validate MTA-STS TXT and policy file contents for secure inbound mail delivery.","category":"web","tags":["mta-sts","email","tls","dns"],"keywords":["mta-sts","email","tls","dns"],"icon":"ShieldCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/mta-sts-policy-checker","webPath":"/tools/mta-sts-policy-checker/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
