// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-oauth-token-response-inspector-v1","name":"OAuth Token Response Inspector","slug":"oauth-token-response-inspector","description":"Inspect an OAuth token response, token types, scopes, and expiry.","category":"web","tags":["oauth","token","json","auth"],"keywords":["oauth","token","json","auth"],"icon":"Key","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/oauth-token-response-inspector","webPath":"/tools/oauth-token-response-inspector/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
