// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-oauth-authorization-url-builder-v1","name":"OAuth Authorization URL Builder","slug":"oauth-authorization-url-builder","description":"Build OAuth 2.0 or OIDC authorization URLs with scopes, PKCE, state, and nonce.","category":"web","tags":["oauth","oidc","url","auth"],"keywords":["oauth","oidc","url","auth"],"icon":"Link","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/oauth-authorization-url-builder","webPath":"/tools/oauth-authorization-url-builder/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
