// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-oidc-id-token-validator-v1","name":"OIDC ID Token Validator","slug":"oidc-id-token-validator","description":"Decode an ID token and check issuer, audience, nonce, expiry, and clock claims.","category":"web","tags":["oidc","jwt","token","auth"],"keywords":["oidc","jwt","token","auth"],"icon":"ShieldCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/oidc-id-token-validator","webPath":"/tools/oidc-id-token-validator/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
