// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-oidc-discovery-inspector-v1","name":"OIDC Discovery Inspector","slug":"oidc-discovery-inspector","description":"Parse OpenID Connect discovery metadata and summarize endpoints, algorithms, and grants.","category":"web","tags":["oidc","openid","oauth","json"],"keywords":["oidc","openid","oauth","json"],"icon":"Compass","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/oidc-discovery-inspector","webPath":"/tools/oidc-discovery-inspector/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
