// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-openapi-security-scheme-inspector-v1","name":"OpenAPI Security Scheme Inspector","slug":"openapi-security-scheme-inspector","description":"Summarize API keys, HTTP auth, OAuth flows, OpenID Connect URLs, and operation security.","category":"web","tags":["openapi","security","oauth","api"],"keywords":["openapi","security","oauth","api"],"icon":"Lock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/openapi-security-scheme-inspector","webPath":"/tools/openapi-security-scheme-inspector/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
