// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-openapi-validator-linter-v1","name":"OpenAPI Validator & Linter","slug":"openapi-validator-linter","description":"Validate common OpenAPI structure and flag missing info, paths, responses, and schemas.","category":"web","tags":["openapi","swagger","api","lint"],"keywords":["openapi","swagger","api","lint"],"icon":"FileSearch","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/openapi-validator-linter","webPath":"/tools/openapi-validator-linter/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
