// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-openapi-schema-example-generator-v1","name":"OpenAPI Schema Example Generator","slug":"openapi-schema-example-generator","description":"Generate JSON examples from OpenAPI component schemas.","category":"web","tags":["openapi","schema","example","json"],"keywords":["openapi","schema","example","json"],"icon":"Braces","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/openapi-schema-example-generator","webPath":"/tools/openapi-schema-example-generator/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
