// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-css-units-v1","name":"PX ↔ REM Converter","slug":"px-rem-converter","description":"Convert between px, rem and em given a configurable root font size.","category":"web","tags":["css","px","rem","em","units"],"keywords":["px to rem","rem to px","em","css units","font size"],"icon":"Ruler","relatedTools":["css-minify","color-converter","unit-converter"],"packageImportPath":"@open-utility-tools/core/tools/web/px-rem-converter","webPath":"/tools/px-rem-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
