// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-query-params-v1","name":"Query String ↔ JSON","slug":"query-params","description":"Convert a URL query string to JSON and back, handling repeated keys.","category":"web","tags":["query","querystring","json","params","url"],"keywords":["query string","querystring","params to json","url params","searchparams"],"icon":"Link2","relatedTools":["url-parser","url-encode","json-formatter"],"packageImportPath":"@open-utility-tools/core/tools/web/query-params","webPath":"/tools/query-params/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
