// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-saml-attribute-mapper-v1","name":"SAML Attribute Mapper","slug":"saml-attribute-mapper","description":"Map SAML attributes to app claims using a simple mapping table.","category":"web","tags":["saml","attributes","mapping","sso"],"keywords":["saml","attributes","mapping","sso"],"icon":"Shuffle","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/saml-attribute-mapper","webPath":"/tools/saml-attribute-mapper/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
