// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-saml-request-decoder-v1","name":"SAML Request Decoder","slug":"saml-request-decoder","description":"Decode a SAMLRequest from URL, query string, or form input and inspect the XML.","category":"web","tags":["saml","sso","decode","xml"],"keywords":["samlrequest","redirect binding","base64","deflate"],"icon":"ShieldCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/saml-request-decoder","webPath":"/tools/saml-request-decoder/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
