// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-saml-redirect-binding-builder-v1","name":"SAML Redirect Binding Builder","slug":"saml-redirect-binding-builder","description":"Build the URL parameters used by SAML HTTP-Redirect binding.","category":"web","tags":["saml","redirect","binding","sso"],"keywords":["saml redirect","relaystate","samlrequest"],"icon":"Route","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/saml-redirect-binding-builder","webPath":"/tools/saml-redirect-binding-builder/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
