// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-scim-user-payload-builder-v1","name":"SCIM User Payload Builder","slug":"scim-user-payload-builder","description":"Build a SCIM 2.0 user JSON payload for provisioning tests.","category":"web","tags":["scim","identity","json","provisioning"],"keywords":["scim","identity","json","provisioning"],"icon":"User","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/scim-user-payload-builder","webPath":"/tools/scim-user-payload-builder/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
