// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-scim-filter-tester-v1","name":"SCIM Filter Tester","slug":"scim-filter-tester","description":"Test basic SCIM filter expressions against pasted sample users.","category":"web","tags":["scim","filter","identity","json"],"keywords":["scim","filter","identity","json"],"icon":"Filter","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/scim-filter-tester","webPath":"/tools/scim-filter-tester/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
