// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-security-headers-auditor-v1","name":"Security Headers Auditor","slug":"security-headers-auditor","description":"Audit pasted HTTP response headers for CSP, HSTS, frame, MIME, referrer, and permissions policy.","category":"web","tags":["security headers","http","csp","audit"],"keywords":["security headers","http","csp","audit"],"icon":"Shield","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/security-headers-auditor","webPath":"/tools/security-headers-auditor/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
