// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-soap-fault-parser-v1","name":"SOAP Fault Parser","slug":"soap-fault-parser","description":"Parse SOAP 1.1/1.2 faults into code, reason, actor/node, role, and detail.","category":"web","tags":["soap","fault","xml","debug"],"keywords":["soap","fault","xml","debug"],"icon":"FileX","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/soap-fault-parser","webPath":"/tools/soap-fault-parser/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
