// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-spf-flattening-analyzer-v1","name":"SPF Flattening Analyzer","slug":"spf-flattening-analyzer","description":"Count SPF mechanisms and estimate DNS lookup pressure before flattening.","category":"web","tags":["spf","dns","email","analysis"],"keywords":["spf","dns","email","analysis"],"icon":"FileSearch","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/spf-flattening-analyzer","webPath":"/tools/spf-flattening-analyzer/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
