// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-tls-rpt-record-builder-v1","name":"TLS-RPT Record Builder","slug":"tls-rpt-record-builder","description":"Build SMTP TLS reporting DNS records for mail delivery diagnostics.","category":"web","tags":["tls-rpt","email","dns","txt"],"keywords":["tls-rpt","email","dns","txt"],"icon":"Mail","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/tls-rpt-record-builder","webPath":"/tools/tls-rpt-record-builder/","coreImportPath":"@open-utility-tools/core/developer-tools"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
