// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-user-agent-v1","name":"User-Agent Parser","slug":"user-agent-parser","description":"Parse a User-Agent string into browser, engine, OS and device.","category":"web","tags":["user agent","ua","browser","parse"],"keywords":["user agent","ua parser","browser detect","os detect","device"],"icon":"ScanLine","relatedTools":["url-parser","http-status-codes","mime-types"],"packageImportPath":"@open-utility-tools/core/tools/web/user-agent-parser","webPath":"/tools/user-agent-parser/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
