// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-media-query-generator-v1","name":"CSS Media Query Generator","slug":"web-media-query-generator","description":"Build responsive @media queries from breakpoints and feature conditions.","category":"web","tags":["css","media-query","responsive","breakpoints"],"keywords":["media query","responsive","breakpoint","min-width","max-width","prefers-color-scheme","orientation","css"],"icon":"Smartphone","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-media-query-generator","webPath":"/tools/web-media-query-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
