// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-http-method-reference-v1","name":"HTTP Method Reference","slug":"web-http-method-reference","description":"Cheatsheet of HTTP methods with safe/idempotent/cacheable/body semantics.","category":"web","tags":["http","methods","reference","rest","rfc"],"keywords":["http method","verb","get post put delete","idempotent","safe method","cacheable","webdav","rfc 9110"],"icon":"Send","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-http-method-reference","webPath":"/tools/web-http-method-reference/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
