// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-cache-control-builder-v1","name":"Cache-Control Builder","slug":"web-cache-control-builder","description":"Compose and explain a Cache-Control header from caching directive checkboxes and durations.","category":"web","tags":["http","cache","headers","cdn","performance"],"keywords":["cache-control","max-age","s-maxage","no-store","immutable","stale-while-revalidate","http header"],"icon":"Clock3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-cache-control-builder","webPath":"/tools/web-cache-control-builder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
