// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-curl-to-fetch-v1","name":"cURL to Code","slug":"web-curl-to-fetch","description":"Convert a curl command into a browser fetch() call, parsing method, URL, headers, and body into ready-to-paste JavaScript.","category":"web","tags":["curl","fetch","javascript","http"],"keywords":["curl","fetch","javascript","http","request","convert"],"icon":"Terminal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-curl-to-fetch","webPath":"/tools/web-curl-to-fetch/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
