// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-ip-address-converter-v1","name":"IP Address Converter","slug":"web-ip-address-converter","description":"Convert an IPv4/IPv6 address between dotted, integer, hex, binary, and expanded forms.","category":"web","tags":["ip","ipv4","ipv6","convert","network"],"keywords":["ip to integer","ip to hex","ip to binary","ipv6 expand","rfc 5952","ipv4-mapped","dotted decimal"],"icon":"ArrowLeftRight","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-ip-address-converter","webPath":"/tools/web-ip-address-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
