// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-url-query-sorter-v1","name":"URL Query Param Sorter","slug":"web-url-query-sorter","description":"Canonicalize a URL by sorting and optionally deduplicating query parameters.","category":"web","tags":["url","query","sort","canonical","params"],"keywords":["querystring","normalize","dedupe","search params","canonicalize url","order"],"icon":"ArrowDownUp","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-url-query-sorter","webPath":"/tools/web-url-query-sorter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
