// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-json-to-toml-v1","name":"JSON to TOML","slug":"web-json-to-toml","description":"Convert JSON configuration into TOML format and back, handling tables, arrays of tables, nested keys, strings, and numeric/boolean scalars.","category":"web","tags":["json","toml","convert"],"keywords":["json","toml","config","convert","cargo","settings"],"icon":"ArrowLeftRight","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-json-to-toml","webPath":"/tools/web-json-to-toml/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
