// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-json-tree-viewer-v1","name":"JSON to Pretty / Tree","slug":"web-json-tree-viewer","description":"Visualize JSON as a collapsible, indented tree with type annotations and node counts, making large nested payloads easy to navigate.","category":"web","tags":["json","tree","viewer"],"keywords":["json","tree","viewer","visualize","collapse","explore"],"icon":"List","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-json-tree-viewer","webPath":"/tools/web-json-tree-viewer/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
