// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-open-graph-preview-card-v1","name":"Open Graph / Twitter Card Preview","slug":"web-open-graph-preview-card","description":"Parses OG and Twitter meta tags from pasted HTML and shows the resolved share-card fields.","category":"web","tags":["open graph","twitter card","meta","seo","preview"],"keywords":["open graph","og:title","twitter card","meta tags","social preview","share card","seo","og:image"],"icon":"Eye","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-open-graph-preview-card","webPath":"/tools/web-open-graph-preview-card/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
