// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-url-normalizer-v1","name":"URL Normalizer","slug":"web-url-normalizer","description":"Canonicalize a URL by lowercasing host, resolving dot segments, sorting params, and stripping defaults.","category":"web","tags":["url","normalize","canonical","query","rfc 3986"],"keywords":["canonicalize","sort params","dedupe","trailing slash","default port","cleanup"],"icon":"Route","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-url-normalizer","webPath":"/tools/web-url-normalizer/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
