// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-favicon-link-generator-v1","name":"Favicon Link Tags Generator","slug":"web-favicon-link-generator","description":"Generate the full set of favicon and app-icon link tags for all platforms.","category":"web","tags":["favicon","html","icons","manifest","apple-touch","meta"],"keywords":["favicon","link tags","apple touch icon","web manifest","theme-color","msapplication","maskable","pwa icons"],"icon":"Link","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-favicon-link-generator","webPath":"/tools/web-favicon-link-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
