// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-clip-path-generator-v1","name":"CSS clip-path Shape Generator","slug":"web-clip-path-generator","description":"Generate polygon, circle, ellipse and inset clip-path values with live preview.","category":"web","tags":["css","clip-path","shapes","polygon","design"],"keywords":["clip-path","polygon","circle","ellipse","inset","css shape","mask"],"icon":"Shapes","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-clip-path-generator","webPath":"/tools/web-clip-path-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
