// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-html-entity-picker-v1","name":"HTML Entity Picker","slug":"web-html-entity-picker","description":"Searchable reference of named HTML entities with their character, numeric, and hex codes ready to copy.","category":"web","tags":["html","entity","reference","unicode","symbols"],"keywords":["html entity","named entity","character reference","nbsp","mdash","copyright","numeric reference","hex code point"],"icon":"Ampersand","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-html-entity-picker","webPath":"/tools/web-html-entity-picker/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
