// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-open-graph-generator-v1","name":"Open Graph Meta Tag Generator","slug":"web-open-graph-generator","description":"Produce Open Graph and Twitter Card meta tags from title, description, URL, image, and type fields for rich social link previews.","category":"web","tags":["open-graph","meta","twitter-card","seo"],"keywords":["open-graph","meta","twitter-card","seo","social","preview"],"icon":"Tags","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-open-graph-generator","webPath":"/tools/web-open-graph-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
