// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-transform-generator-v1","name":"CSS Transform Generator","slug":"web-transform-generator","description":"Compose translate, rotate, scale, skew and perspective into one transform value.","category":"web","tags":["css","transform","animation","3d","generator"],"keywords":["css transform","translate","rotate","scale","skew","perspective","transform-origin","rotateX","preview"],"icon":"Globe","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-transform-generator","webPath":"/tools/web-transform-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
