// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-csp-builder-v1","name":"Content-Security-Policy Builder","slug":"web-csp-builder","description":"Build a CSP header from per-directive source lists with keyword and nonce/hash helpers.","category":"web","tags":["http","csp","security","headers","policy"],"keywords":["content-security-policy","csp","script-src","nonce","strict-dynamic","unsafe-inline","header"],"icon":"ShieldCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-csp-builder","webPath":"/tools/web-csp-builder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
