// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-robots-txt-tester-v1","name":"robots.txt Tester","slug":"web-robots-txt-tester","description":"Test whether a URL path is allowed for a user-agent against pasted robots.txt rules.","category":"web","tags":["robots","seo","crawler","allow","disallow"],"keywords":["robots.txt","user-agent","googlebot","rfc 9309","crawl-delay","sitemap"],"icon":"Bug","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-robots-txt-tester","webPath":"/tools/web-robots-txt-tester/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
