// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-ipv6-expander-v1","name":"IPv6 Expand & Compress","slug":"web-ipv6-expander","description":"Expand IPv6 addresses to full form or compress to canonical RFC 5952 shorthand.","category":"web","tags":["ipv6","network","expand","compress","rfc5952"],"keywords":["ipv6 expand","ipv6 compress","canonical ipv6","rfc 5952","shorten ipv6","normalize ipv6"],"icon":"Minimize2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-ipv6-expander","webPath":"/tools/web-ipv6-expander/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
