// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-xml-formatter-v1","name":"XML Formatter","slug":"web-xml-formatter","description":"Pretty-print and indent minified XML, or minify verbose XML by stripping whitespace between tags, with self-closing tag handling.","category":"web","tags":["xml","format","beautify"],"keywords":["xml","format","beautify","minify","pretty","indent"],"icon":"Code2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-xml-formatter","webPath":"/tools/web-xml-formatter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
