// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-css-to-tailwind-v1","name":"CSS to Tailwind","slug":"web-css-to-tailwind","description":"Translate common CSS declarations into equivalent Tailwind utility classes, mapping spacing, colors, flex, font, and border properties.","category":"web","tags":["css","tailwind","convert"],"keywords":["css","tailwind","convert","utility","classes","frontend"],"icon":"Wand2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-css-to-tailwind","webPath":"/tools/web-css-to-tailwind/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
