// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-semver-bump-v1","name":"Semver Version Bumper","slug":"web-semver-bump","description":"Compute the next semantic version by bumping major, minor, patch, or prerelease according to semver rules.","category":"web","tags":["semver","version","bump","npm","release"],"keywords":["increment version","major minor patch","prerelease","premajor","preminor","prepatch","alpha","beta"],"icon":"TrendingUp","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-semver-bump","webPath":"/tools/web-semver-bump/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
