// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-set-cookie-builder-v1","name":"Set-Cookie Header Builder","slug":"web-set-cookie-builder","description":"Build a syntactically correct Set-Cookie header from name, value, and attribute toggles.","category":"web","tags":["http","cookie","headers","security"],"keywords":["set-cookie","cookie","samesite","httponly","secure","__host-","max-age","rfc 6265","header"],"icon":"Cookie","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-set-cookie-builder","webPath":"/tools/web-set-cookie-builder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
