// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-htaccess-redirect-builder-v1","name":".htaccess Redirect Builder","slug":"web-htaccess-redirect-builder","description":"Build Apache .htaccess redirect rules (Redirect, RewriteRule) from source/target URL pairs with status codes.","category":"web","tags":["htaccess","apache","redirect","rewrite","seo"],"keywords":["htaccess","apache","redirect","rewriterule","301","302","mod_rewrite","canonical","https"],"icon":"Route","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-htaccess-redirect-builder","webPath":"/tools/web-htaccess-redirect-builder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
