// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-regex-named-group-converter-v1","name":"Regex Named Group Reference Converter","slug":"web-regex-named-group-converter","description":"Convert between numbered capture groups and named capture groups in regex patterns and their backreferences/replacements.","category":"web","tags":["regex","capture groups","named groups","convert","backreference"],"keywords":["regular expression","numbered groups","k<name>","replacement","$1","rewrite"],"icon":"Parentheses","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-regex-named-group-converter","webPath":"/tools/web-regex-named-group-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
