// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-css-button-generator-v1","name":"CSS Button Generator","slug":"web-css-button-generator","description":"Design a button (colors, padding, radius, shadow, hover) and copy the CSS.","category":"web","tags":["css","button","ui","design","generator"],"keywords":["css button","hover","border-radius","box-shadow","button styles","transition"],"icon":"Pointer","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-css-button-generator","webPath":"/tools/web-css-button-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
