// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-meta-tags-generator-v1","name":"HTML Meta Tags Generator (SEO)","slug":"web-meta-tags-generator","description":"Generate the full SEO meta tag head block from title, description and options.","category":"web","tags":["seo","meta","html","head","tags"],"keywords":["meta tags","seo","head","description","canonical","robots","viewport","html"],"icon":"Tags","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-meta-tags-generator","webPath":"/tools/web-meta-tags-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
