// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-css-triangle-generator-v1","name":"CSS Triangle Generator","slug":"web-css-triangle-generator","description":"Create pure-CSS triangles using the border trick for any direction and size.","category":"web","tags":["css","triangle","border-trick","shapes","design"],"keywords":["css triangle","border trick","arrow","caret","tooltip arrow","pure css shape"],"icon":"Triangle","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-css-triangle-generator","webPath":"/tools/web-css-triangle-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
