// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-css-gradient-text-v1","name":"CSS Gradient Text Generator","slug":"web-css-gradient-text","description":"Produce the background-clip text trick CSS for gradient-colored text.","category":"web","tags":["css","gradient","text","design","background-clip"],"keywords":["gradient text","background-clip","text-fill-color","linear-gradient","radial-gradient","css"],"icon":"Type","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-css-gradient-text","webPath":"/tools/web-css-gradient-text/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
