// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-jsonld-schema-generator-v1","name":"JSON-LD Structured Data Generator","slug":"web-jsonld-schema-generator","description":"Generate schema.org JSON-LD for Article, Product, FAQ, Breadcrumb and more.","category":"web","tags":["json-ld","schema.org","seo","structured-data","rich-results"],"keywords":["json-ld","jsonld","schema.org","structured data","seo","rich snippets","product","faq","breadcrumb","article"],"icon":"FileJson","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-jsonld-schema-generator","webPath":"/tools/web-jsonld-schema-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
