// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-keyframes-generator-v1","name":"CSS Keyframes & Animation Generator","slug":"web-keyframes-generator","description":"Create @keyframes with stops plus the animation shorthand, and copy the CSS.","category":"web","tags":["css","animation","keyframes","transition","frontend"],"keywords":["css","keyframes","animation","transform","timing-function","easing","shorthand","preview"],"icon":"Sparkles","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-keyframes-generator","webPath":"/tools/web-keyframes-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
