// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-data-uri-builder-text-v1","name":"Text Data URI Builder","slug":"web-data-uri-builder-text","description":"Build a data: URI from pasted text with MIME type, charset, and base64 options.","category":"web","tags":["data-uri","base64","encode","svg","inline"],"keywords":["data uri","data url","base64","percent encode","inline svg","mime type","embed"],"icon":"Braces","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-data-uri-builder-text","webPath":"/tools/web-data-uri-builder-text/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
