// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-hsts-header-builder-v1","name":"HSTS Header Builder","slug":"web-hsts-header-builder","description":"Build and decode the Strict-Transport-Security header with preload-eligibility checks.","category":"web","tags":["hsts","http","security","headers","preload","https"],"keywords":["strict-transport-security","hsts","max-age","includeSubDomains","preload","hstspreload","https","security header"],"icon":"Lock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-hsts-header-builder","webPath":"/tools/web-hsts-header-builder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
