// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-accept-language-parser-v1","name":"Accept-Language / Accept Parser","slug":"web-accept-language-parser","description":"Parse and sort Accept-Language or Accept headers by quality value (q-factor).","category":"web","tags":["accept-language","http header","q-factor","content negotiation","parser"],"keywords":["Accept header","Accept-Language","quality value","q-factor","language preference","content negotiation"],"icon":"Languages","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-accept-language-parser","webPath":"/tools/web-accept-language-parser/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
