// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-jwt-expiry-inspector-v1","name":"JWT Expiry Inspector","slug":"web-jwt-expiry-inspector","description":"Decode a JWT and report human-readable issued/expiry times and remaining validity.","category":"web","tags":["jwt","token","expiry","auth","decode"],"keywords":["jwt","json web token","exp","iat","nbf","expiry","validity","bearer","auth token"],"icon":"Clock3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-jwt-expiry-inspector","webPath":"/tools/web-jwt-expiry-inspector/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
