// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-css-specificity-v1","name":"CSS Specificity Calculator","slug":"web-css-specificity","description":"Compute the specificity of any CSS selector as an (a,b,c) triple and rank multiple selectors to predict which rule wins.","category":"web","tags":["css","specificity","selector"],"keywords":["css","specificity","selector","cascade","calculate","frontend"],"icon":"Calculator","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-css-specificity","webPath":"/tools/web-css-specificity/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
