// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-cubic-bezier-v1","name":"CSS Cubic Bezier Generator","slug":"web-cubic-bezier","description":"Design CSS cubic-bezier easing curves with draggable control points and a live animation preview, outputting the transition-timing-function value.","category":"web","tags":["css","cubic-bezier","animation"],"keywords":["css","cubic-bezier","easing","animation","transition","curve"],"icon":"Spline","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-cubic-bezier","webPath":"/tools/web-cubic-bezier/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
