// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-json-to-java-v1","name":"JSON to Java Class","slug":"web-json-to-java","description":"Convert a JSON payload into POJO Java class definitions with typed fields and getters/setters, inferring nested classes and collection generics.","category":"web","tags":["json","java","codegen"],"keywords":["json","java","pojo","class","codegen","model"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-json-to-java","webPath":"/tools/web-json-to-java/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
