// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-sitemap-generator-v1","name":"XML Sitemap Generator","slug":"web-sitemap-generator","description":"Turn a list of URLs into a valid sitemap.xml with lastmod, changefreq, priority.","category":"web","tags":["sitemap","xml","seo","urls","crawl"],"keywords":["sitemap.xml","urlset","changefreq","lastmod","priority","search engine","google","robots"],"icon":"Network","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-sitemap-generator","webPath":"/tools/web-sitemap-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
