// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-flexbox-playground-v1","name":"CSS Flexbox Generator","slug":"web-flexbox-playground","description":"Set flex container and item properties from dropdowns and copy the generated CSS.","category":"web","tags":["css","flexbox","layout","generator","flex","preview"],"keywords":["flexbox","flex","justify-content","align-items","flex-direction","flex-wrap","gap","css layout"],"icon":"Columns3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-flexbox-playground","webPath":"/tools/web-flexbox-playground/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
