// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-content-type-charset-reference-v1","name":"Content-Type & Charset Reference","slug":"web-content-type-charset-reference","description":"Searchable reference of common Content-Type media types, charsets, and parameters.","category":"web","tags":["content-type","mime","charset","reference","http"],"keywords":["media type","mime type","utf-8","boundary","multipart","application/json","extensions"],"icon":"FileType","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-content-type-charset-reference","webPath":"/tools/web-content-type-charset-reference/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
