// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-html-minify-v1","name":"HTML Minifier / Beautifier","slug":"web-html-minify","description":"Minify HTML by stripping comments and whitespace, or pretty-print it.","category":"web","tags":["html","minify","beautify","format","whitespace"],"keywords":["html minify","compress html","pretty print","indent html","strip comments","collapse whitespace"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-html-minify","webPath":"/tools/web-html-minify/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
