// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-shell-arg-escaper-v1","name":"Shell Argument Escaper","slug":"web-shell-arg-escaper","description":"Safely quote and escape strings for bash, sh, PowerShell, or cmd.exe.","category":"web","tags":["shell","escape","quote","bash","powershell"],"keywords":["cmd","sh","argument","command line","injection","quoting"],"icon":"Terminal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-shell-arg-escaper","webPath":"/tools/web-shell-arg-escaper/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
