// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-slugify-variants-v1","name":"Slugify Variants Comparator","slug":"web-slugify-variants","description":"Generate multiple slug styles (kebab, snake, dot, path, GitHub-anchor) from one input at once for comparison.","category":"web","tags":["slug","slugify","kebab","snake","anchor"],"keywords":["url slug","dot case","path case","github heading","filename safe","diacritics"],"icon":"Link","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-slugify-variants","webPath":"/tools/web-slugify-variants/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
