// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-json-to-jsonschema-v1","name":"JSON to JSON Schema","slug":"web-json-to-jsonschema","description":"Generate a draft JSON Schema from an example JSON document, inferring types, required keys, array item shapes, and nested object definitions.","category":"web","tags":["json","schema","validation"],"keywords":["json","schema","jsonschema","validation","infer","draft"],"icon":"FileJson","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-json-to-jsonschema","webPath":"/tools/web-json-to-jsonschema/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
