// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-semver-compare-v1","name":"Semantic Version Comparator","slug":"web-semver-compare","description":"Compare two semantic versions to see which is greater, parse a version into major/minor/patch/prerelease, and test it against a range.","category":"web","tags":["semver","version","compare"],"keywords":["semver","version","compare","semantic","range","npm"],"icon":"GitCompare","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-semver-compare","webPath":"/tools/web-semver-compare/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
