// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-twitter-card-generator-v1","name":"Twitter Card Meta Generator","slug":"web-twitter-card-generator","description":"Build Twitter/X card meta tags (summary, large image, app, player).","category":"web","tags":["twitter","meta","seo","social","card"],"keywords":["twitter card","x card","summary_large_image","meta tags","social preview","player card","app card","og"],"icon":"MessageSquareCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-twitter-card-generator","webPath":"/tools/web-twitter-card-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
