// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-regex-escape-v1","name":"Regex Escape / Unescape","slug":"web-regex-escape","description":"Escape arbitrary text into a literal regex pattern or unescape an escaped pattern back to plain text.","category":"web","tags":["regex","escape","pattern","literal","text"],"keywords":["regex escape","regexp escape","literal pattern","escape special characters","unescape regex","metacharacters"],"icon":"Regex","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-regex-escape","webPath":"/tools/web-regex-escape/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
