// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-cache-busting-hash-appender-v1","name":"Asset Cache-Busting URL Builder","slug":"web-cache-busting-hash-appender","description":"Appends a deterministic version/hash query param to a list of asset URLs.","category":"web","tags":["cache","cache-busting","url","version","assets"],"keywords":["cache busting","asset version","query param","fingerprint","hash","static assets","cdn"],"icon":"Link2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-cache-busting-hash-appender","webPath":"/tools/web-cache-busting-hash-appender/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
