// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-url-builder-v1","name":"URL Builder","slug":"web-url-builder","description":"Assemble a valid URL from individual scheme, host, port, path, query, and fragment fields.","category":"web","tags":["url","query","builder","encode","whatwg"],"keywords":["url builder","query string","percent encoding","scheme","host","fragment","whatwg url","encodeuricomponent"],"icon":"Link","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-url-builder","webPath":"/tools/web-url-builder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
