// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-json-to-query-string-v1","name":"JSON to Query Params","slug":"web-json-to-query-string","description":"Turn a flat or nested JSON object into a properly encoded URL query string, with bracket notation for nested keys and arrays.","category":"web","tags":["json","query","url","encode"],"keywords":["json","query","url","params","encode","nested"],"icon":"Braces","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-json-to-query-string","webPath":"/tools/web-json-to-query-string/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
