// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-css-unit-converter-v1","name":"CSS Unit Converter (px / rem / em / pt / %)","slug":"web-css-unit-converter","description":"Convert between px, rem, em, pt, pc, vw/vh and percent using a root and base.","category":"web","tags":["css","units","px","rem","convert"],"keywords":["px to rem","em","pt","pc","vw","vh","percent","font-size","absolute","relative"],"icon":"Ruler","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-css-unit-converter","webPath":"/tools/web-css-unit-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
