// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-dotenv-to-json-v1","name":".env to JSON","slug":"web-dotenv-to-json","description":"Parse a .env / dotenv file into a JSON object and convert JSON back into .env format, handling quotes, comments, and export prefixes.","category":"web","tags":["env","dotenv","json","config"],"keywords":["env","dotenv","json","config","parse","environment"],"icon":"FileCog","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-dotenv-to-json","webPath":"/tools/web-dotenv-to-json/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
