// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-url-inspector-v1","name":"URL Inspector","slug":"web-url-inspector","description":"Break a URL into protocol, host, port, path segments, query parameters, and hash, displayed as a clear labeled component breakdown.","category":"web","tags":["url","parse","inspect"],"keywords":["url","parse","components","host","path","inspect"],"icon":"Globe","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-url-inspector","webPath":"/tools/web-url-inspector/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
