// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-http-headers-reference-v1","name":"HTTP Headers Reference","slug":"web-http-headers-reference","description":"Look up any HTTP request or response header to see its purpose, direction, example values, and whether it is standard or deprecated.","category":"web","tags":["http","headers","reference"],"keywords":["http","headers","reference","request","response","lookup"],"icon":"Network","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-http-headers-reference","webPath":"/tools/web-http-headers-reference/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
