// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-etag-conditional-builder-v1","name":"ETag & Conditional Request Builder","slug":"web-etag-conditional-builder","description":"Generate ETag values and matching If-None-Match / If-Modified-Since request headers.","category":"web","tags":["etag","http","cache","conditional","headers","hash"],"keywords":["etag","if-none-match","if-modified-since","last-modified","304 not modified","conditional request","weak etag","caching"],"icon":"Fingerprint","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-etag-conditional-builder","webPath":"/tools/web-etag-conditional-builder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
