// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"web-web-htaccess-snippet-v1","name":"Apache .htaccess Snippet Generator","slug":"web-htaccess-snippet","description":"Generate .htaccess rules for redirects, HTTPS, rewrites, headers, and caching.","category":"web","tags":["htaccess","apache","headers","caching","rewrite"],"keywords":["htaccess","apache","mod_rewrite","mod_headers","mod_expires","cache-control","security headers","csp","https"],"icon":"FileCog","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/web/web-htaccess-snippet","webPath":"/tools/web-htaccess-snippet/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
