export interface MimeEntry {
  ext: string;
  mime: string;
  name: string;
}

export const MIME_TYPES: MimeEntry[] = [
  { ext: 'txt', mime: 'text/plain', name: 'Plain text' },
  { ext: 'html', mime: 'text/html', name: 'HTML' },
  { ext: 'css', mime: 'text/css', name: 'CSS' },
  { ext: 'csv', mime: 'text/csv', name: 'CSV' },
  { ext: 'md', mime: 'text/markdown', name: 'Markdown' },
  { ext: 'js', mime: 'text/javascript', name: 'JavaScript' },
  { ext: 'mjs', mime: 'text/javascript', name: 'ES module' },
  { ext: 'json', mime: 'application/json', name: 'JSON' },
  { ext: 'xml', mime: 'application/xml', name: 'XML' },
  { ext: 'yaml', mime: 'application/yaml', name: 'YAML' },
  { ext: 'pdf', mime: 'application/pdf', name: 'PDF' },
  { ext: 'zip', mime: 'application/zip', name: 'ZIP archive' },
  { ext: 'gz', mime: 'application/gzip', name: 'Gzip' },
  { ext: 'tar', mime: 'application/x-tar', name: 'Tar archive' },
  { ext: '7z', mime: 'application/x-7z-compressed', name: '7-Zip' },
  { ext: 'wasm', mime: 'application/wasm', name: 'WebAssembly' },
  { ext: 'png', mime: 'image/png', name: 'PNG image' },
  { ext: 'jpg', mime: 'image/jpeg', name: 'JPEG image' },
  { ext: 'gif', mime: 'image/gif', name: 'GIF image' },
  { ext: 'webp', mime: 'image/webp', name: 'WebP image' },
  { ext: 'avif', mime: 'image/avif', name: 'AVIF image' },
  { ext: 'svg', mime: 'image/svg+xml', name: 'SVG image' },
  { ext: 'ico', mime: 'image/x-icon', name: 'Icon' },
  { ext: 'bmp', mime: 'image/bmp', name: 'Bitmap' },
  { ext: 'tiff', mime: 'image/tiff', name: 'TIFF image' },
  { ext: 'heic', mime: 'image/heic', name: 'HEIC image' },
  { ext: 'mp3', mime: 'audio/mpeg', name: 'MP3 audio' },
  { ext: 'wav', mime: 'audio/wav', name: 'WAV audio' },
  { ext: 'ogg', mime: 'audio/ogg', name: 'Ogg audio' },
  { ext: 'flac', mime: 'audio/flac', name: 'FLAC audio' },
  { ext: 'mp4', mime: 'video/mp4', name: 'MP4 video' },
  { ext: 'webm', mime: 'video/webm', name: 'WebM video' },
  { ext: 'mov', mime: 'video/quicktime', name: 'QuickTime' },
  { ext: 'avi', mime: 'video/x-msvideo', name: 'AVI video' },
  { ext: 'woff', mime: 'font/woff', name: 'WOFF font' },
  { ext: 'woff2', mime: 'font/woff2', name: 'WOFF2 font' },
  { ext: 'ttf', mime: 'font/ttf', name: 'TrueType font' },
  { ext: 'otf', mime: 'font/otf', name: 'OpenType font' },
  { ext: 'doc', mime: 'application/msword', name: 'Word (legacy)' },
  { ext: 'docx', mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', name: 'Word' },
  { ext: 'xls', mime: 'application/vnd.ms-excel', name: 'Excel (legacy)' },
  { ext: 'xlsx', mime: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', name: 'Excel' },
  { ext: 'ppt', mime: 'application/vnd.ms-powerpoint', name: 'PowerPoint (legacy)' },
  { ext: 'pptx', mime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation', name: 'PowerPoint' },
  { ext: 'bin', mime: 'application/octet-stream', name: 'Binary' },
];
