// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"pdf-image-to-pdf-v1","name":"Image to PDF","slug":"image-to-pdf","description":"Combine JPG, PNG & other images into a single PDF — one image per page, entirely in your browser.","category":"pdf","tags":["pdf","image","convert","jpg","png"],"keywords":["image to pdf","jpg to pdf","jpeg to pdf","png to pdf","photos to pdf","images to pdf","convert image to pdf","picture to pdf"],"icon":"FileImage","relatedTools":["merge-pdf","split-pdf","rotate-pdf","image-converter"],"packageImportPath":"@open-utility-tools/core/tools/pdf/image-to-pdf","webPath":"/tools/image-to-pdf/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
