// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"pdf-merge-v1","name":"Merge PDF","slug":"merge-pdf","description":"Combine multiple PDFs into one, reorder by drag — entirely in your browser.","category":"pdf","tags":["pdf","merge","combine","join"],"keywords":["merge pdf","combine pdf","join pdf","concatenate"],"icon":"Combine","relatedTools":["split-pdf","rotate-pdf","pdf-metadata"],"packageImportPath":"@open-utility-tools/core/tools/pdf/merge-pdf","webPath":"/tools/merge-pdf/","loadWasm":true} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
