// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"pdf-pdf-organize-pages-v1","name":"Organize PDF Pages","slug":"pdf-organize-pages","description":"Reorder, duplicate, delete and reverse PDF pages with drag and drop, or interleave front and back scans into one document.","category":"pdf","tags":["pdf","reorder","pages","interleave","duplex"],"keywords":["reorder pdf pages","rearrange pdf","organize pdf","reverse pdf pages","duplicate pdf page","interleave pdf","collate duplex scan","odd even pages","sort pdf pages"],"icon":"LayoutGrid","relatedTools":["merge-pdf","split-pdf","rotate-pdf"],"packageImportPath":"@open-utility-tools/core/tools/pdf/pdf-organize-pages","webPath":"/tools/pdf-organize-pages/","loadWasm":true} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
