// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"pdf-metadata-v1","name":"PDF Info & Metadata","slug":"pdf-metadata","description":"Inspect a PDF’s page count, version, and document metadata.","category":"pdf","tags":["pdf","metadata","info","inspect","properties"],"keywords":["pdf metadata","pdf info","page count","document properties","inspect pdf"],"icon":"FileSearch","relatedTools":["merge-pdf","split-pdf","rotate-pdf"],"packageImportPath":"@open-utility-tools/core/tools/pdf/pdf-metadata","webPath":"/tools/pdf-metadata/","loadWasm":true} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
