// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"pdf-pdf-protect-unlock-v1","name":"Protect & Unlock PDF","slug":"pdf-protect-unlock","description":"Encrypt a PDF with an open password and permission limits (AES-256 or AES-128), or remove a password you already know.","category":"pdf","tags":["pdf","password","encrypt","decrypt","permissions"],"keywords":["password protect pdf","encrypt pdf","unlock pdf","remove pdf password","decrypt pdf","restrict printing","pdf permissions","aes-256 pdf","secure pdf"],"icon":"FileLock","relatedTools":["pdf-metadata","merge-pdf"],"packageImportPath":"@open-utility-tools/core/tools/pdf/pdf-protect-unlock","webPath":"/tools/pdf-protect-unlock/","loadWasm":true} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
