// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"pdf-rotate-v1","name":"Rotate PDF","slug":"rotate-pdf","description":"Rotate all or selected pages of a PDF by 90, 180 or 270 degrees.","category":"pdf","tags":["pdf","rotate","orientation","pages"],"keywords":["rotate pdf","turn pages","orientation","landscape","portrait"],"icon":"RotateCw","relatedTools":["merge-pdf","split-pdf","pdf-metadata"],"packageImportPath":"@open-utility-tools/core/tools/pdf/rotate-pdf","webPath":"/tools/rotate-pdf/","loadWasm":true} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
