// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.

export const TOOL_CATEGORIES = ["image","pdf","data","convert","text","crypto","encoding","generators","web","time","math","color"] as const;

export type ToolCategory = (typeof TOOL_CATEGORIES)[number];

export interface ToolPackageEntry {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: ToolCategory;
  tags: readonly string[];
  keywords: readonly string[];
  icon: string;
  relatedTools: readonly string[];
  loadWasm?: boolean;
  hidden?: boolean;
  packageImportPath: string;
  webPath: string;
  coreImportPath?: string;
}
