#!/usr/bin/env bun
/**
 * Build-time registry codegen.
 *
 * Scans tools/<category>/<slug>/tool.config.ts, validates each config, and emits
 * lib/registry/registry.generated.ts — a manifest that statically imports each
 * tool's static metadata and provides a lazy () => import('./ui') per tool, so
 * the bundler produces one code-split chunk per tool. No central switch to edit:
 * adding a tool = dropping a folder.
 *
 * Validation enforced at build time:
 *   - unique slugs and ids
 *   - valid category
 *   - relatedTools reference existing slugs
 */
import { Glob } from 'bun';
import { join, relative, dirname } from 'node:path';

const ROOT = join(import.meta.dir, '..');
const TOOLS_DIR = join(ROOT, 'tools');
const OUT = join(ROOT, 'lib/registry/registry.generated.ts');

const VALID_CATEGORIES = new Set([
  'image',
  'pdf',
  'data',
  'convert',
  'text',
  'crypto',
  'encoding',
  'generators',
  'web',
  'time',
  'math',
  'color',
]);

interface RawConfig {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: string;
  tags?: string[];
  keywords?: string[];
  icon: string;
  relatedTools?: string[];
  loadWasm?: boolean;
  hidden?: boolean;
}

async function main() {
  const glob = new Glob('**/tool.config.ts');
  const files: string[] = [];
  for await (const f of glob.scan({ cwd: TOOLS_DIR })) {
    files.push(f);
  }
  files.sort();

  if (files.length === 0) {
    console.warn('⚠ gen-registry: no tools found under tools/ — emitting empty registry.');
  }

  const entries: { meta: RawConfig; importPath: string; dir: string }[] = [];

  for (const rel of files) {
    const abs = join(TOOLS_DIR, rel);
    const mod = await import(abs);
    const cfg = (mod.default ?? mod.config) as RawConfig | undefined;
    if (!cfg) {
      throw new Error(`tool config has no default export: ${rel}`);
    }
    // The ui module lives next to the config as ./ui(.tsx).
    const dir = dirname(rel);
    const importPath = `@/tools/${dir}/ui`;
    entries.push({ meta: cfg, importPath, dir });
  }

  // Validation
  const slugs = new Set<string>();
  const ids = new Set<string>();
  for (const { meta, dir } of entries) {
    for (const field of ['id', 'name', 'slug', 'description', 'category', 'icon'] as const) {
      if (!meta[field]) throw new Error(`tool ${dir}: missing required field "${field}"`);
    }
    if (slugs.has(meta.slug)) throw new Error(`duplicate slug: "${meta.slug}" (${dir})`);
    if (ids.has(meta.id)) throw new Error(`duplicate id: "${meta.id}" (${dir})`);
    if (!VALID_CATEGORIES.has(meta.category))
      throw new Error(`tool ${dir}: invalid category "${meta.category}"`);
    slugs.add(meta.slug);
    ids.add(meta.id);
  }
  for (const { meta, dir } of entries) {
    for (const r of meta.relatedTools ?? []) {
      if (!slugs.has(r))
        console.warn(`⚠ tool ${dir}: relatedTools references unknown slug "${r}"`);
    }
  }

  // Emit
  const sorted = entries.sort((a, b) => a.meta.slug.localeCompare(b.meta.slug));
  const lines: string[] = [];
  lines.push('// AUTO-GENERATED by scripts/gen-registry.ts — do not edit.');
  lines.push('// Run `bun run registry:gen` to regenerate.');
  lines.push('import type { ToolConfig, ToolMetaStatic } from "./types";');
  lines.push('');
  lines.push('export const TOOL_META: ToolMetaStatic[] = [');
  for (const { meta } of sorted) {
    lines.push('  ' + serializeMeta(meta) + ',');
  }
  lines.push('];');
  lines.push('');
  lines.push('/** Lazy component loaders, keyed by slug. Each is its own chunk. */');
  lines.push(
    'export const TOOL_COMPONENTS: Record<string, ToolConfig["component"]> = {'
  );
  for (const { meta, importPath } of sorted) {
    lines.push(`  ${JSON.stringify(meta.slug)}: () => import(${JSON.stringify(importPath)}),`);
  }
  lines.push('};');
  lines.push('');

  await Bun.write(OUT, lines.join('\n'));
  console.log(`✓ gen-registry: ${entries.length} tool(s) → ${relative(ROOT, OUT)}`);
}

function serializeMeta(m: RawConfig): string {
  const obj: Record<string, unknown> = {
    id: m.id,
    name: m.name,
    slug: m.slug,
    description: m.description,
    category: m.category,
    tags: m.tags ?? [],
    keywords: m.keywords ?? [],
    icon: m.icon,
    relatedTools: m.relatedTools ?? [],
  };
  if (m.loadWasm) obj.loadWasm = true;
  if (m.hidden) obj.hidden = true;
  return JSON.stringify(obj);
}

main().catch((e) => {
  console.error('✗ gen-registry failed:', e.message);
  process.exit(1);
});
