// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-accessible-text-color-v1","name":"Accessible Text Color Picker","slug":"accessible-text-color","description":"Decide whether black or white text is more readable on any background color.","category":"color","tags":["accessibility","contrast","wcag","color","text"],"keywords":["accessible text","black or white text","wcag contrast","readable","foreground color","a11y","luminance"],"icon":"Eye","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/accessible-text-color","webPath":"/tools/accessible-text-color/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
