// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-analogous-color-scheme-v1","name":"Analogous Color Scheme Generator","slug":"analogous-color-scheme","description":"Create harmonious neighboring-hue palettes around a base color.","category":"color","tags":["palette","analogous","harmony","hsl","scheme"],"keywords":["analogous","color scheme","palette generator","hue","harmony","neighboring colors"],"icon":"Spline","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/analogous-color-scheme","webPath":"/tools/analogous-color-scheme/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
