// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-color-invert-calculator-v1","name":"Color Invert Calculator","slug":"color-invert-calculator","description":"Compute RGB-inverted and luminance-inverted versions of a color.","category":"color","tags":["invert","color","css filter","dark mode","negative"],"keywords":["invert color","negative","css invert","flip lightness","complement","dark mode token"],"icon":"FlipHorizontal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/color-invert-calculator","webPath":"/tools/color-invert-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
