// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-color-sort-by-hue-v1","name":"Color List Sorter","slug":"color-sort-by-hue","description":"Sort a pasted list of colors by hue, lightness, saturation, or luminance.","category":"color","tags":["color","sort","hue","palette","luminance"],"keywords":["sort colors","hue sort","step sort","palette order","luminance","saturation","lightness"],"icon":"SortAsc","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/color-sort-by-hue","webPath":"/tools/color-sort-by-hue/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
