// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-color-format-allinone-v1","name":"Universal Color Format Translator","slug":"color-format-allinone","description":"Paste any CSS color and instantly see HEX, RGB, HSL, HSV, HWB, CMYK, LAB, LCH, and OKLCH.","category":"color","tags":["color","converter","css","hex","oklch"],"keywords":["rgb","hsl","hsv","hwb","cmyk","lab","lch","oklch","oklab","named color","convert color"],"icon":"Palette","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/color-format-allinone","webPath":"/tools/color-format-allinone/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
