// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-color-css-gradient-extract-stops-v1","name":"CSS Gradient Parser","slug":"color-css-gradient-extract-stops","description":"Parses a CSS linear/radial gradient string into structured angle, type, and color stops.","category":"color","tags":["gradient","css","parse","color","stops"],"keywords":["gradient","linear-gradient","radial-gradient","conic-gradient","color stops","parse css","extract"],"icon":"Blend","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/color-css-gradient-extract-stops","webPath":"/tools/color-css-gradient-extract-stops/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
