// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-color-scale-generator-v1","name":"Color Scale Generator","slug":"color-scale-generator","description":"Generate an evenly stepped color scale between two colors, choosing the number of steps and interpolation space.","category":"color","tags":["scale","interpolate","ramp"],"keywords":["color scale","steps","interpolate","ramp","between","gradient stops"],"icon":"Spline","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/color-scale-generator","webPath":"/tools/color-scale-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
