// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-color-luminance-calculator-v1","name":"Relative Luminance Calculator","slug":"color-luminance-calculator","description":"Compute WCAG relative luminance and perceived brightness for any color.","category":"color","tags":["luminance","brightness","wcag","perceived","luma"],"keywords":["relative luminance","perceived brightness","hsp","luma","light or dark","text color"],"icon":"Sun","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/color-luminance-calculator","webPath":"/tools/color-luminance-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
