// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-color-temperature-shift-v1","name":"Color Temperature Shift","slug":"color-temperature-shift","description":"Warm or cool a color by shifting it toward a target white point.","category":"color","tags":["color","temperature","warm","cool","kelvin"],"keywords":["white balance","warm color","cool color","color temperature","tint color"],"icon":"Thermometer","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/color-temperature-shift","webPath":"/tools/color-temperature-shift/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
