// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-color-harmony-v1","name":"Color Harmony / Palette Builder","slug":"color-harmony","description":"Build harmonious palettes from a base color using complementary, analogous, triadic, tetradic, split-complementary, and monochromatic schemes.","category":"color","tags":["palette","harmony","scheme","color"],"keywords":["palette","harmony","complementary","analogous","triadic","scheme"],"icon":"Palette","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/color-harmony","webPath":"/tools/color-harmony/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
