// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-converter-v1","name":"Color Converter","slug":"color-converter","description":"Convert colors between HEX, RGB, HSL, HSV, CMYK and OKLCH, with a live preview.","category":"color","tags":["color","hex","rgb","hsl","oklch","cmyk","convert"],"keywords":["color converter","hex to rgb","hsl","oklch","cmyk","hsv","picker"],"icon":"Palette","relatedTools":["contrast-checker","color-picker","gradient-generator"],"packageImportPath":"@open-utility-tools/core/tools/color/color-converter","webPath":"/tools/color-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
