// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-css-color-function-builder-v1","name":"CSS Color Function Builder","slug":"css-color-function-builder","description":"Interactively build modern CSS color() , rgb(), hsl(), lab(), lch(), oklch() strings.","category":"color","tags":["css","color","oklch","lab","builder"],"keywords":["css color function","oklch builder","lch","hwb","display-p3","modern css color"],"icon":"Braces","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/css-color-function-builder","webPath":"/tools/css-color-function-builder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
