// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-desaturate-color-v1","name":"Desaturate Color","slug":"desaturate-color","description":"Reduce a color's saturation by a percentage and preview the muted result.","category":"color","tags":["color","desaturate","saturation","muted","filter"],"keywords":["reduce saturation","mute color","grayscale partial","css saturate filter","tone down color"],"icon":"Droplet","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/desaturate-color","webPath":"/tools/desaturate-color/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
