// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-dominant-color-math-v1","name":"Dominant Color from Palette","slug":"dominant-color-math","description":"Compute the average and dominant color from a list of input colors.","category":"color","tags":["color","average","dominant","palette","kmeans"],"keywords":["average color","mean color","k-means colors","palette average","gamma correct average"],"icon":"PaintBucket","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/dominant-color-math","webPath":"/tools/dominant-color-math/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
