// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-gradient-generator-v1","name":"CSS Gradient Generator","slug":"gradient-generator","description":"Build linear, radial and conic CSS gradients with a live preview.","category":"color","tags":["gradient","css","linear","radial","conic"],"keywords":["gradient","css gradient","linear gradient","radial","conic","background"],"icon":"Blend","relatedTools":["color-converter","contrast-checker","color-picker"],"packageImportPath":"@open-utility-tools/core/tools/color/gradient-generator","webPath":"/tools/gradient-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
