// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-gradient-stops-generator-v1","name":"Gradient Stops Generator","slug":"gradient-stops-generator","description":"Compute evenly or eased intermediate color stops between two or more colors.","category":"color","tags":["color","gradient","stops","interpolation","css"],"keywords":["gradient","stops","oklch","hsl","easing","linear-gradient","interpolate"],"icon":"Spline","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/gradient-stops-generator","webPath":"/tools/gradient-stops-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
