// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-grayscale-converter-v1","name":"Grayscale Converter","slug":"grayscale-converter","description":"Convert any color to its grayscale equivalent using luminance, average, or desaturation methods, with side-by-side preview.","category":"color","tags":["grayscale","desaturate","luminance"],"keywords":["grayscale","greyscale","desaturate","luminance","black and white"],"icon":"Eye","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/grayscale-converter","webPath":"/tools/grayscale-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
