// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-hex-to-rgba-v1","name":"HEX to RGBA Converter","slug":"hex-to-rgba","description":"Convert HEX color codes (including 8-digit HEX with alpha) to rgba() and back, controlling opacity with a percentage value.","category":"color","tags":["hex","rgba","alpha"],"keywords":["hex","rgba","alpha","opacity","convert"],"icon":"Droplet","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/hex-to-rgba","webPath":"/tools/hex-to-rgba/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
