// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-image-color-extractor-v1","name":"Image Color Extractor","slug":"image-color-extractor","description":"Upload an image and extract its dominant colors and an automatic palette, ready to copy as HEX swatches.","category":"color","tags":["image","palette","swatch","color"],"keywords":["image","extract","dominant","palette","swatch","picker"],"icon":"Image","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/image-color-extractor","webPath":"/tools/image-color-extractor/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
