// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-lighten-darken-color-v1","name":"Lighten / Darken Color","slug":"lighten-darken-color","description":"Lighten or darken any color by a chosen percentage and get the adjusted color in HEX and RGB, with a before/after preview.","category":"color","tags":["lighten","darken","adjust","color"],"keywords":["lighten","darken","brighten","adjust","lightness"],"icon":"Contrast","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/lighten-darken-color","webPath":"/tools/lighten-darken-color/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
