// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-named-colors-v1","name":"CSS Named Colors","slug":"named-colors","description":"Browse and search all CSS named colors with their HEX/RGB values.","category":"color","tags":["colors","css","named","reference","hex"],"keywords":["css named colors","color names","web colors","hex reference","x11"],"icon":"Palette","relatedTools":["color-converter","color-harmony","color-shades"],"packageImportPath":"@open-utility-tools/core/tools/color/named-colors","webPath":"/tools/named-colors/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
