// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-nearest-pantone-name-v1","name":"Nearest Pantone-Style Name (Approx)","slug":"nearest-pantone-name","description":"Approximate the closest named swatch from an offline curated color-name dictionary.","category":"color","tags":["color-name","swatch","delta-e","approximate","palette"],"keywords":["pantone","color name","nearest swatch","lab","cie76","unofficial","dictionary"],"icon":"Stamp","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/nearest-pantone-name","webPath":"/tools/nearest-pantone-name/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
