// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-nearest-tailwind-color-v1","name":"Nearest Tailwind Color","slug":"nearest-tailwind-color","description":"Map any color to the closest Tailwind CSS palette token (e.g. blue-500).","category":"color","tags":["tailwind","palette","color","delta-e","css"],"keywords":["tailwind","nearest token","blue-500","palette","lab","cie76","shade","class"],"icon":"Wind","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/nearest-tailwind-color","webPath":"/tools/nearest-tailwind-color/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
