// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-oklch-converter-v1","name":"OKLCH Color Converter","slug":"oklch-converter","description":"Convert sRGB/HEX to OKLCH and OKLab and back, the modern perceptual model.","category":"color","tags":["color","oklch","oklab","css","converter","perceptual"],"keywords":["oklch","oklab","hex to oklch","oklch to hex","css color 4","perceptual color","ottosson"],"icon":"Orbit","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/oklch-converter","webPath":"/tools/oklch-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
