// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-palette-from-numbers-v1","name":"Palette from Numbers","slug":"palette-from-numbers","description":"Turn any number, ID, or seed string into a deterministic reproducible color palette.","category":"color","tags":["color","palette","seed","deterministic","generator"],"keywords":["seed","hash","avatar colors","tag colors","golden angle","reproducible","fnv"],"icon":"Hash","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/palette-from-numbers","webPath":"/tools/palette-from-numbers/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
