// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-random-palette-by-mood-v1","name":"Random Palette by Mood","slug":"random-palette-by-mood","description":"Generate a random color palette tuned to a chosen mood like calm, vibrant, or pastel.","category":"color","tags":["color","palette","random","mood","generator"],"keywords":["palette","mood","pastel","vibrant","muted","warm","cool","seed","css variables"],"icon":"Sparkles","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/random-palette-by-mood","webPath":"/tools/random-palette-by-mood/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
