// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-rgb-to-xyz-converter-v1","name":"RGB to CIE XYZ Converter","slug":"rgb-to-xyz-converter","description":"Convert sRGB to CIE 1931 XYZ tristimulus values (D65) and back.","category":"color","tags":["color","rgb","xyz","cie","converter"],"keywords":["rgb to xyz","xyz to rgb","cie 1931","tristimulus","d65","color space"],"icon":"Microscope","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/rgb-to-xyz-converter","webPath":"/tools/rgb-to-xyz-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
