// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-rgb-to-hex-v1","name":"RGB to HEX Converter","slug":"rgb-to-hex","description":"Convert rgb()/rgba() color values to HEX (and 8-digit HEX when alpha is present), accepting comma or space separated channels.","category":"color","tags":["rgb","hex","rgba","color"],"keywords":["rgb","hex","rgba","convert","color"],"icon":"ArrowLeftRight","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/rgb-to-hex","webPath":"/tools/rgb-to-hex/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
