// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-rgb-to-hsv-converter-v1","name":"RGB to HSV Converter","slug":"rgb-to-hsv-converter","description":"Convert between sRGB and HSV/HSB color models with a preview swatch.","category":"color","tags":["color","rgb","hsv","hsb","converter"],"keywords":["rgb to hsv","hsv to rgb","hsb","hue saturation value","brightness","color model"],"icon":"Droplet","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/rgb-to-hsv-converter","webPath":"/tools/rgb-to-hsv-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
