// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-rgb-to-hwb-converter-v1","name":"RGB to HWB Converter","slug":"rgb-to-hwb-converter","description":"Convert sRGB to CSS HWB (hue, whiteness, blackness) and back.","category":"color","tags":["color","rgb","hwb","css","converter"],"keywords":["rgb to hwb","hwb to rgb","hue whiteness blackness","css color 4","hwb()"],"icon":"Blend","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/rgb-to-hwb-converter","webPath":"/tools/rgb-to-hwb-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
