// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-split-complementary-scheme-v1","name":"Split-Complementary Scheme Generator","slug":"split-complementary-scheme","description":"Generate a base plus the two colors adjacent to its complement.","category":"color","tags":["color","scheme","complementary","harmony","palette"],"keywords":["split complementary","color wheel","complement","accent","harmony","hsl"],"icon":"GitCompare","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/split-complementary-scheme","webPath":"/tools/split-complementary-scheme/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
