// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-tailwind-colors-v1","name":"Tailwind Color Finder","slug":"tailwind-colors","description":"Find the closest Tailwind CSS color name and shade for any HEX/RGB color, and look up the exact HEX of any Tailwind color token.","category":"color","tags":["tailwind","color","nearest","hex"],"keywords":["tailwind","nearest","color","shade","closest","hex"],"icon":"Tags","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/tailwind-colors","webPath":"/tools/tailwind-colors/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
