// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-triadic-color-scheme-v1","name":"Triadic Color Scheme Generator","slug":"triadic-color-scheme","description":"Build a balanced three-color triadic palette from one base hue.","category":"color","tags":["color","palette","triadic","scheme","harmony"],"keywords":["triadic","three color","palette","color wheel","hsl","css variables","ui colors"],"icon":"Triangle","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/triadic-color-scheme","webPath":"/tools/triadic-color-scheme/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
