// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"color-wcag-contrast-pair-finder-v1","name":"WCAG Contrast Pair Finder","slug":"wcag-contrast-pair-finder","description":"Adjust a foreground color until it meets a target WCAG contrast on a fixed background.","category":"color","tags":["wcag","contrast","accessibility","a11y","color"],"keywords":["contrast ratio","aa","aaa","accessible","readability","lightness","fix contrast"],"icon":"Contrast","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/color/wcag-contrast-pair-finder","webPath":"/tools/wcag-contrast-pair-finder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
