// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-bic-swift-test-generator-v1","name":"BIC / SWIFT Code Test Generator","slug":"bic-swift-test-generator","description":"Generate structurally valid test BIC/SWIFT codes (8 or 11 chars) with bank, country, location, branch parts.","category":"generators","tags":["bic","swift","iso-9362","banking","test-data","fake"],"keywords":["bic generator","swift code","iso 9362","bank identifier code","test bic","mock banking data"],"icon":"Landmark","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/bic-swift-test-generator","webPath":"/tools/bic-swift-test-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
