// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-changelog-generator-v1","name":"CHANGELOG Generator (Keep a Changelog)","slug":"changelog-generator","description":"Scaffold a Keep-a-Changelog / SemVer CHANGELOG.md with version sections and Added/Changed/Fixed groups.","category":"generators","tags":["changelog","keep-a-changelog","semver","markdown","release"],"keywords":["changelog","keep a changelog","release notes","semver","changelog.md","version history"],"icon":"FileStack","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/changelog-generator","webPath":"/tools/changelog-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
