// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-conventional-commit-generator-v1","name":"Conventional Commit Message Builder","slug":"conventional-commit-generator","description":"Build a Conventional Commits message from type, scope, description, body, breaking change, and footers.","category":"generators","tags":["conventional-commits","git","commit","semver","changelog"],"keywords":["conventional commits","commit message","git commit","breaking change","gitmoji","commitlint"],"icon":"GitCompare","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/conventional-commit-generator","webPath":"/tools/conventional-commit-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
