// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-crontab-recipe-generator-v1","name":"Crontab Recipe Generator","slug":"crontab-recipe-generator","description":"Generate a full crontab file with multiple jobs, schedule presets, env lines, and human comments.","category":"generators","tags":["cron","crontab","scheduler","linux","devops"],"keywords":["crontab","cron file","cron jobs","scheduler","cron expression","cronjob"],"icon":"CalendarClock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/crontab-recipe-generator","webPath":"/tools/crontab-recipe-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
