// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-dice-v1","name":"Dice & Coin Roller","slug":"dice-roller","description":"Roll dice (d4–d100, multiple dice) and flip coins with fair randomness.","category":"generators","tags":["dice","coin","random","rng","roll"],"keywords":["dice roller","coin flip","d20","random number","rng","tabletop"],"icon":"Dice5","relatedTools":["random-string","password-generator","uuid-generator"],"packageImportPath":"@open-utility-tools/core/tools/generators/dice-roller","webPath":"/tools/dice-roller/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
