// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-editorconfig-generator-v1","name":".editorconfig Generator","slug":"editorconfig-generator","description":"Generate an .editorconfig from options: indent style/size, charset, EOL, trailing whitespace, per-glob rules.","category":"generators","tags":["editorconfig","config","indent","formatting","scaffold"],"keywords":["editorconfig","indent_style","indent_size","charset","end_of_line","trailing whitespace","final newline","glob","ini"],"icon":"FileCog","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/editorconfig-generator","webPath":"/tools/editorconfig-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
