// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-env-example-generator-v1","name":".env.example Generator","slug":"env-example-generator","description":"Turn a list of env var names/values into a redacted .env.example with comments and grouping.","category":"generators","tags":["env","dotenv","config","secrets","redact"],"keywords":["env.example","dotenv",".env","environment variables","redact","placeholder","secrets","template"],"icon":"FileKey","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/env-example-generator","webPath":"/tools/env-example-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
