// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-fake-ipv4-ipv6-generator-v1","name":"Random IP Address Generator","slug":"fake-ipv4-ipv6-generator","description":"Generate random IPv4 and IPv6 addresses, optionally restricted to private or public ranges.","category":"generators","tags":["ip","ipv4","ipv6","network","random"],"keywords":["ip address","random ip","cidr","rfc1918","test data","fake ip","subnet"],"icon":"Network","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/fake-ipv4-ipv6-generator","webPath":"/tools/fake-ipv4-ipv6-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
