// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generators-systemd-service-unit-v1","name":"systemd Service Unit Generator","slug":"generators-systemd-service-unit","description":"Generate a systemd .service unit file from descriptive form inputs.","category":"generators","tags":["systemd","service","linux","unit","daemon"],"keywords":["systemd","service unit",".service","ExecStart","daemon","linux","systemctl"],"icon":"FileCog","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generators-systemd-service-unit","webPath":"/tools/generators-systemd-service-unit/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
