// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-slug-v1","name":"Slug Generator","slug":"generate-slug","description":"Turn each line of text into clean URL slugs with options for separator, lowercasing, accent stripping, and max length, processing many titles at once.","category":"generators","tags":["slug","url","seo"],"keywords":["slug","url","permalink","seo","kebab","friendly"],"icon":"Link2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-slug","webPath":"/tools/generate-slug/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
