// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generators-makefile-scaffold-v1","name":"Makefile Scaffold Generator","slug":"generators-makefile-scaffold","description":"Generates a Makefile with .PHONY targets, variables, and help target from a list of tasks.","category":"generators","tags":["makefile","make","build","scaffold","devops"],"keywords":["makefile","make targets","phony","help target","build automation","variables"],"icon":"Hammer","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generators-makefile-scaffold","webPath":"/tools/generators-makefile-scaffold/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
