// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-placeholder-image-v1","name":"Placeholder Image Generator","slug":"generate-placeholder-image","description":"Generate downloadable placeholder images at a chosen size, background/text color, and label text, drawn on a canvas as a data URL for mockups.","category":"generators","tags":["placeholder","image","generator"],"keywords":["placeholder","image","mockup","canvas","dummy","thumbnail"],"icon":"FileImage","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-placeholder-image","webPath":"/tools/generate-placeholder-image/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
