// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-cron-expression-v1","name":"Cron Expression Builder","slug":"generate-cron-expression","description":"Build a cron expression from human-friendly schedule controls (minute, hour, day, month, weekday) and see a plain-English description of when it runs.","category":"generators","tags":["cron","schedule","generator"],"keywords":["cron","schedule","crontab","builder","expression","job"],"icon":"CalendarClock","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-cron-expression","webPath":"/tools/generate-cron-expression/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
