// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-mac-address-v1","name":"MAC Address Generator","slug":"generate-mac-address","description":"Generate random MAC addresses with selectable separator (colon, hyphen, dot), case, and locally-administered/unicast bit control for network testing.","category":"generators","tags":["mac","address","network"],"keywords":["mac","address","network","ethernet","hardware","random"],"icon":"Network","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-mac-address","webPath":"/tools/generate-mac-address/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
