// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-nanoid-v1","name":"NanoID Generator","slug":"generate-nanoid","description":"Generate compact, URL-safe NanoIDs with configurable length and alphabet, a popular smaller alternative to UUIDs for keys and short links.","category":"generators","tags":["nanoid","id","short","url-safe","unique","key"],"keywords":["nanoid","id","short","url-safe","unique","key"],"icon":"KeyRound","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-nanoid","webPath":"/tools/generate-nanoid/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
