// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generators-svg-qr-style-placeholder-v1","name":"Random Identicon (SVG)","slug":"generators-svg-qr-style-placeholder","description":"Generates a deterministic symmetric pixel identicon SVG from a seed string.","category":"generators","tags":["identicon","svg","avatar","placeholder","deterministic"],"keywords":["identicon","avatar","svg","gravatar","pixel art","seed","github avatar"],"icon":"Grid3x3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generators-svg-qr-style-placeholder","webPath":"/tools/generators-svg-qr-style-placeholder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
