// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-random-date-v1","name":"Random Date Generator","slug":"generate-random-date","description":"Generate random dates and times between a start and end bound, with chosen output format (ISO, locale, Unix timestamp) and quantity for seeding data.","category":"generators","tags":["date","random","generator"],"keywords":["date","random","time","timestamp","iso","seed"],"icon":"Calendar","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-random-date","webPath":"/tools/generate-random-date/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
