// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-random-string-v1","name":"Random String Generator","slug":"generate-random-string","description":"Generate random strings/tokens with toggleable character sets (lowercase, uppercase, digits, symbols), custom length, and quantity for API keys, secrets, and test data.","category":"generators","tags":["random","string","token"],"keywords":["random","string","token","secret","key","alphanumeric"],"icon":"Shuffle","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-random-string","webPath":"/tools/generate-random-string/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
