// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generators-ssh-config-builder-v1","name":"SSH Config Block Builder","slug":"generators-ssh-config-builder","description":"Build a well-formed ~/.ssh/config Host block from form fields.","category":"generators","tags":["ssh","config","devops","host","proxyjump"],"keywords":["ssh config","host block","identityfile","proxyjump","forwardagent","ssh aliases"],"icon":"ServerCog","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generators-ssh-config-builder","webPath":"/tools/generators-ssh-config-builder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
