// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-barcode-v1","name":"Barcode Generator","slug":"generate-barcode","description":"Generate Code 39 and EAN-13 barcodes from input text/digits, rendered to a downloadable SVG/PNG with adjustable bar width and height.","category":"generators","tags":["barcode","generator","image"],"keywords":["barcode","code39","ean13","scan","product","svg"],"icon":"ScanLine","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-barcode","webPath":"/tools/generate-barcode/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
