// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-random-number-v1","name":"Random Number Generator","slug":"generate-random-number","description":"Generate cryptographically random integers or decimals within a min/max range, with options for quantity, uniqueness, and number of decimal places.","category":"generators","tags":["random","number","rng"],"keywords":["random","number","integer","rng","range","dice"],"icon":"Dice5","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-random-number","webPath":"/tools/generate-random-number/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
