// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-pin-v1","name":"PIN Code Generator","slug":"generate-pin","description":"Generate random numeric PIN codes of a chosen length (e.g. 4/6/8 digits) in bulk, with an option to avoid trivial sequences and repeats.","category":"generators","tags":["pin","code","numeric"],"keywords":["pin","code","numeric","otp","random","digits"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-pin","webPath":"/tools/generate-pin/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
