// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-credit-card-v1","name":"Credit Card Number Generator","slug":"generate-credit-card","description":"Generate Luhn-valid fake test card numbers by brand (Visa, Mastercard, Amex, Discover) with optional expiry and CVV, for payment-form testing only.","category":"generators","tags":["credit card","luhn","test"],"keywords":["credit card","luhn","test","fake","visa","mastercard"],"icon":"CreditCard","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-credit-card","webPath":"/tools/generate-credit-card/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
