// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generate-iban-v1","name":"IBAN Generator","slug":"generate-iban","description":"Generate valid-format test IBANs per country with correct length and ISO 7064 mod-97 check digits, useful for banking and form validation testing.","category":"generators","tags":["iban","bank","test"],"keywords":["iban","bank","mod-97","test","account","validation"],"icon":"Banknote","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generate-iban","webPath":"/tools/generate-iban/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
