// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-generators-gitlab-ci-yaml-v1","name":"GitLab CI Pipeline Generator","slug":"generators-gitlab-ci-yaml","description":"Builds a .gitlab-ci.yml from selected stages, jobs, images, and cache settings.","category":"generators","tags":["gitlab","ci","yaml","pipeline","devops"],"keywords":["gitlab-ci","pipeline","ci/cd","yaml","stages","jobs","cache"],"icon":"FileCog","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/generators-gitlab-ci-yaml","webPath":"/tools/generators-gitlab-ci-yaml/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
