// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-ics-event-generator-v1","name":"Calendar Event (.ics) Generator","slug":"ics-event-generator","description":"Build RFC 5545 iCalendar (.ics) files with time zones, recurrence, reminders and attendees, and get Google, Outlook and Yahoo add-to-calendar links.","category":"generators","tags":["ics","icalendar","calendar","event","rrule","recurrence"],"keywords":["ics generator","ical","icalendar","add to calendar","calendar invite","rrule","vevent","valarm","vtimezone","google calendar link","outlook calendar link","recurring event"],"icon":"CalendarClock","relatedTools":["recurring-event-dates","timezone-converter","vcard-generator"],"packageImportPath":"@open-utility-tools/core/tools/generators/ics-event-generator","webPath":"/tools/ics-event-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
