// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-ksuid-generator-v1","name":"KSUID Generator","slug":"ksuid-generator","description":"Generate K-Sortable Unique Identifiers as 27-character Base62 strings.","category":"generators","tags":["ksuid","id","sortable","base62","unique"],"keywords":["ksuid","k-sortable","unique id","base62","segment","identifier","ulid alternative"],"icon":"KeyRound","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/ksuid-generator","webPath":"/tools/ksuid-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
