// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-lorem-bytes-generator-v1","name":"Lorem Ipsum by Byte Size","slug":"lorem-bytes-generator","description":"Generate filler Lorem Ipsum text trimmed to an exact target byte or character size.","category":"generators","tags":["lorem","ipsum","bytes","filler","placeholder"],"keywords":["lorem ipsum","byte size","fill bytes","dummy text","placeholder text","exact size","padding"],"icon":"FileText","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/lorem-bytes-generator","webPath":"/tools/lorem-bytes-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
