// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-lottery-number-generator-v1","name":"Lottery Number Generator","slug":"lottery-number-generator","description":"Generate lottery quick-pick numbers for common formats or a custom number pool.","category":"generators","tags":["lottery","random","quick-pick","numbers","powerball"],"keywords":["lotto","powerball","mega millions","euromillions","quick pick","draw","random numbers"],"icon":"Ticket","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/lottery-number-generator","webPath":"/tools/lottery-number-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
