// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-memorable-password-generator-v1","name":"Memorable Password Generator","slug":"memorable-password-generator","description":"Build easy-to-type memorable passwords from word groups with separators and number/symbol injection.","category":"generators","tags":["password","memorable","words","entropy","security"],"keywords":["memorable password","word password","xkcd","correct horse","passphrase","secure password"],"icon":"Brush","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/memorable-password-generator","webPath":"/tools/memorable-password-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
