// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-mnemonic-pin-generator-v1","name":"Mnemonic PIN Generator","slug":"mnemonic-pin-generator","description":"Generate numeric PINs alongside a word mnemonic to help you remember each digit.","category":"generators","tags":["pin","mnemonic","memory","numbers","security"],"keywords":["pin code","memorable pin","numeric password","digit words","mnemonic","remember pin"],"icon":"Lightbulb","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/mnemonic-pin-generator","webPath":"/tools/mnemonic-pin-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
