// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-mock-json-v1","name":"Mock Data Generator","slug":"mock-data","description":"Generate an array of realistic fake records (names, emails, dates) as JSON.","category":"generators","tags":["fake data","mock","test data","json","seed"],"keywords":["fake data","mock data","test data","faker","seed","json generator"],"icon":"Database","relatedTools":["uuid-generator","lorem-ipsum","json-formatter"],"packageImportPath":"@open-utility-tools/core/tools/generators/mock-data","webPath":"/tools/mock-data/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
