// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-nanoid-custom-alphabet-v1","name":"NanoID Custom Alphabet Generator","slug":"nanoid-custom-alphabet","description":"Generate NanoIDs from your own alphabet with an unbiased rejection-sampling algorithm.","category":"generators","tags":["nanoid","id","random","alphabet","unique"],"keywords":["nanoid","custom alphabet","unique id","short id","rejection sampling","url safe id"],"icon":"Type","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/nanoid-custom-alphabet","webPath":"/tools/nanoid-custom-alphabet/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
