// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-otp-secret-generator-v1","name":"OTP Secret Generator","slug":"otp-secret-generator","description":"Generate Base32 TOTP/HOTP shared secrets and a matching otpauth:// URI.","category":"generators","tags":["otp","totp","base32","secret","2fa"],"keywords":["otp secret","totp","hotp","2fa","authenticator","base32 secret","otpauth uri","mfa"],"icon":"ShieldCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/otp-secret-generator","webPath":"/tools/otp-secret-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
