// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-playing-card-dealer-v1","name":"Playing Card Dealer","slug":"playing-card-dealer","description":"Shuffle a standard deck and deal random cards or hands.","category":"generators","tags":["cards","deck","shuffle","random","game"],"keywords":["playing cards","deal","poker","deck","shuffle","fisher-yates","joker"],"icon":"Gamepad2","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/playing-card-dealer","webPath":"/tools/playing-card-dealer/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
