// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-qr-code-generator-v1","name":"QR Code Generator","slug":"qr-code-generator","description":"Create QR codes for URLs, text, Wi-Fi, email, phone, SMS, contacts and locations with styling, a centre logo, and PNG or SVG download.","category":"generators","tags":["qr","qr code","wifi","vcard","svg","png"],"keywords":["qr code maker","qr generator","create qr code","wifi qr code","vcard qr","qr code with logo","qr code svg","qr code png","url to qr","error correction level","reed solomon","mailto qr","sms qr","geo qr"],"icon":"QrCode","relatedTools":["wifi-qr-payload-generator","vcard-qr-payload-generator","generate-barcode"],"packageImportPath":"@open-utility-tools/core/tools/generators/qr-code-generator","webPath":"/tools/qr-code-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
