// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-random-choice-picker-v1","name":"Random Choice Picker","slug":"random-choice-picker","description":"Pick one or several random options from a list of choices, with or without replacement.","category":"generators","tags":["random","picker","choice","shuffle","decision"],"keywords":["random picker","pick one","choose","raffle","decision maker","shuffle list"],"icon":"Pointer","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/random-choice-picker","webPath":"/tools/random-choice-picker/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
