// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-random-hex-color-palette-v1","name":"Random Color Palette Generator","slug":"random-hex-color-palette","description":"Generate harmonious random color palettes in HEX/RGB/HSL using HSL-based schemes.","category":"generators","tags":["color","palette","hsl","scheme","random","design"],"keywords":["color palette","analogous","complementary","triadic","monochromatic","tetradic","hex rgb hsl"],"icon":"Palette","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/random-hex-color-palette","webPath":"/tools/random-hex-color-palette/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
