// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-uuid-namespace-v1","name":"Random String Generator","slug":"random-string","description":"Generate random strings from a chosen alphabet (hex, alphanumeric, custom).","category":"generators","tags":["random","string","token","hex","alphanumeric"],"keywords":["random string","token","random hex","api key","secret"],"icon":"Dice5","relatedTools":["password-generator","uuid-generator","nanoid-generator"],"packageImportPath":"@open-utility-tools/core/tools/generators/random-string","webPath":"/tools/random-string/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
