// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-readme-scaffold-generator-v1","name":"README.md Scaffold Generator","slug":"readme-scaffold-generator","description":"Build a structured README.md from a form: title, badges, install, usage, features, license sections.","category":"generators","tags":["readme","markdown","documentation","scaffold","generator"],"keywords":["readme generator","markdown readme","project docs","shields badges","table of contents","open source"],"icon":"FileText","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/readme-scaffold-generator","webPath":"/tools/readme-scaffold-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
