// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-robots-txt-v1","name":"robots.txt Generator","slug":"robots-txt","description":"Build a robots.txt with allow/disallow rules and a sitemap line.","category":"generators","tags":["robots.txt","seo","crawler","sitemap"],"keywords":["robots.txt","robots generator","crawler rules","disallow","sitemap"],"icon":"FileCog","relatedTools":["meta-tags","gitignore-generator","slugify"],"packageImportPath":"@open-utility-tools/core/tools/generators/robots-txt","webPath":"/tools/robots-txt/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
