// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-ssn-format-test-generator-v1","name":"SSN-Format Test Number Generator","slug":"ssn-format-test-generator","description":"Generate format-valid but non-issuable US SSN test numbers (e.g. 900-xx-xxxx, 666 area) for QA.","category":"generators","tags":["ssn","test-data","qa","placeholder","fake","us"],"keywords":["fake ssn","test ssn","social security number","never issued","qa data","itin","placeholder"],"icon":"FileBadge","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/ssn-format-test-generator","webPath":"/tools/ssn-format-test-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
