// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-team-shuffler-v1","name":"Team / Group Splitter","slug":"team-shuffler","description":"Randomly split a list of names into balanced teams or fixed-size groups.","category":"generators","tags":["teams","groups","shuffle","random","split"],"keywords":["team generator","group maker","random teams","pick teams","divide groups","fisher-yates"],"icon":"Users","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/team-shuffler","webPath":"/tools/team-shuffler/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
