// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-ulid-v1","name":"ULID Generator","slug":"ulid-generator","description":"Generate lexicographically-sortable ULIDs in bulk, locally.","category":"generators","tags":["ulid","id","sortable","unique"],"keywords":["ulid","sortable id","unique id","identifier"],"icon":"Fingerprint","relatedTools":["uuid-generator","nanoid-generator","password-generator"],"packageImportPath":"@open-utility-tools/core/tools/generators/ulid-generator","webPath":"/tools/ulid-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
