// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-uuid-v7-generator-v1","name":"UUID v7 Generator","slug":"uuid-v7-generator","description":"Generate time-ordered, sortable UUID v7 identifiers using the current timestamp.","category":"generators","tags":["uuid","v7","sortable","timestamp","rfc9562"],"keywords":["uuid v7","time ordered uuid","sortable uuid","unix timestamp uuid","monotonic uuid"],"icon":"Fingerprint","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/uuid-v7-generator","webPath":"/tools/uuid-v7-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
