// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"generators-uuid-namespace-builder-v1","name":"UUID Namespace Builder","slug":"uuid-namespace-builder","description":"Build and manage RFC 4122 namespace UUIDs and derive v5/v3 names beneath a custom namespace, offline.","category":"generators","tags":["uuid","namespace","v5","v3","deterministic"],"keywords":["namespace uuid","uuid v5","uuid v3","sha-1 uuid","md5 uuid","derive uuid","rfc 4122"],"icon":"Fingerprint","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/generators/uuid-namespace-builder","webPath":"/tools/uuid-namespace-builder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
