// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-csv-merge-columns-v1","name":"CSV Merge Columns","slug":"csv-merge-columns","description":"Concatenate two or more CSV columns into a single column using a chosen separator and template.","category":"data","tags":["csv","merge","columns","concatenate","template"],"keywords":["csv merge","combine columns","concatenate csv","join columns","template column"],"icon":"Combine","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/csv-merge-columns","webPath":"/tools/csv-merge-columns/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
