// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-csv-column-math-v1","name":"CSV Column Math","slug":"csv-column-math","description":"Add a computed column to a CSV using an arithmetic expression over existing numeric columns, evaluated safely without eval.","category":"data","tags":["csv","formula","calculate","column","expression"],"keywords":["csv formula","computed column","arithmetic","spreadsheet formula","derive column","price times quantity","expression evaluator"],"icon":"SquareFunction","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/csv-column-math","webPath":"/tools/csv-column-math/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
