// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-csv-transpose-v1","name":"CSV Transpose","slug":"csv-transpose","description":"Swap rows and columns of a CSV so the first column becomes the header row and vice versa.","category":"data","tags":["csv","transpose","rows","columns"],"keywords":["csv","tsv","transpose","pivot","rotate","flip","rows","columns","matrix"],"icon":"ArrowDownUp","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/csv-transpose","webPath":"/tools/csv-transpose/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
