// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-csv-column-stats-v1","name":"CSV Column Statistics","slug":"csv-column-stats","description":"Compute per-column statistics (type, count, nulls, distinct, min/max, mean, median, std-dev) for every column in a CSV.","category":"data","tags":["csv","statistics","profiling","summary","analytics"],"keywords":["csv stats","column profiling","describe","data summary","mean median","standard deviation","distinct count","data quality"],"icon":"ChartBar","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/csv-column-stats","webPath":"/tools/csv-column-stats/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
