// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-csv-viewer-v1","name":"CSV Viewer","slug":"csv-viewer","description":"Paste CSV and view it as a sortable, searchable table.","category":"data","tags":["csv","viewer","table","tsv","spreadsheet"],"keywords":["csv viewer","view csv","csv table","tsv","parse csv","spreadsheet"],"icon":"Table","relatedTools":["csv-to-json","json-to-csv","json-formatter"],"packageImportPath":"@open-utility-tools/core/tools/data/csv-viewer","webPath":"/tools/csv-viewer/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
