// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-csv-to-fixed-width-v1","name":"CSV to Fixed-Width","slug":"csv-to-fixed-width","description":"Convert CSV into fixed-width / column-aligned text with per-column widths and alignment.","category":"data","tags":["csv","fixed-width","align","columns","table"],"keywords":["fixed width","column aligned","ascii table","monospace table","padded columns","flat file"],"icon":"AlignJustify","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/csv-to-fixed-width","webPath":"/tools/csv-to-fixed-width/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
