// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-csv-sort-v1","name":"CSV Sorter","slug":"csv-sort","description":"Sort CSV rows by a chosen column with numeric/text mode and ascending or descending order.","category":"data","tags":["csv","sort"],"keywords":["csv","sort","rows","order","column"],"icon":"SortAsc","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/csv-sort","webPath":"/tools/csv-sort/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
