// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-csv-to-json-v1","name":"CSV to JSON","slug":"csv-to-json","description":"Convert CSV (with header row) into a JSON array of objects.","category":"data","tags":["csv","json","convert","parse","import"],"keywords":["csv to json","parse csv","import","array of objects"],"icon":"Braces","relatedTools":["json-to-csv","json-formatter","csv-viewer"],"packageImportPath":"@open-utility-tools/core/tools/data/csv-to-json","webPath":"/tools/csv-to-json/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
