// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-csv-to-sql-v1","name":"CSV to SQL INSERT","slug":"csv-to-sql","description":"Generate SQL INSERT statements from CSV with a configurable table name and quoting.","category":"data","tags":["csv","sql"],"keywords":["csv","sql","insert","database","generate"],"icon":"Database","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/csv-to-sql","webPath":"/tools/csv-to-sql/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
