// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-data-tsv-to-markdown-table-v1","name":"TSV to Markdown Table","slug":"data-tsv-to-markdown-table","description":"Convert tab-separated values into a GitHub-flavored Markdown table.","category":"data","tags":["tsv","markdown","table","convert","gfm"],"keywords":["tab separated to markdown","spreadsheet to markdown","markdown table generator","github table","excel to markdown"],"icon":"Table","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/data-tsv-to-markdown-table","webPath":"/tools/data-tsv-to-markdown-table/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
