// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-data-jsonl-deduplicate-v1","name":"JSONL Record Deduplicator","slug":"data-jsonl-deduplicate","description":"Remove duplicate JSON objects from JSON Lines input, optionally keyed by selected fields.","category":"data","tags":["jsonl","dedupe","ndjson","unique"],"keywords":["jsonl","ndjson","dedupe","duplicate","unique","json lines","records","distinct"],"icon":"Filter","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/data-jsonl-deduplicate","webPath":"/tools/data-jsonl-deduplicate/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
