// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-data-json-array-flatten-nested-v1","name":"JSON Nested Array Flattener","slug":"data-json-array-flatten-nested","description":"Flattens deeply nested JSON arrays into a single flat array to a chosen depth.","category":"data","tags":["json","array","flatten","nested"],"keywords":["json","array","flatten","nested","depth","flat","merge"],"icon":"Layers","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/data-json-array-flatten-nested","webPath":"/tools/data-json-array-flatten-nested/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
