// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-data-jsonl-validate-lint-v1","name":"JSON Lines Validator","slug":"data-jsonl-validate-lint","description":"Validates each line of an NDJSON/JSONL file as standalone JSON and reports line-level errors.","category":"data","tags":["jsonl","ndjson","validate","lint","json"],"keywords":["json lines","newline delimited json","ndjson validator","jsonl lint","per line json","streaming json"],"icon":"FileJson","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/data-jsonl-validate-lint","webPath":"/tools/data-jsonl-validate-lint/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
