// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-data-tsv-column-reorder-v1","name":"Delimited Column Reorder","slug":"data-tsv-column-reorder","description":"Reorders, drops, or duplicates columns in CSV/TSV data by index or header name.","category":"data","tags":["csv","tsv","columns","reorder","delimited"],"keywords":["rearrange columns","select columns","drop column","duplicate column","column order","csv projection"],"icon":"Columns3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/data-tsv-column-reorder","webPath":"/tools/data-tsv-column-reorder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
