// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-data-json-array-chunk-v1","name":"JSON Array Chunker","slug":"data-json-array-chunk","description":"Split a large JSON array into fixed-size chunks of smaller arrays.","category":"data","tags":["json","array","chunk","split"],"keywords":["json","array","chunk","split","batch","partition","paginate"],"icon":"SplitSquareHorizontal","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/data-json-array-chunk","webPath":"/tools/data-json-array-chunk/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
