// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-ndjson-v1","name":"JSON to NDJSON / JSON Lines","slug":"json-to-ndjson","description":"Convert between a JSON array and newline-delimited JSON (NDJSON / JSON Lines).","category":"data","tags":["json","ndjson","convert"],"keywords":["ndjson","jsonl","json lines","array","convert"],"icon":"List","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-ndjson","webPath":"/tools/json-to-ndjson/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
