// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-stats-summary-v1","name":"JSON Structure Stats","slug":"json-stats-summary","description":"Summarize a JSON document's structure, depth, and type counts.","category":"data","tags":["json","stats","analysis","structure","depth"],"keywords":["json stats","json analyzer","type counts","json depth","key frequency","json schema skeleton"],"icon":"ChartBar","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-stats-summary","webPath":"/tools/json-stats-summary/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
