// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-dart-v1","name":"JSON to Dart Class","slug":"json-to-dart","description":"Generate Dart classes with fromJson/toJson from a JSON sample.","category":"data","tags":["json","dart","flutter","codegen","class"],"keywords":["json to dart","flutter model","fromjson","tojson","data class","serialization"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-dart","webPath":"/tools/json-to-dart/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
