// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-csv-headers-v1","name":"JSON Keys to CSV Header","slug":"json-to-csv-headers","description":"Derive a unified CSV/flat header row from JSON array of objects.","category":"data","tags":["json","csv","headers","keys","flatten"],"keywords":["json keys","csv header","union keys","field map","header row","sparse keys"],"icon":"TableProperties","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-csv-headers","webPath":"/tools/json-to-csv-headers/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
