// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-escape-v1","name":"JSON String Escape / Unescape","slug":"json-escape","description":"Escape text into a JSON string literal, or unescape one back to raw text.","category":"data","tags":["json","escape","unescape","string","stringify"],"keywords":["json escape","unescape","stringify","json string","quote"],"icon":"Quote","relatedTools":["json-formatter","json-minify","html-entities"],"packageImportPath":"@open-utility-tools/core/tools/data/json-escape","webPath":"/tools/json-escape/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
