// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-jsdoc-typedef-v1","name":"JSON to JSDoc Typedef","slug":"json-to-jsdoc-typedef","description":"Generate JSDoc @typedef comments from a JSON sample.","category":"data","tags":["json","jsdoc","typedef","javascript","codegen"],"keywords":["json to jsdoc","typedef","jsdoc property","javascript types","codegen"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-jsdoc-typedef","webPath":"/tools/json-to-jsdoc-typedef/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
