// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-graphql-sdl-v1","name":"JSON to GraphQL Type","slug":"json-to-graphql-sdl","description":"Generate GraphQL SDL type definitions from a JSON sample.","category":"data","tags":["json","graphql","sdl","schema","codegen"],"keywords":["json to graphql","sdl","graphql type","schema definition","codegen"],"icon":"Braces","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-graphql-sdl","webPath":"/tools/json-to-graphql-sdl/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
