// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-path-extractor-v1","name":"JSON Path Extractor","slug":"json-path-extractor","description":"Pull values out of JSON with a dot/bracket path like data.items[0].name.","category":"data","tags":["json","query","extract"],"keywords":["json","jsonpath","query","extract","path"],"icon":"FileSearch","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-path-extractor","webPath":"/tools/json-path-extractor/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
