// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-deep-clean-v1","name":"JSON Deep Clean","slug":"json-deep-clean","description":"Recursively strip null, empty, or falsy values from JSON.","category":"data","tags":["json","clean","strip","null","empty"],"keywords":["json","clean","strip","remove null","remove empty","falsy","prune","compact"],"icon":"Eraser","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-deep-clean","webPath":"/tools/json-deep-clean/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
