// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-patch-diff-v1","name":"JSON Patch Generator","slug":"json-patch-diff","description":"Generate an RFC 6902 JSON Patch between two JSON documents.","category":"data","tags":["json","patch","diff","rfc6902","json-pointer"],"keywords":["json patch","json diff","rfc 6902","generate patch","compare json"],"icon":"Diff","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-patch-diff","webPath":"/tools/json-patch-diff/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
