// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-markdown-table-v1","name":"JSON to Markdown Table","slug":"json-to-markdown-table","description":"Render an array of JSON objects as a GitHub-flavored Markdown table.","category":"data","tags":["json","markdown","table"],"keywords":["json","markdown","table","convert","github"],"icon":"FileText","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-markdown-table","webPath":"/tools/json-to-markdown-table/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
