// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-patch-apply-v1","name":"JSON Patch Apply","slug":"json-patch-apply","description":"Apply an RFC 6902 JSON Patch to a JSON document.","category":"data","tags":["json","patch","rfc6902","json-pointer","apply"],"keywords":["json patch","rfc 6902","apply patch","json pointer","add remove replace move"],"icon":"FileCog","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-patch-apply","webPath":"/tools/json-patch-apply/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
