// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-extract-keys-v1","name":"JSON Key Extractor","slug":"json-extract-keys","description":"List every unique key path in a JSON document, optionally with the inferred type of each.","category":"data","tags":["json","keys"],"keywords":["json","keys","paths","extract","schema"],"icon":"ListOrdered","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-extract-keys","webPath":"/tools/json-extract-keys/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
