// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-pointer-resolver-v1","name":"JSON Pointer Resolver","slug":"json-pointer-resolver","description":"Resolve an RFC 6901 JSON Pointer against a JSON document.","category":"data","tags":["json","json-pointer","rfc6901","resolve","lookup"],"keywords":["json pointer","rfc 6901","resolve pointer","json path token","lookup value"],"icon":"Crosshair","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-pointer-resolver","webPath":"/tools/json-pointer-resolver/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
