// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-merge-patch-v1","name":"JSON Merge Patch","slug":"json-merge-patch","description":"Apply an RFC 7386 JSON Merge Patch to a document.","category":"data","tags":["json","merge","patch","rfc7386","diff"],"keywords":["merge patch","rfc 7386","json merge","apply patch","json diff"],"icon":"Combine","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-merge-patch","webPath":"/tools/json-merge-patch/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
