// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-key-case-converter-v1","name":"JSON Key Case Converter","slug":"json-key-case-converter","description":"Recursively convert all JSON object keys to a chosen case.","category":"data","tags":["json","keys","case","camelcase","snake_case"],"keywords":["json","keys","case","camelcase","snake_case","kebab-case","pascalcase","rename keys"],"icon":"CaseSensitive","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-key-case-converter","webPath":"/tools/json-key-case-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
