// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-minify-v1","name":"JSON Minify","slug":"json-minify","description":"Strip whitespace from JSON to produce the smallest valid output.","category":"data","tags":["json","minify","compress","compact"],"keywords":["json minify","compact json","compress json","strip whitespace"],"icon":"Minimize2","relatedTools":["json-formatter","json-to-csv","json-diff"],"packageImportPath":"@open-utility-tools/core/tools/data/json-minify","webPath":"/tools/json-minify/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
