// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-sort-keys-v1","name":"JSON Sort Keys","slug":"json-sort-keys","description":"Recursively sort all object keys in a JSON document alphabetically.","category":"data","tags":["json","sort","keys","normalize","canonical"],"keywords":["json sort keys","alphabetize json","canonical json","normalize"],"icon":"SortAsc","relatedTools":["json-formatter","json-diff","json-minify"],"packageImportPath":"@open-utility-tools/core/tools/data/json-sort-keys","webPath":"/tools/json-sort-keys/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
