// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-mongoose-schema-v1","name":"JSON to Mongoose Schema","slug":"json-to-mongoose-schema","description":"Generate a Mongoose schema definition from a JSON sample.","category":"data","tags":["json","mongoose","mongodb","schema","codegen"],"keywords":["json to mongoose","mongodb schema","mongoose model","odm","codegen"],"icon":"Database","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-mongoose-schema","webPath":"/tools/json-to-mongoose-schema/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
