// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-python-dataclass-v1","name":"JSON to Python Dataclass","slug":"json-to-python-dataclass","description":"Generate Python @dataclass definitions from a JSON sample.","category":"data","tags":["json","python","dataclass","codegen","types"],"keywords":["json to dataclass","python dataclass","json to python","codegen","typing","dto"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-python-dataclass","webPath":"/tools/json-to-python-dataclass/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
