// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-diff-v1","name":"JSON Diff","slug":"json-diff","description":"Compare two JSON documents (normalized & sorted) and see the changes.","category":"data","tags":["json","diff","compare","changes"],"keywords":["json diff","compare json","changes","difference"],"icon":"GitCompare","relatedTools":["text-diff","json-formatter","json-minify"],"packageImportPath":"@open-utility-tools/core/tools/data/json-diff","webPath":"/tools/json-diff/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
