// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-protobuf-v1","name":"JSON to Protobuf","slug":"json-to-protobuf","description":"Generate a proto3 .proto message definition from a JSON sample.","category":"data","tags":["json","protobuf","proto3","grpc","codegen"],"keywords":["json to protobuf","proto3","proto file","message definition","grpc","codegen"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-protobuf","webPath":"/tools/json-to-protobuf/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
