// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-zod-v1","name":"JSON to Zod Schema","slug":"json-to-zod","description":"Generate a Zod validation schema from a JSON sample.","category":"data","tags":["json","zod","typescript","validation","codegen"],"keywords":["json to zod","zod schema","validation","z.object","typescript","codegen"],"icon":"ShieldCheck","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-zod","webPath":"/tools/json-to-zod/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
