// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-json-schema-v1","name":"JSON Schema Generator","slug":"json-to-json-schema","description":"Infer a JSON Schema (draft-07) from a sample JSON document with types and required fields.","category":"data","tags":["json","schema","validation"],"keywords":["json","schema","json schema","generate","validation"],"icon":"Braces","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-json-schema","webPath":"/tools/json-to-json-schema/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
