// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-to-env-v1","name":"JSON to .env","slug":"json-to-env","description":"Flatten a JSON object into dotenv KEY=VALUE lines.","category":"data","tags":["json","env","dotenv","config","flatten"],"keywords":["json to env","dotenv","environment variables","flatten json","config","KEY=VALUE"],"icon":"FileKey","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-to-env","webPath":"/tools/json-to-env/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
