// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-flatten-v1","name":"JSON Flatten / Unflatten","slug":"json-flatten","description":"Flatten nested JSON into dot-notation keys or rebuild nested objects from flattened keys.","category":"data","tags":["json","flatten","unflatten"],"keywords":["json","flatten","unflatten","nested","dot notation"],"icon":"AlignJustify","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-flatten","webPath":"/tools/json-flatten/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
