// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-json-array-dedupe-v1","name":"JSON Array Deduplicate","slug":"json-array-dedupe","description":"Remove duplicate elements from a JSON array, optionally by key.","category":"data","tags":["json","array","dedupe","unique","duplicates"],"keywords":["json","array","dedupe","deduplicate","unique","distinct","remove duplicates","by key"],"icon":"Filter","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/json-array-dedupe","webPath":"/tools/json-array-dedupe/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
