// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-markdown-table-to-json-v1","name":"Markdown Table to JSON","slug":"markdown-table-to-json","description":"Convert a Markdown table into a JSON array of objects keyed by the header row.","category":"data","tags":["markdown","table","json","convert","gfm"],"keywords":["markdown table to json","gfm","table to json","parse markdown table","convert"],"icon":"FileJson","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/markdown-table-to-json","webPath":"/tools/markdown-table-to-json/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
