// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-ndjson-field-filter-v1","name":"NDJSON Field Filter","slug":"ndjson-field-filter","description":"Select, drop, or rename fields across NDJSON records.","category":"data","tags":["ndjson","jsonl","filter","fields","transform"],"keywords":["ndjson","jsonl","field filter","pick fields","drop fields","rename fields"],"icon":"ListFilter","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/ndjson-field-filter","webPath":"/tools/ndjson-field-filter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
