// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-ndjson-to-json-array-v1","name":"NDJSON to JSON Array","slug":"ndjson-to-json-array","description":"Convert NDJSON / JSON Lines to a single JSON array and back.","category":"data","tags":["ndjson","json","json-lines","array","convert"],"keywords":["jsonl","jsonlines","ndjson to array","array to ndjson","round trip","json lines"],"icon":"Rows3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/ndjson-to-json-array","webPath":"/tools/ndjson-to-json-array/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
