// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-sql-create-table-from-json-v1","name":"SQL CREATE TABLE from JSON","slug":"sql-create-table-from-json","description":"Generate a CREATE TABLE statement by inferring columns and types from a JSON array of objects.","category":"data","tags":["sql","json","ddl","schema","create-table"],"keywords":["create table","json to sql","infer schema","ddl","postgres","mysql","sqlite"],"icon":"FileCode","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/sql-create-table-from-json","webPath":"/tools/sql-create-table-from-json/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
