// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-sql-insert-from-json-v1","name":"SQL INSERT from JSON","slug":"sql-insert-from-json","description":"Generate INSERT statements from a JSON array of objects with type-aware value quoting.","category":"data","tags":["sql","json","insert","dml","convert"],"keywords":["insert into","json to sql","bulk insert","multi-row","postgres","mysql","sqlite"],"icon":"Database","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/data/sql-insert-from-json","webPath":"/tools/sql-insert-from-json/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
