// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"data-sql-formatter-v1","name":"SQL Formatter","slug":"sql-formatter","description":"Format and indent SQL queries with keyword casing.","category":"data","tags":["sql","format","beautify","query","prettify"],"keywords":["sql formatter","format sql","beautify sql","pretty sql","indent query"],"icon":"Database","relatedTools":["json-formatter","css-minify","json-to-csv"],"packageImportPath":"@open-utility-tools/core/tools/data/sql-formatter","webPath":"/tools/sql-formatter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
