// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-acronym-maker-v1","name":"Acronym Maker","slug":"acronym-maker","description":"Build an acronym or initialism from a phrase using configurable rules.","category":"text","tags":["acronym","initialism","abbreviation","generator","phrase"],"keywords":["make acronym","first letters","initialism","abbreviate phrase","stop words"],"icon":"CaseSensitive","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/acronym-maker","webPath":"/tools/acronym-maker/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
