// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-alternating-case-converter-v1","name":"Alternating & Inverse Case","slug":"alternating-case-converter","description":"Apply mocking sPoNgEbOb alternating case, inverse case, or random case to text.","category":"text","tags":["case","alternating","mocking","spongebob","random"],"keywords":["spongebob case","mocking text","inverse case","swap case","random case","alternating"],"icon":"Type","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/alternating-case-converter","webPath":"/tools/alternating-case-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
