// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-anagram-solver-v1","name":"Anagram & Letter Rearranger","slug":"anagram-solver","description":"Generate rearrangements of letters and find sub-words from a set of letters offline.","category":"text","tags":["anagram","permutation","wordplay","letters","combinations"],"keywords":["anagram","permutation","rearrange letters","combinations","scramble","wordplay"],"icon":"Dice5","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/anagram-solver","webPath":"/tools/anagram-solver/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
