// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-binary-ascii-art-v1","name":"Bacon / Binary Cipher Encoder","slug":"binary-ascii-art","description":"Encode text with Bacon's biliteral cipher or a custom two-symbol substitution alphabet.","category":"text","tags":["bacon cipher","biliteral","cipher","steganography","encode"],"keywords":["bacon cipher","baconian","biliteral","binary cipher","two symbol","AAAAA BBBBB"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/binary-ascii-art","webPath":"/tools/binary-ascii-art/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
