// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-caesar-cipher-v1","name":"Caesar Cipher","slug":"caesar-cipher","description":"Encode or decode text with a Caesar cipher of any shift amount, the classic reversible letter rotation, with optional brute-force of all 25 shifts.","category":"text","tags":["caesar","cipher","shift","encrypt"],"keywords":["caesar","cipher","shift","encrypt","decode"],"icon":"RotateCw","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/caesar-cipher","webPath":"/tools/caesar-cipher/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
