// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-character-ngram-counter-v1","name":"Character N-Gram Counter","slug":"character-ngram-counter","description":"Count character-level n-grams for linguistics, cryptanalysis, and fingerprinting.","category":"text","tags":["ngram","frequency","cryptanalysis","linguistics","analysis"],"keywords":["character ngram","bigram","trigram","frequency analysis","cipher","fingerprint","language detection"],"icon":"Binary","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/character-ngram-counter","webPath":"/tools/character-ngram-counter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
