// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-coleman-liau-index-v1","name":"Coleman-Liau Index","slug":"coleman-liau-index","description":"Compute the character-based Coleman-Liau readability grade with no syllable counting.","category":"text","tags":["readability","grade level","metrics","writing","analysis"],"keywords":["coleman liau","readability","grade level","reading level","letters per word","writing score"],"icon":"FileText","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/coleman-liau-index","webPath":"/tools/coleman-liau-index/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
