// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-column-aligner-v1","name":"Column Aligner (Elastic Tabstops)","slug":"column-aligner","description":"Align delimited columns into a neat fixed-width table by padding each column to its widest cell.","category":"text","tags":["align","columns","table","format","tabstops"],"keywords":["align columns","elastic tabstops","fixed width","pad columns","tabular","markdown table","pretty print"],"icon":"AlignJustify","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/column-aligner","webPath":"/tools/column-aligner/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
