// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-column-extractor-v1","name":"Column / Field Extractor (cut)","slug":"column-extractor","description":"Extract or reorder fields from delimited lines like the Unix cut command, by index or character range.","category":"text","tags":["cut","fields","columns","extract","delimited"],"keywords":["cut command","extract fields","select columns","reorder columns","character range","csv columns","delimited"],"icon":"Columns3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/column-extractor","webPath":"/tools/column-extractor/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
