// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-count-occurrences-v1","name":"Count Occurrences","slug":"count-occurrences","description":"Count how many times a substring or regex pattern appears in text.","category":"text","tags":["count","occurrences","find","frequency","search"],"keywords":["count occurrences","count matches","word count","substring count","how many"],"icon":"Hash","relatedTools":["find-replace","regex-tester","text-statistics"],"packageImportPath":"@open-utility-tools/core/tools/text/count-occurrences","webPath":"/tools/count-occurrences/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
