// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-deduplicate-words-v1","name":"Deduplicate Words","slug":"deduplicate-words","description":"Remove repeated words from text while preserving order, optionally case-insensitively or only consecutive duplicates.","category":"text","tags":["words","dedupe","duplicate","unique","cleanup"],"keywords":["remove duplicate words","repeated words","unique words","double word typo","the the fix","word dedup"],"icon":"Filter","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/deduplicate-words","webPath":"/tools/deduplicate-words/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
