// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-delimiter-converter-v1","name":"Delimited Text Converter","slug":"delimiter-converter","description":"Convert delimited text between comma, tab, pipe, semicolon, newline, and custom delimiters, ideal for reshaping CSV-style lists.","category":"text","tags":["delimiter","csv","convert"],"keywords":["delimiter","csv","tab separated","comma","convert"],"icon":"Table","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/delimiter-converter","webPath":"/tools/delimiter-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
