// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-emoji-extractor-v1","name":"Emoji Extractor","slug":"emoji-extractor","description":"Extract every emoji from text and list them with counts and code points.","category":"text","tags":["emoji","extract","count","unicode","codepoints"],"keywords":["extract emoji","find emoji","emoji list","emoji frequency","code points","zwj sequence"],"icon":"Sparkles","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/emoji-extractor","webPath":"/tools/emoji-extractor/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
