// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-extract-data-v1","name":"Extract Emails, URLs & Numbers","slug":"extract-data","description":"Pull all email addresses, URLs, phone numbers, IPs, or numbers out of a blob of text into a clean deduplicated list.","category":"text","tags":["extract","emails","urls"],"keywords":["extract","emails","urls","scrape","phone numbers"],"icon":"Filter","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/extract-data","webPath":"/tools/extract-data/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
