// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-gunning-fog-index-v1","name":"Gunning Fog Index","slug":"gunning-fog-index","description":"Estimate the years of formal education needed to understand text on first reading.","category":"text","tags":["readability","gunning fog","grade level","writing","analysis"],"keywords":["gunning fog","fog index","readability","complex words","reading level","grade level","syllables"],"icon":"Glasses","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/gunning-fog-index","webPath":"/tools/gunning-fog-index/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
