// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-haiku-checker-v1","name":"Haiku Syllable Checker","slug":"haiku-checker","description":"Verify whether three lines follow the 5-7-5 haiku syllable pattern.","category":"text","tags":["haiku","syllables","poetry","meter","checker"],"keywords":["haiku","syllable counter","5-7-5","poetry","lune","meter","verse"],"icon":"Feather","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/haiku-checker","webPath":"/tools/haiku-checker/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
