// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-hashtag-generator-v1","name":"Hashtag Generator","slug":"hashtag-generator","description":"Turn phrases into clean hashtags with chosen casing, removing punctuation and merging or splitting words.","category":"text","tags":["hashtag","social","tags","casing","cleanup"],"keywords":["hashtag generator","social media tags","camelcase hashtag","instagram tags","twitter hashtags","pascalcase"],"icon":"Hash","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/hashtag-generator","webPath":"/tools/hashtag-generator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
