// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-keyboard-shift-cipher-v1","name":"Keyboard Shift Cipher","slug":"keyboard-shift-cipher","description":"Shift each key one position left/right/up/down on a QWERTY keyboard, a popular obfuscation puzzle.","category":"text","tags":["cipher","keyboard","qwerty","obfuscate","puzzle"],"keywords":["keyboard shift cipher","qwerty shift","keyboard cipher","one key left","azerty","dvorak","obfuscation"],"icon":"Keyboard","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/keyboard-shift-cipher","webPath":"/tools/keyboard-shift-cipher/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
