// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-keyword-density-analyzer-v1","name":"Keyword Density Analyzer","slug":"keyword-density-analyzer","description":"Measure single-word and phrase keyword density with stop-word filtering for SEO.","category":"text","tags":["seo","keyword density","frequency","stop words","content"],"keywords":["keyword density","seo","stop words","word frequency","content optimization","phrase"],"icon":"Target","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/keyword-density-analyzer","webPath":"/tools/keyword-density-analyzer/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
