// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-leetspeak-v1","name":"Leetspeak Converter","slug":"leetspeak","description":"Convert text to and from leetspeak (1337), swapping letters for numbers and symbols at adjustable intensity.","category":"text","tags":["text","fun","convert"],"keywords":["leetspeak","1337","hacker text","convert","fun"],"icon":"Code","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/leetspeak","webPath":"/tools/leetspeak/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
