// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-lexical-diversity-calculator-v1","name":"Lexical Diversity Calculator","slug":"lexical-diversity-calculator","description":"Measure vocabulary richness with type-token ratio and related metrics.","category":"text","tags":["lexical diversity","ttr","vocabulary","linguistics","metrics"],"keywords":["type token ratio","lexical diversity","vocabulary richness","guiraud","herdan","hapax legomena","ttr"],"icon":"ChartBar","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/lexical-diversity-calculator","webPath":"/tools/lexical-diversity-calculator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
