// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-line-operations-v1","name":"Line Operations","slug":"line-operations","description":"Number, prefix, suffix, or wrap each line of text.","category":"text","tags":["lines","number","prefix","suffix","wrap"],"keywords":["number lines","add prefix","add suffix","wrap lines","line operations"],"icon":"ListOrdered","relatedTools":["sort-lines","remove-duplicates","whitespace-cleaner"],"packageImportPath":"@open-utility-tools/core/tools/text/line-operations","webPath":"/tools/line-operations/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
