// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-lorem-ipsum-variants-v1","name":"Themed Placeholder Text Generator","slug":"lorem-ipsum-variants","description":"Generate themed filler text (hipster, corporate, pirate, tech, bacon, cat) instead of classic Lorem Ipsum.","category":"text","tags":["lorem","placeholder","filler","mockup","generator"],"keywords":["lorem ipsum","hipster ipsum","bacon ipsum","corporate ipsum","pirate ipsum","cat ipsum","dummy text","placeholder text"],"icon":"FileText","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/lorem-ipsum-variants","webPath":"/tools/lorem-ipsum-variants/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
