// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-morse-to-text-visual-v1","name":"Morse Code Visual Decoder","slug":"morse-to-text-visual","description":"Decode Morse with timing/visual rendering and encode text with adjustable dot, dash, and gap symbols.","category":"text","tags":["morse","cipher","decode","encode","visual"],"keywords":["morse code","morse decoder","morse encoder","dot dash","itu morse","tap rhythm","sos"],"icon":"Radio","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/morse-to-text-visual","webPath":"/tools/morse-to-text-visual/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
