// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-number-lines-v1","name":"Number Each Line","slug":"number-lines","description":"Generate a sequence and prefix lines with auto-incrementing numbers using a start value, step, and zero-padding.","category":"text","tags":["text","lines","numbering"],"keywords":["line numbers","numbering","sequence","enumerate","increment"],"icon":"ListOrdered","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/number-lines","webPath":"/tools/number-lines/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
