// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-outline-to-list-v1","name":"Indented Outline ↔ Nested List","slug":"outline-to-list","description":"Convert tab/space-indented outlines to Markdown/HTML nested lists, or flatten nested lists to an outline.","category":"text","tags":["outline","list","nested","markdown","html"],"keywords":["outline","nested list","markdown list","html ul ol","indent","tree","flatten","breadcrumb path"],"icon":"ListTree","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/outline-to-list","webPath":"/tools/outline-to-list/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
