// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-palindrome-checker-v1","name":"Palindrome Checker","slug":"palindrome-checker","description":"Check if text is a palindrome and find palindromic words and substrings.","category":"text","tags":["palindrome","text","analysis","string","wordplay"],"keywords":["palindrome","reverse","mirror","longest palindromic substring","racecar","word"],"icon":"ArrowLeftRight","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/palindrome-checker","webPath":"/tools/palindrome-checker/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
