// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-paragraph-splitter-v1","name":"Paragraph Splitter & Joiner","slug":"paragraph-splitter","description":"Split text into separated paragraphs or rejoin wrapped lines into paragraphs.","category":"text","tags":["paragraph","split","join","unwrap","reflow"],"keywords":["paragraph splitter","join lines","unwrap text","rewrap","hard wrap","blank lines","reflow"],"icon":"Pilcrow","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/paragraph-splitter","webPath":"/tools/paragraph-splitter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
