// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-pig-latin-v1","name":"Pig Latin Translator","slug":"pig-latin","description":"Translate English text to or from Pig Latin, moving leading consonants and appending the classic -ay ending.","category":"text","tags":["text","fun","translate"],"keywords":["pig latin","translate","fun","language game","encode"],"icon":"Languages","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/pig-latin","webPath":"/tools/pig-latin/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
