// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-regex-tester-v1","name":"Regex Tester","slug":"regex-tester","description":"Test JavaScript regular expressions live with match highlighting and groups.","category":"text","tags":["regex","regexp","test","match","pattern"],"keywords":["regex tester","regular expression","pattern","match","capture groups"],"icon":"Regex","relatedTools":["find-replace","sort-lines","word-count"],"packageImportPath":"@open-utility-tools/core/tools/text/regex-tester","webPath":"/tools/regex-tester/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
