// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-remove-duplicates-v1","name":"Remove Duplicate Lines","slug":"remove-duplicates","description":"Strip duplicate lines, keeping first occurrence, with optional case-insensitivity.","category":"text","tags":["duplicate","dedupe","unique","lines"],"keywords":["remove duplicates","dedupe","unique lines","distinct"],"icon":"Filter","relatedTools":["sort-lines","word-count","whitespace-cleaner"],"packageImportPath":"@open-utility-tools/core/tools/text/remove-duplicates","webPath":"/tools/remove-duplicates/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
