// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-rot13-v1","name":"ROT13 / Caesar Cipher","slug":"rot13","description":"Apply ROT13 or a Caesar shift cipher to text (reversible).","category":"text","tags":["rot13","caesar","cipher","shift","rotate"],"keywords":["rot13","caesar cipher","shift cipher","rotate letters","encode"],"icon":"Shuffle","relatedTools":["morse-code","base64-text","case-converter"],"packageImportPath":"@open-utility-tools/core/tools/text/rot13","webPath":"/tools/rot13/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
