// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-runic-transliterator-v1","name":"Runic Transliterator","slug":"runic-transliterator","description":"Convert Latin text to Elder Futhark or Younger Futhark runes (and back) using a fixed letter mapping.","category":"text","tags":["runes","futhark","transliterate","norse","viking"],"keywords":["runic","elder futhark","younger futhark","runes","norse","viking alphabet","transliterate"],"icon":"Languages","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/runic-transliterator","webPath":"/tools/runic-transliterator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
