// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-sentence-case-converter-v1","name":"Sentence Case Converter","slug":"sentence-case-converter","description":"Lowercase text then capitalize the first letter of each sentence, preserving common acronyms and the pronoun I.","category":"text","tags":["case","sentence","capitalize","text","format"],"keywords":["sentence case","capitalize sentences","first letter","lowercase","acronym","pronoun i"],"icon":"Pilcrow","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/sentence-case-converter","webPath":"/tools/sentence-case-converter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
