// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-shuffle-lines-v1","name":"Shuffle Lines","slug":"shuffle-lines","description":"Randomly shuffle the order of lines, with an option to pick a random subset or a single random line.","category":"text","tags":["shuffle","randomize","lines"],"keywords":["shuffle","randomize","random order","lines","scramble"],"icon":"Shuffle","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/shuffle-lines","webPath":"/tools/shuffle-lines/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
