// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-smog-readability-grade-v1","name":"SMOG Readability Grade","slug":"smog-readability-grade","description":"Calculate the SMOG grade, the standard readability measure for healthcare and consumer text.","category":"text","tags":["readability","smog","grade","text","analysis"],"keywords":["smog","readability","grade level","polysyllable","reading age","healthcare text"],"icon":"Microscope","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/smog-readability-grade","webPath":"/tools/smog-readability-grade/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
