// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-strikethrough-text-variants-v1","name":"Strikethrough, Underline & Overline Combiner","slug":"strikethrough-text-variants","description":"Add combining strikethrough, underline, overline, or slash overlays to text for plain-text styling.","category":"text","tags":["text","unicode","decorate","style"],"keywords":["strikethrough","underline","overline","combining","crossed out","slash","unicode style"],"icon":"Type","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/strikethrough-text-variants","webPath":"/tools/strikethrough-text-variants/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
