// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-superscript-subscript-v1","name":"Superscript & Subscript Text","slug":"superscript-subscript","description":"Convert text to Unicode superscript or subscript characters for inline chemistry/math notation.","category":"text","tags":["text","unicode","superscript","subscript"],"keywords":["superscript","subscript","unicode","chemistry","math","exponent","H2O","x squared"],"icon":"Superscript","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/superscript-subscript","webPath":"/tools/superscript-subscript/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
