// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-syllable-counter-v1","name":"Syllable Counter","slug":"syllable-counter","description":"Count syllables in words and whole text using an English heuristic algorithm.","category":"text","tags":["syllable","text","poetry","haiku","count"],"keywords":["syllable","count","haiku","poetry","meter","vowel groups","phonetics"],"icon":"Speech","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/syllable-counter","webPath":"/tools/syllable-counter/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
