// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-tap-code-cipher-v1","name":"Tap Code Cipher","slug":"tap-code-cipher","description":"Encode text into Polybius-square tap code (rows.columns) and decode tap sequences back to letters.","category":"text","tags":["text","cipher","encode","decode"],"keywords":["tap code","polybius","prisoner","pow","cipher","knock code","encode","decode"],"icon":"Grid3x3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/tap-code-cipher","webPath":"/tools/tap-code-cipher/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
