// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-to-columns-v1","name":"Wrap Text Into Columns","slug":"text-to-columns","description":"Reflow a single stream of lines into multiple side-by-side newspaper-style columns.","category":"text","tags":["columns","layout","wrap","monospace","reflow"],"keywords":["multi column","newspaper layout","column wrap","side by side","grid text"],"icon":"Rows3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-to-columns","webPath":"/tools/text-to-columns/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
