// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-anonymizer-v1","name":"PII Placeholder Anonymizer","slug":"text-anonymizer","description":"Replace emails, phone numbers, and other PII patterns with placeholder tokens.","category":"text","tags":["text","privacy","pii","redact"],"keywords":["anonymize","redact","pii","mask","email","phone","ip address","credit card","privacy"],"icon":"Eye","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-anonymizer","webPath":"/tools/text-anonymizer/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
