// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-redundancy-finder-v1","name":"Repeated Phrase Finder","slug":"text-redundancy-finder","description":"Find phrases repeated multiple times in text to catch wordiness and filler.","category":"text","tags":["phrases","repetition","editing","analysis","wordiness"],"keywords":["repeated phrases","redundancy","filler","duplicate","n-gram","editing","cliche"],"icon":"Repeat","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-redundancy-finder","webPath":"/tools/text-redundancy-finder/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
