// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-text-bracket-matcher-v1","name":"Bracket & Quote Balance Checker","slug":"text-text-bracket-matcher","description":"Verify that brackets, parentheses, braces, and quotes are balanced in text.","category":"text","tags":["brackets","balance","parentheses","validate","quotes"],"keywords":["balanced brackets","matching parentheses","brace balance","quote balance","syntax check","unbalanced","mismatched bracket"],"icon":"Brackets","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-text-bracket-matcher","webPath":"/tools/text-text-bracket-matcher/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
