// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-text-sort-by-length-v1","name":"Sort Lines by Length","slug":"text-text-sort-by-length","description":"Reorder lines by character length, ascending or descending, with tie-breaking.","category":"text","tags":["sort","lines","length","order","text"],"keywords":["sort by length","longest lines","shortest lines","reorder","arrange lines"],"icon":"SortAsc","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-text-sort-by-length","webPath":"/tools/text-text-sort-by-length/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
