// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-case-statistics-report-v1","name":"Text Case Statistics Report","slug":"text-case-statistics-report","description":"Counts uppercase, lowercase, digit, punctuation and whitespace characters and reports their percentages.","category":"text","tags":["statistics","count","characters","analyze","report"],"keywords":["character count","uppercase lowercase count","digit count","punctuation count","whitespace count","text statistics","letter frequency classes"],"icon":"ChartBar","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-case-statistics-report","webPath":"/tools/text-case-statistics-report/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
