// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-text-column-sort-v1","name":"Multi-Key Column Sort","slug":"text-text-column-sort","description":"Sort delimited rows by one or more columns with per-key type and direction.","category":"text","tags":["sort","columns","csv","multi-key","table"],"keywords":["sort csv","multi column sort","sort by column","stable sort","sort tsv","order rows","sort by number date"],"icon":"Columns3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-text-column-sort","webPath":"/tools/text-text-column-sort/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
