// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-truncator-v1","name":"Text Truncator","slug":"text-truncator","description":"Truncate text or each line to a maximum length by characters or words, appending an ellipsis or custom suffix.","category":"text","tags":["truncate","shorten","limit"],"keywords":["truncate","shorten","ellipsis","limit","trim"],"icon":"Scissors","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-truncator","webPath":"/tools/text-truncator/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
