// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-repeater-v1","name":"Text Repeater","slug":"text-repeater","description":"Repeat a piece of text a chosen number of times, separated by newlines, spaces, or a custom delimiter.","category":"text","tags":["repeat","duplicate","multiply"],"keywords":["repeat","duplicate","multiply","copies","loop"],"icon":"Repeat","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-repeater","webPath":"/tools/text-repeater/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
