// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-text-to-slug-history-v1","name":"Slug Collision Disambiguator","slug":"text-text-to-slug-history","description":"Generate sequential unique slugs from a list, appending numeric suffixes on collision.","category":"text","tags":["slug","unique","collision","url","cms"],"keywords":["unique slug","slug suffix","permalink","duplicate slug","slugify list"],"icon":"Tags","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-text-to-slug-history","webPath":"/tools/text-text-to-slug-history/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
