// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-roman-to-fancy-numbering-v1","name":"List Number Style Converter","slug":"text-roman-to-fancy-numbering","description":"Renumbers a list using decimal, roman numerals, or letter sequences (a, b, c / A, B, C).","category":"text","tags":["list","numbering","roman","letters","renumber"],"keywords":["renumber list","roman numerals","lettered list","ordered list","list markers","decimal numbering","a b c list"],"icon":"ListOrdered","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-roman-to-fancy-numbering","webPath":"/tools/text-roman-to-fancy-numbering/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
