// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-snake-to-title-humanizer-v1","name":"Identifier Humanizer","slug":"text-snake-to-title-humanizer","description":"Turns snake_case, kebab-case, or camelCase identifiers into human-readable Title Case labels.","category":"text","tags":["humanize","title-case","identifier","snake-case","camel-case"],"keywords":["humanize identifier","snake case to title","camelCase to words","kebab case","variable name to label","title case","split words"],"icon":"WholeWord","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-snake-to-title-humanizer","webPath":"/tools/text-snake-to-title-humanizer/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
