// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-text-align-pad-v1","name":"Text Alignment & Padding","slug":"text-align-pad","description":"Pad or align each line to a fixed width, left, right, or centered, with a chosen fill character for tidy fixed-width columns.","category":"text","tags":["align","pad","format"],"keywords":["align","pad","center","right align","fixed width"],"icon":"AlignJustify","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/text-align-pad","webPath":"/tools/text-align-pad/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
