// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-transliterate-cyrillic-v1","name":"Cyrillic Transliteration","slug":"transliterate-cyrillic","description":"Transliterate between Cyrillic and Latin using selectable schemes (GOST, BGN/PCGN, scientific, ISO 9).","category":"text","tags":["cyrillic","transliterate","romanize","russian","latin"],"keywords":["cyrillic to latin","romanization","iso 9","gost","bgn pcgn","russian transliteration"],"icon":"Languages","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/transliterate-cyrillic","webPath":"/tools/transliterate-cyrillic/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
