// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-unicode-inspector-v1","name":"Unicode Inspector","slug":"unicode-inspector","description":"Break text into code points with hex, decimal, UTF-8 bytes and names.","category":"text","tags":["unicode","code point","utf-8","inspect","character"],"keywords":["unicode inspector","code points","utf-8 bytes","character codes","escape unicode"],"icon":"Languages","relatedTools":["ascii-table","binary-text","hex-text"],"packageImportPath":"@open-utility-tools/core/tools/text/unicode-inspector","webPath":"/tools/unicode-inspector/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
