// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-whitespace-cleaner-v1","name":"Whitespace Cleaner","slug":"whitespace-cleaner","description":"Trim lines, collapse spaces, strip blank lines, and normalize whitespace.","category":"text","tags":["whitespace","trim","clean","spaces","tabs"],"keywords":["whitespace","trim","collapse spaces","remove blank lines","clean text"],"icon":"Eraser","relatedTools":["remove-duplicates","sort-lines","word-count"],"packageImportPath":"@open-utility-tools/core/tools/text/whitespace-cleaner","webPath":"/tools/whitespace-cleaner/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
