// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-whitespace-visualizer-v1","name":"Whitespace & Special Character Visualizer","slug":"whitespace-visualizer","description":"Reveal hidden spaces, tabs, and line endings by replacing them with visible glyphs.","category":"text","tags":["whitespace","visualize","tabs","line-endings","debug"],"keywords":["show whitespace","reveal spaces","visualize tabs","line endings","crlf lf","trailing whitespace"],"icon":"Eye","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/whitespace-visualizer","webPath":"/tools/whitespace-visualizer/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
