// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-wide-spaced-text-v1","name":"Letter & Word Spacing Expander","slug":"wide-spaced-text","description":"Insert spaces or custom separators between letters and words to create s p a c e d  o u t text.","category":"text","tags":["spacing","wide","vaporwave","letter-spacing","novelty"],"keywords":["wide text","spaced out text","letter spacing","full width space","vaporwave space","aesthetic text"],"icon":"TextCursor","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/wide-spaced-text","webPath":"/tools/wide-spaced-text/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
