// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-word-length-distribution-v1","name":"Word & Sentence Length Distribution","slug":"word-length-distribution","description":"Show how word lengths and sentence lengths are distributed across text.","category":"text","tags":["distribution","statistics","histogram","analysis","length"],"keywords":["word length","sentence length","histogram","distribution","mean median mode","standard deviation","dispersion"],"icon":"BarChart3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/word-length-distribution","webPath":"/tools/word-length-distribution/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
