// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-word-frequency-v1","name":"Word Frequency Counter","slug":"word-frequency","description":"Count how often each word appears and rank them by frequency, with options to ignore case and skip common stop words.","category":"text","tags":["frequency","keyword density","ranking","tally"],"keywords":["frequency","keyword density","tally","occurrences","ranking"],"icon":"BarChart3","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/word-frequency","webPath":"/tools/word-frequency/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
