// AUTO-GENERATED by packages/core/scripts/gen-tools-catalog.ts -- do not edit.
import type { ToolPackageEntry } from '../types';

export const tool = {"id":"text-zero-width-char-stripper-v1","name":"Zero-Width & Invisible Character Stripper","slug":"zero-width-char-stripper","description":"Detect and remove invisible zero-width and formatting characters from pasted text.","category":"text","tags":["zero-width","invisible","unicode","clean","sanitize"],"keywords":["zero width space","invisible characters","strip zwsp","remove bom","soft hyphen","directional marks"],"icon":"Ghost","relatedTools":[],"packageImportPath":"@open-utility-tools/core/tools/text/zero-width-char-stripper","webPath":"/tools/zero-width-char-stripper/"} as const satisfies ToolPackageEntry;
export const metadata = tool;
export default tool;
